<script setup lang="ts">
import {computed,ref,watch} from 'vue';
import {ApiError,StaleResponse,label,formatTime,type Row,type Page,type Space} from '@qixu/client';
import {api,asset,auth,baseUrl,client,errorMessage,go,icon,releaseDownloaded} from '../runtime';
const props=defineProps<{view:string;resourceId:number}>();
const id=computed(()=>props.resourceId);
const data=ref<Row>({}),items=ref<Row[]>([]),shorts=ref<Row[]>([]),venues=ref<Row[]>([]),parts=ref<Row[]>([]),myBatches=ref<Row[]>([]),options=ref<Row[]>([]),error=ref(''),message=ref(''),busy=ref(false),loading=ref(false),page=ref(1),total=ref(0);
const username=ref(''),password=ref(''),origin=ref(String(uni.getStorageSync('qixu.apiOrigin')||'')),spaceId=ref(String(props.resourceId||'')),category=ref('OUTLET'),description=ref(''),statement=ref('');
const feedbackSpace=ref<Space|null>(null),attachments=ref<{id:number;path:string}[]>([]);
const preferences=ref<Record<string,number>>({}),keepWaitlist=ref(true),dirty=ref(false),impact=ref<Row|null>(null),impactOffer=ref(0),agreedImpact=ref(false),exitConfirmation=ref(false);
let revision=0;const applicationsPage=ref(1),applicationsTotal=ref(0);
const batch=computed(()=>data.value.batch||{});
const categories=[{value:'OUTLET',label:'插座故障'},{value:'LIGHT',label:'照明故障'},{value:'DESK',label:'桌面问题'},{value:'ENVIRONMENT',label:'环境问题'},{value:'INFORMATION',label:'档案不符'},{value:'OTHER',label:'其他事实'}];
const outcomeReasons:Record<string,string>={NO_ACCEPTABLE_EDGE:'本轮没有满足你硬约束的位置',FIXED_WAITLIST:'可接受的位置已分配完，进入固定候补',PREFERRED_OFFER:'已提供首选要约',AUTHORIZED_FALLBACK_OFFER:'按你的预授权提供兜底要约'};
const arrangementStates:Record<string,string>={TEMPORARY:'临时安排',TEMPORARILY_UNAVAILABLE:'暂不可用',ARRANGEMENT_REQUIRED:'尚需明确处置'};
const selectedCount=computed(()=>Object.values(preferences.value).filter(v=>v>0).length);
async function load(){const run=++revision;loading.value=true;error.value='';try{
 if(props.view==='profile'){if(!auth.session){try{const o=await api<Row[]>('/auth/options');if(run===revision)options.value=o;}catch(e){if(!(e instanceof ApiError&&e.status===404))throw e;}}return;}
 if(!auth.session)return;
 if(props.view==='batch'){const r=await api<Row>('/preparation-batches/'+props.resourceId+'/application','application');if(run!==revision)return;data.value=r;if(!dirty.value){preferences.value=Object.fromEntries((r.preferences||[]).map((p:Row)=>[String(p.seatId),Number(p.rank)]));keepWaitlist.value=r.applied?Boolean(r.keep_waitlist):true;}}
 else if(props.view==='event'){const r=await api('/events/'+props.resourceId);if(run===revision)data.value=r;}
 else if(props.view==='messages'){const r=await api<Row>('/inbox');if(run!==revision)return;items.value=r.items;total.value=r.unread;}
 else if(props.view==='feedback'){if(props.resourceId){const sp=await api<Space>('/spaces/'+props.resourceId);if(run!==revision)return;feedbackSpace.value=sp;spaceId.value=String(sp.id);}const r=await api<Page<Row>>('/feedback?page='+page.value);if(run!==revision)return;items.value=r.items;total.value=r.total;}
 else if(props.view==='report'){const report=await api<Row>('/feedback/'+props.resourceId);if(run!==revision)return;data.value=report;clearAttachments();for(const a of report.attachments||[]){const file=await client.get<{tempFilePath:string}>('/api/v1/feedback/'+props.resourceId+'/attachments/'+a.id,'photo-'+a.id,'FILE');if(run!==revision){releaseDownloaded(file.tempFilePath);return;}attachments.value.push({id:a.id,path:file.tempFilePath});}}
 else if(props.view==='governance'){if(props.resourceId){const r=await api('/governance-cases/'+props.resourceId);if(run===revision)data.value=r;}else {const r=await api<Page<Row>>('/governance-cases?page='+page.value);if(run!==revision)return;items.value=r.items;total.value=r.total;}}
 else if(props.view==='mine'){const [a,b,c,applications]=await Promise.all([api<Row[]>('/reservations'),api<Row[]>('/venue-requests'),api<Row[]>('/participations'),api<Page<Row>>('/preparation-applications?page='+applicationsPage.value)]);if(run!==revision)return;shorts.value=a;venues.value=b;parts.value=c;myBatches.value=applications.items;applicationsTotal.value=applications.total;}
 }catch(e){if(run===revision&&!(e instanceof StaleResponse))error.value=errorMessage(e);}finally{if(run===revision)loading.value=false;}}
async function write(path:string,body:unknown,sensitive=false){if(busy.value)return;const run=revision;busy.value=true;error.value='';message.value='';try{const result=await client.mutate<Row>('/api/v1'+path,body,{sensitive});if(run!==revision)return;message.value='已确认回执 '+result.receipt.key.slice(-8)+'。';if(props.view==='batch')dirty.value=false;await load();return result;}catch(e){if(run===revision)error.value=errorMessage(e);}finally{busy.value=false;}}
async function login(){if(busy.value)return;busy.value=true;error.value='';try{await client.login(username.value,password.value);password.value='';await client.bootstrap();message.value='已登录，当前身份 '+auth.session?.actor.displayName;go('home',undefined,true);}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
async function logout(){if(busy.value)return;busy.value=true;try{await client.logout();password.value='';data.value={};items.value=[];}catch(e){error.value=errorMessage(e);}finally{busy.value=false;}}
function chooseDemo(index:number){username.value=String(options.value[index].username);password.value='qixu-demo';}
function saveOrigin(){if(!/^https:\/\/[^/]+$/.test(origin.value)){error.value='地址需为 HTTPS origin，不包含路径、账号或参数。';return;}uni.setStorageSync('qixu.apiOrigin',origin.value);message.value='服务地址已保存，请重新打开小程序，先核对登录身份。';}
function rank(seat:number,n:number){preferences.value={...preferences.value,[seat]:preferences.value[seat]===n?0:n};dirty.value=true;}
function submitPreferences(){const choices=Object.entries(preferences.value).filter(([,rank])=>rank>0).map(([seatId,rank])=>({seatId:Number(seatId),rank}));if(!choices.length){error.value='请选择至少一个真正可接受的座位。';return;}const ranks=[...new Set(choices.map(c=>c.rank))].sort();if(ranks.some((r,i)=>r!==i+1)){error.value='志愿等级需要从1开始连续填写。';return;}write('/preparation-batches/'+props.resourceId+'/application',{version:data.value.current_version||0,preferences:choices,keepWaitlist:keepWaitlist.value});}
async function offerPreview(offer:Row){const run=revision;impact.value=null;impactOffer.value=offer.id;agreedImpact.value=false;try{const result=await api<Row>('/long-offers/'+offer.id+'/impact','offer-impact');if(run===revision&&impactOffer.value===offer.id)impact.value=result;}catch(e){if(run===revision&&impactOffer.value===offer.id)error.value=errorMessage(e);}}
function acceptOffer(offer:Row){if(impactOffer.value!==offer.id||!impact.value){error.value='请先查看要约当前安排。';return;}const hash=String(impact.value.impactHash||'');if(impact.value.requiresAcknowledgement&&!agreedImpact.value){error.value='请先确认已阅读临时安排。';return;}write('/long-offers/'+offer.id+'/actions',{version:offer.version,action:'ACCEPT',...(hash?{impactHash:hash}:{})});}
function inboxView(item:Row){const views:Record<string,string>={BATCH:'batch',EVENT:'event',FEEDBACK:'report',GOVERNANCE:'governance',SPACE:'space',SHORT:'mine',VENUE:'mine',BLOCK:'mine'};go(views[item.entity_type]||'mine',Number(item.entity_id));}
function clearAttachments(){for(const a of attachments.value)releaseDownloaded(a.path);attachments.value=[];}
function uploadPhoto(){if(busy.value)return;const run=revision;uni.chooseImage({count:1,sizeType:['original'],sourceType:['album'],success:async res=>{if(run!==revision)return;const f=Array.isArray(res.tempFiles)?res.tempFiles[0]:undefined;if(f&&f.size>1048576){error.value='照片须不超过1MiB，请选择更小的图片。';return;}await write('/feedback/'+props.resourceId+'/attachments',{filePath:res.tempFilePaths[0]},true);},fail:err=>{if(!err.errMsg.includes('cancel'))error.value='未能选择照片，请重新选择。';}});}
function leave(){revision++;clearAttachments();feedbackSpace.value=null;description.value='';statement.value='';password.value='';data.value={};items.value=[];client.clearSensitive();}
defineExpose({refresh:load,leave});
watch(()=>[props.view,props.resourceId,auth.generation],()=>{revision++;clearAttachments();feedbackSpace.value=null;data.value={};items.value=[];shorts.value=[];venues.value=[];parts.value=[];myBatches.value=[];description.value='';statement.value='';preferences.value={};dirty.value=false;impact.value=null;exitConfirmation.value=false;load();},{immediate:true});
</script>
<template>
<view v-if="error" class="error-note" role="alert">{{error}}<button role="button" class="text-button" @click="load">刷新当前事实（保留输入）</button></view><view v-if="message" class="info-note">{{message}}</view><text v-if="loading" class="loading">正在核对…</text>
<template v-if="view==='profile'">
 <view class="profile-brand"><image :src="asset('qixu-brand.png')" mode="aspectFit"/><text>校园空间预约与使用权管理</text></view>
 <view v-if="auth.session" class="panel"><text class="section-title">{{auth.session.actor.displayName}}</text><text class="muted">{{{STUDENT:'学生',TEACHER:'老师',ADMIN:'管理员'}[auth.session.actor.role]}} · {{auth.session.actor.username}}</text><text class="caption">身份由服务端确认。老师与管理员使用独立管理Web处理工作。</text><button role="button" @click="go('mine')">我的使用安排</button><button role="button" @click="go('favorites')">收藏与对比</button><button role="button" @click="go('governance')">陈述与申诉</button><button role="button" @click="go('about')">使用原则</button><button role="button" :disabled="busy" @click="logout">退出当前登录</button></view>
 <view v-else class="panel"><text class="section-title">登录期序</text><label class="field-label">账号<input v-model="username" maxlength="64" placeholder="输入账号" autocomplete="username"/></label><label class="field-label">密码<input v-model="password" password maxlength="72" placeholder="输入密码" autocomplete="current-password"/></label><button role="button" class="primary" :disabled="busy" @click="login">{{busy?'正在确认身份…':'登录'}}</button><view v-if="options.length" class="demo-options"><text class="caption">当前服务明确开放演示身份；演示密码 qixu-demo</text><button role="button" v-for="(o,i) in options" :key="o.username" class="text-button" @click="chooseDemo(i)">{{o.displayName}} · {{o.role==='STUDENT'?'学生':o.role==='TEACHER'?'老师':'管理员'}}</button></view></view>
 <!-- #ifndef H5 -->
 <view class="panel"><text class="card-title">小程序连接设置</text><text class="caption">H5使用同源代理；微信小程序使用单独部署的HTTPS API。更换服务后重新打开并核对身份。</text><label class="field-label">API服务地址<input v-model="origin" placeholder="https://api.example.edu" maxlength="200"/></label><button role="button" @click="saveOrigin">保存原生服务地址</button></view>
 <!-- #endif -->
</template>
<template v-else-if="view==='mine'">
 <view class="section-heading"><text class="section-title">长期使用安排</text><button role="button" class="text-button" @click="go('batches')">全部批次</button></view><button role="button" v-for="a in myBatches" :key="a.id" class="list-row" @click="go('batch',a.batch_id)"><image :src="icon('book-open','red')"/><view><text class="card-title">{{a.batch.title}}</text><text class="muted">{{label(a.batch.effectivePhase)}} · {{a.entitlements?.filter((r:Row)=>r.effectiveStatus==='ACTIVE').length?'有有效使用权':a.waitlist?.effectiveStatus==='ACTIVE'?'在稳定候补中':'查看明确结果与要约'}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!myBatches.length" class="empty">没有已保存的长期申请，可查看开放批次。</text>
 <view v-if="applicationsTotal>20" class="pagination"><button role="button" :disabled="applicationsPage<=1||loading" @click="applicationsPage--;load()">前一页申请</button><text>{{applicationsPage}} / {{Math.ceil(applicationsTotal/20)}}</text><button role="button" :disabled="applicationsPage*20>=applicationsTotal||loading" @click="applicationsPage++;load()">后一页申请</button></view><text class="section-title">短期预约</text><view v-for="r in shorts" :key="r.id" class="panel"><text class="card-title">{{r.code||r.space_id}} · {{label(r.effectiveStatus||r.status)}}</text><text class="muted">{{formatTime(r.starts_at)}} — {{formatTime(r.ends_at)}}</text><text class="caption">到场期限 {{formatTime(r.check_in_deadline)}}</text><button role="button" class="text-button" @click="go('space',r.space_id)">空间档案</button><view class="actions"><button role="button" v-if="(r.effectiveStatus||r.status)==='PENDING'" :disabled="busy" @click="write('/reservations/'+r.id+'/actions',{version:r.version,action:'CHECK_IN'})">到场确认</button><button role="button" v-if="(r.effectiveStatus||r.status)==='PENDING'" :disabled="busy" @click="write('/reservations/'+r.id+'/actions',{version:r.version,action:'CANCEL'})">取消预约</button><button role="button" v-if="(r.effectiveStatus||r.status)==='CHECKED_IN'" :disabled="busy" @click="write('/reservations/'+r.id+'/actions',{version:r.version,action:'END'})">离开并释放</button></view><view v-if="r.relocations?.length" class="info-note"><text v-for="(x,i) in r.relocations" :key="i">明确换位：{{x.original_code}} → {{x.replacement_code}} · {{formatTime(x.created_at)}}。请以新预约的当前状态和期限为准。</text></view></view><text v-if="!loading&&!error&&!shorts.length" class="empty">没有短期预约，可从空间地图查找。</text>
 <text class="section-title">场地申请</text><view v-for="r in venues" :key="r.id" class="panel"><text class="card-title">{{r.purpose}} · {{label(r.status)}}</text><text class="muted">{{r.code}} · {{formatTime(r.starts_at)}} — {{formatTime(r.ends_at)}} · {{r.people}}人</text><text v-if="r.decision_note" class="description">审批说明：{{r.decision_note}}</text><button role="button" class="text-button" @click="go('space',r.space_id)">查看空间</button><button role="button" v-if="['SUBMITTED','APPROVED'].includes(r.status)" :disabled="busy" @click="write('/venue-requests/'+r.id+'/actions',{version:r.version,action:'CANCEL',reason:'申请人主动取消'})">取消场地申请</button></view><text v-if="!loading&&!error&&!venues.length" class="empty">没有场地申请。</text>
 <text class="section-title">活动预约</text><button role="button" v-for="r in parts" :key="r.id" class="list-row" @click="go('event',r.id)"><view><text class="card-title">{{r.title||'活动 '+r.id}}</text><text class="muted">{{label(r.myParticipation?.status)}} · 顺序{{r.myParticipation?.sequence_number}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!parts.length" class="empty">没有活动预约。</text>
</template>
<template v-else-if="view==='batch'&&data.batch">
 <view class="panel"><text class="section-title">{{batch.title}}</text><text class="status-tag">{{label(batch.effectivePhase)}}</text><text class="muted">使用周期 {{formatTime(batch.cycle_starts_at)}} — {{formatTime(batch.cycle_ends_at)}}</text><view class="fact-row"><text>申请截止</text><text>{{formatTime(batch.closes_at)}}</text></view><view class="fact-row"><text>结果最迟公布</text><text>{{formatTime(batch.result_deadline)}}</text></view><view class="fact-row"><text>首次确认截止</text><text>{{formatTime(batch.confirmation_deadline)}}</text></view><view class="fact-row"><text>递补停止</text><text>{{formatTime(batch.promotion_until)}}</text></view><text class="caption">固定输入、未来公开随机源、最大可满足人数优先。不以提交手速或学习时长决定中签。</text><text v-if="batch.failure_reason" class="error-note">本轮未产生合法结果：{{batch.failure_reason}}。可选其他真实空间。</text></view>
 <view v-if="data.applied" class="panel"><text class="section-title">我的申请</text><text class="muted">编号{{data.id}} · 已接收版本{{data.current_version}}<text v-if="data.frozen_version"> · 冻结版本{{data.frozen_version}}</text></text><text class="caption">接收时间 {{formatTime(data.accepted_at)}}</text><text v-if="data.currentEligibility&&!data.currentEligibility.eligible" class="error-note">当前资格不可用：{{data.currentEligibility.reason}}</text><text v-if="data.outcome?.reason" class="info-note">本轮结果：{{data.outcome.space_id ? '已提供第'+data.outcome.preference_rank+'志愿要约' : '未获得可接受席位'}}。{{outcomeReasons[data.outcome.reason]||'可查看公开复算材料'}}。请继续查看有效要约/使用权和候补。</text><text v-if="data.waitlist?.effectiveStatus==='ACTIVE'" class="info-note">候补沿用本轮固定顺序{{data.waitlist.lottery_position}}，并受可接受条件约束。候补不保证有席位。</text>
  <view v-for="r in data.entitlements||[]" :key="r.id" class="entitlement"><text class="card-title">{{r.code}} · {{label(r.effectiveStatus)}}</text><text class="muted">{{formatTime(r.starts_at)}} — {{formatTime(r.ends_at)}}</text><text class="caption">暂离不丢失长期使用权。</text><button role="button" class="text-button" @click="go('space',r.space_id)">查看空间</button></view>
  <view v-for="o in data.offers||[]" :key="o.id" class="entitlement"><text class="card-title">{{o.code}} · {{label(o.effectiveStatus)}}</text><text class="muted">第{{o.preference_rank}}志愿 · 确认截至{{formatTime(o.deadline)}}</text><text v-if="o.upgrade_from_id" class="caption">这是升级要约；确认成功才原子释放原席位。</text><template v-if="o.effectiveStatus==='OPEN'"><button role="button" @click="offerPreview(o)">查看当前使用安排</button><view v-if="impactOffer===o.id&&impact" class="info-note"><text v-if="!(impact.segments||[]).length">没有查询到临时安排，原位按当前限制判定。</text><view v-for="(x,i) in impact.segments||[]" :key="i"><text>{{arrangementStates[x.state]||x.state}} · {{formatTime(x.startsAt||x.starts_at)}}—{{formatTime(x.endsAt||x.ends_at)}} · 目标{{x.spaceId||'暂不可用'}}</text></view><label v-if="impact.requiresAcknowledgement" class="checkbox-label"><checkbox :checked="agreedImpact" @click="agreedImpact=!agreedImpact"/>我已阅读当前安排</label></view><view class="actions"><button role="button" class="primary" :disabled="busy" @click="acceptOffer(o)">确认接受</button><button role="button" :disabled="busy" @click="write('/long-offers/'+o.id+'/actions',{version:o.version,action:'DECLINE'})">拒绝本要约</button></view></template></view>
  <view class="actions"><button role="button" class="text-button" @click="go('map')">普通空间与其他选择</button><button role="button" v-if="data.waitlist?.effectiveStatus==='ACTIVE'" :disabled="busy" @click="write('/preparation-batches/'+id+'/waitlist-exit',{version:data.current_version,action:'EXIT_WAITLIST'})">只退出候补</button></view>
  <template v-if="['RESULT_PUBLISHED','FAILED_NO_RESULT','CANCELED','CLOSED'].includes(batch.status)&&data.status!=='WITHDRAWN'"><label class="checkbox-label"><checkbox :checked="exitConfirmation" @click="exitConfirmation=!exitConfirmation"/>确认退出本轮：使用权、要约和候补一并退出</label><button role="button" :disabled="busy||!exitConfirmation" @click="write('/preparation-batches/'+id+'/exit',{version:data.current_version,action:'EXIT'})">明确退出本轮</button></template>
 </view>
 <view v-if="batch.effectivePhase==='APPLICATION_OPEN'" class="panel"><text class="section-title">表达可接受的志愿</text><text class="caption">点空间名称先看档案；为每个真正可接受的位置选1、2或3级志愿。不选的位置不会被强制分配。等级须从1连续填写。</text><view v-for="s in batch.pool" :key="s.space_id" class="preference-row"><button role="button" class="text-button" @click="go('space',s.space_id)">{{s.code}} · {{s.name}}</button><view class="rank-buttons"><button role="button" v-for="n in [1,2,3]" :key="n" :class="{active:preferences[s.space_id]===n}" @click="rank(s.space_id,n)">{{n}}</button></view></view><label class="checkbox-label"><checkbox :checked="keepWaitlist" @click="keepWaitlist=!keepWaitlist;dirty=true"/>保留较高志愿候补；次优接受后可继续等待升级</label><text class="caption">已选{{selectedCount}}个位置；2/3级即本人预授权的兜底偏好。</text><button role="button" class="primary" :disabled="busy||!selectedCount" @click="submitPreferences">{{data.applied?'提交新的志愿版本':'提交本轮申请'}}</button><button role="button" v-if="data.applied&&data.status==='SUBMITTED'" :disabled="busy" @click="write('/preparation-batches/'+id+'/withdraw',{version:data.current_version,action:'WITHDRAW'})">申请期撤回</button></view>
</template>
<template v-else-if="view==='event'&&data.id"><view class="panel"><text class="section-title">{{data.title}}</text><text class="status-tag">{{label(data.phase)}}</text><text class="muted">{{data.speaker}} · {{formatTime(data.startsAt)}}—{{formatTime(data.endsAt)}}</text><text class="description">{{data.description}}</text><text class="info-note">{{data.notice||'请遵守空间使用规则。'}}</text><button role="button" class="text-button" @click="go('space',data.spaceId)">查看场地档案与位置</button><text class="muted">当前剩余{{data.remaining}}/{{data.capacity}}名额；满额进入按预约顺序候补。</text><text v-if="data.myParticipation?.status" class="info-note">我的状态：{{label(data.myParticipation.status)}} · 顺序{{data.myParticipation.sequence_number}}</text><button role="button" v-if="data.phase==='REGISTRATION_OPEN'&&!['CONFIRMED','WAITLISTED'].includes(data.myParticipation?.status)" class="primary" :disabled="busy" @click="write('/events/'+id+'/participation',{action:'JOIN'})">{{data.remaining?'预约参加':'参加候补'}}</button><button role="button" v-if="['CONFIRMED','WAITLISTED'].includes(data.myParticipation?.status)" :disabled="busy" @click="write('/events/'+id+'/participation',{action:'CANCEL'})">取消本次活动预约</button></view></template>
<template v-else-if="view==='messages'"><text class="section-title">站内消息 · {{total}}条未读</text><text class="caption">结果页面是权威入口；投递不等于已读。</text><view v-for="n in items" :key="n.id" class="panel"><text class="card-title">{{n.title}}<text class="status-tag">{{n.read_at?'已读':'未读'}}</text></text><text class="description">{{n.message}}</text><text class="caption">{{formatTime(n.created_at)}}</text><view class="actions"><button role="button" class="text-button" @click="inboxView(n)">查看相关安排</button><button role="button" v-if="!n.read_at" :disabled="busy" @click="write('/inbox/'+n.id+'/read',{})">标为已读</button></view></view><text v-if="!loading&&!error&&!items.length" class="empty">暂时没有站内消息。</text></template>
<template v-else-if="view==='feedback'"><view class="panel"><text class="section-title">反馈空间事实</text><text class="caption">反馈仅本人及有权管理员可见；核实后才改变公开空间画像。</text><view v-if="feedbackSpace" class="info-note">{{feedbackSpace.code}} · {{feedbackSpace.name}}<button role="button" class="text-button" @click="go('space',feedbackSpace.id)">查看空间档案</button></view><view v-else class="info-note">先了解空间，再反馈可核实的问题。<button role="button" @click="go('map')">从地图选择空间</button></view><picker :range="categories.map(c=>c.label)" @change="(e:Row)=>category=categories[Number(e.detail.value)].value"><view class="picker-label">{{categories.find(c=>c.value===category)?.label}}</view></picker><label class="field-label">发生了什么<textarea v-model="description" maxlength="2000" placeholder="描述可以核实的问题；不要填写他人隐私" :adjust-position="true" :cursor-spacing="32"/></label><button role="button" class="primary" :disabled="busy||!feedbackSpace" @click="write('/feedback',{spaceId:Number(spaceId),category,description},true)">保存私有反馈</button></view><text class="section-title">我的反馈</text><button role="button" v-for="r in items" :key="r.id" class="list-row" @click="go('report',r.id)"><view><text class="card-title">空间{{r.space_id}} · {{label(r.status)}}</text><text class="muted">{{categories.find(c=>c.value===r.category)?.label}} · {{formatTime(r.updated_at)}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!items.length" class="empty">没有已保存的反馈。</text></template>
<template v-else-if="view==='report'&&data.id"><view class="panel"><text class="section-title">反馈{{data.id}} · {{label(data.status)}}</text><text class="description">{{data.description}}</text><view v-if="attachments.length" class="evidence-photos"><image v-for="a in attachments" :key="a.id" :src="a.path" mode="aspectFit"/><text class="caption">受权限保护的照片，离开页面会清除本地展示。</text></view><text class="caption">最多3张JPEG/PNG照片，每张不超过1MiB。</text><button role="button" :disabled="busy||(data.attachments||[]).length>=3" @click="uploadPhoto">添加事实照片</button><text class="muted">{{data.decision_note||'等待核实与处理说明。'}}</text><view v-for="h in data.history" :key="h.id" class="history-row"><text class="card-title">{{label(h.action)}} · {{formatTime(h.created_at)}}</text><text>{{h.message}}</text></view><label class="field-label">补充事实<textarea v-model="statement" maxlength="2000" placeholder="补充现状或说明仍未解决的问题" :adjust-position="true" :cursor-spacing="32"/></label><view class="actions"><button role="button" :disabled="busy" @click="write('/feedback/'+id+'/supplements',{version:data.version,action:'SUPPLEMENT',message:statement},true)">补充</button><button role="button" v-if="['RESOLVED','NOT_REPRODUCED','REJECTED'].includes(data.status)" :disabled="busy" @click="write('/feedback/'+id+'/supplements',{version:data.version,action:'REOPEN',message:statement},true)">重新核实</button></view></view></template>
<template v-else-if="view==='governance'"><template v-if="!id"><view class="info-note">长期席位处置有明确依据、陈述期限与独立申诉复核，不以勤奋值收回席位。</view><button role="button" v-for="r in items" :key="r.id" class="list-row" @click="go('governance',r.id)"><view><text class="card-title">处置{{r.id}} · {{label(r.status)}}</text><text class="muted">空间{{r.space_id}} · 陈述截至{{formatTime(r.statement_until)}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!items.length" class="empty">没有与你有关的处置。</text></template><view v-else-if="data.id" class="panel"><text class="section-title">处置{{data.id}} · {{label(data.status)}}</text><text class="description">依据：{{data.evidence}}</text><text class="muted">{{data.decision_reason||'尚未作出裁决。'}}</text><text class="caption">陈述截至{{formatTime(data.statement_until)}}；申诉截至{{formatTime(data.appeal_until)}}</text><view v-for="(h,i) in data.history" :key="i" class="history-row"><text class="card-title">{{label(h.action)}} · {{formatTime(h.created_at)}}</text><text>{{h.message}}</text></view><label v-if="['NOTICE','REVOKED'].includes(data.status)" class="field-label">{{data.status==='NOTICE'?'我的陈述':'我的申诉'}}<textarea v-model="statement" maxlength="3000" :adjust-position="true" :cursor-spacing="32"/></label><button role="button" v-if="data.status==='NOTICE'" class="primary" :disabled="busy" @click="write('/governance-cases/'+id+'/statements',{version:data.version,message:statement},true)">提交陈述</button><button role="button" v-if="data.status==='REVOKED'" class="primary" :disabled="busy" @click="write('/governance-cases/'+id+'/appeals',{version:data.version,message:statement},true)">提交申诉（7天窗口）</button></view></template>
<view v-if="(view==='feedback'||(view==='governance'&&!id))" class="pagination"><button role="button" :disabled="page<=1||loading" @click="page--;load()">上一页</button><text>{{page}} / {{Math.max(1,Math.ceil(total/50))}}</text><button role="button" :disabled="page*50>=total||loading" @click="page++;load()">下一页</button></view>
</template>
