<script setup lang="ts">
import {computed,ref,watch,onMounted,nextTick} from 'vue';
import {ApiError,StaleResponse,featureText,factLabel,label,formatTime,localDateTime,businessTime,imageKey,query,type Space,type Floor,type Row,type Page} from '@qixu/client';
import {api,asset,auth,back,client,errorMessage,go,icon,initialize,kindLabel,modeLabel} from '../runtime';
import RequestState from './RequestState.vue';
import SpaceMap from './SpaceMap.vue';
import SpaceCard from './SpaceCard.vue';
import PersonalFlows from './PersonalFlows.vue';
const props=defineProps<{view:string;resourceId:number}>();
const view=computed(()=>props.view),id=computed(()=>props.resourceId),loading=ref(false),error=ref(''),success=ref(''),busy=ref(false);
const floors=ref<Floor[]>([]),spaces=ref<Space[]>([]),batches=ref<Row[]>([]),events=ref<Row[]>([]),favorites=ref<Space[]>([]),selected=ref<Space|null>(null),available=ref<Row|null>(null),rules=ref<Row>({}),facts=ref<Row[]>([]);
const floor=ref(100),search=ref(''),tag=ref(''),kind=ref(''),mapMode=ref(true),startsAt=ref(''),endsAt=ref(''),people=ref('1'),purpose=ref(''),description=ref(''),contact=ref('');
let revision=0;let visible=true;
const titles:Record<string,string>={home:'期序',map:'空间地图',space:'空间详情',favorites:'收藏与对比',batches:'备考席位',batch:'批次与我的申请',events:'近期活动',event:'活动详情',mine:'我的使用安排',messages:'消息',profile:'我的',feedback:'空间反馈',report:'反馈详情',governance:'使用权处置'};
const showParentBack=ref(false);
const personal=ref<{refresh:()=>void;leave:()=>void}|null>(null);
const title=computed(()=>titles[view.value]||'期序');
const currentFloor=computed(()=>floors.value.find(f=>Number(f.id)===floor.value));
const featured=computed(()=>spaces.value.filter(s=>s.kind==='SEAT').slice(0,3));
const activeBatch=computed(()=>batches.value.find(b=>['APPLICATION_OPEN','NOT_OPEN','FROZEN','RESULT_PUBLISHED'].includes(b.effectivePhase))||batches.value[0]);
const tabs=[{view:'home',name:'首页',icon:'house'},{view:'map',name:'找空间',icon:'armchair'},{view:'mine',name:'我的安排',icon:'clipboard-text'},{view:'messages',name:'消息',icon:'chat-circle'},{view:'profile',name:'我的',icon:'user'}];
function remember(){uni.setStorageSync('qixu.mapContext',JSON.stringify({floor:floor.value,search:search.value,tag:tag.value,kind:kind.value,mapMode:mapMode.value}));}
async function allSpaces(run:number){const collected:Space[]=[];for(let p=1;p<=40;p++){if(run!==revision)return;const page=await api<Page<Space>>('/spaces?'+query({floor:floor.value,page:p,search:search.value,tag:tag.value,kind:kind.value}),'spaces');if(run!==revision)return;collected.push(...page.items);if(collected.length>=page.total){spaces.value=collected;return;}}throw new ApiError(503,'MAP_TOO_LARGE','当前楼层记录较多，请缩小筛选范围。');}
async function load(){const run=++revision;loading.value=true;error.value='';try{await initialize();if(run!==revision)return;if(!auth.session)return;
  if(['home','map','space'].includes(view.value)){floors.value=await api<Floor[]>('/floors','floors');rules.value=await api('/booking-rules');if(run!==revision)return;}
  if(['home','map'].includes(view.value))await allSpaces(run);
  if(['home','batches'].includes(view.value))batches.value=await api<Row[]>('/preparation-batches');
  if(['home','events'].includes(view.value))events.value=await api<Row[]>('/events');
  if(['favorites','space'].includes(view.value))favorites.value=await api<Space[]>('/favorites');
  if(view.value==='space'){const s=await api<Space>('/spaces/'+id.value);if(run!==revision)return;selected.value=s;const result=await api<Row>('/spaces/'+id.value+'/facts');facts.value=Array.isArray(result)?result:result.items||[];}
}catch(e){if(run===revision&&!(e instanceof StaleResponse))error.value=errorMessage(e);}finally{if(run===revision)loading.value=false;}}
async function changeFilter(){remember();if(view.value==='map')uni.setStorageSync('qixu.mapScroll',0);await load();}
async function write(path:string,body:unknown,sensitive=false){if(busy.value)return;const run=revision;busy.value=true;error.value='';success.value='';try{const r=await client.mutate<Row>('/api/v1'+path,body,{sensitive});if(run!==revision)return;available.value=null;success.value='原提交已确认，回执 '+r.receipt.key.slice(-8)+'。';await load();if(run+1===revision&&!error.value)success.value+='当前详情已刷新。';}catch(e){if(run===revision)error.value=errorMessage(e);}finally{busy.value=false;}}
async function checkAvailability(){available.value=null;error.value='';const run=revision,start=startsAt.value,end=endsAt.value,space=id.value;try{const result=await api('/spaces/'+space+'/availability?'+query({start:businessTime(start),end:businessTime(end)}),'selected-availability');if(run===revision&&start===startsAt.value&&end===endsAt.value&&space===id.value)available.value=result;}catch(e){if(run===revision&&start===startsAt.value&&end===endsAt.value)error.value=errorMessage(e);}}
function datePart(value:string){return value.split('T')[0]||'';}function timePart(value:string){return value.split('T')[1]||'08:00';}
function pickTime(field:'starts'|'ends',part:'date'|'time',event:Row){const r=field==='starts'?startsAt:endsAt;const old=r.value||localDateTime(rules.value.serverNow);r.value=part==='date'?event.detail.value+'T'+timePart(old):datePart(old)+'T'+event.detail.value;available.value=null;}
function initTimes(){const now=new Date(String(rules.value.serverNow||new Date().toISOString()));now.setUTCSeconds(0,0);now.setUTCMinutes(now.getUTCMinutes()+15);let start=localDateTime(now.toISOString());if(timePart(start)<'08:00')start=datePart(start)+'T08:00';startsAt.value=start;endsAt.value=localDateTime(new Date(new Date(businessTime(start)).getTime()+3600000).toISOString());}
function stepFloor(delta:number){const i=floors.value.findIndex(f=>Number(f.id)===floor.value);const next=floors.value[i+delta];if(next){floor.value=Number(next.id);changeFilter();}}
async function submitShort(){try{await write('/reservations',{spaceId:id.value,startsAt:businessTime(startsAt.value),endsAt:businessTime(endsAt.value)});}catch(e){error.value=errorMessage(e);}}
async function submitVenue(){try{await write('/venue-requests',{spaceId:id.value,startsAt:businessTime(startsAt.value),endsAt:businessTime(endsAt.value),people:Number(people.value),purpose:purpose.value,description:description.value,contact:contact.value},true);}catch(e){error.value=errorMessage(e);}}
function chooseFloor(e:Row){floor.value=Number(floors.value[Number(e.detail.value)].id);changeFilter();}
function trackScroll(value:number){if(visible&&view.value==='map')uni.setStorageSync('qixu.mapScroll',Math.max(0,value));}
function leave(){visible=false;revision++;description.value='';contact.value='';personal.value?.leave();client.clearSensitive();}
async function refresh(){visible=true;showParentBack.value=getCurrentPages().length<=1;const scroll=Number(uni.getStorageSync('qixu.mapScroll')||0);await load();personal.value?.refresh();if(view.value==='map'&&visible&&scroll>0)await nextTick(()=>uni.pageScrollTo({scrollTop:scroll,duration:0}));}
defineExpose({refresh,leave,trackScroll});
onMounted(()=>{if(['map','home'].includes(view.value)){try{const context=JSON.parse(String(uni.getStorageSync('qixu.mapContext')||'{}'));floor.value=Number(context.floor)||100;if(view.value==='map'){search.value=String(context.search||'');tag.value=String(context.tag||'');kind.value=String(context.kind||'');mapMode.value=context.mapMode!==false;}}catch{}}uni.setNavigationBarTitle({title:title.value});load();});
watch(()=>auth.generation,()=>{revision++;spaces.value=[];batches.value=[];events.value=[];favorites.value=[];selected.value=null;facts.value=[];available.value=null;description.value='';contact.value='';});
watch(()=>rules.value.serverNow,()=>{if(!startsAt.value)initTimes();});
</script>
<template>
<view class="screen">
  <view v-if="view!=='home'&&showParentBack" class="page-heading"><button role="button" class="back-button" @click="back()"><image :src="icon('caret-left')"/>返回首页</button></view>
  <RequestState/>
  <view v-if="error" class="error-note" role="alert">{{error}}<button role="button" class="text-button" @click="load">刷新当前事实</button></view>
  <view v-if="success" class="info-note">{{success}}</view>
  <view v-if="auth.loading||loading" class="loading">正在读取当前事实…</view>
  <view v-if="!auth.loading&&!auth.session&&view!=='profile'" class="login-gate"><image :src="asset('qixu-brand.png')" mode="aspectFit"/><text class="section-title">先认识你，再安排空间</text><text class="muted">登录后查看申请、使用安排与通知。</text><button role="button" class="primary" @click="go('profile')">去登录</button></view>
  <template v-else-if="auth.session||view==='profile'">
  <template v-if="view==='home'">
    <view class="hero"><image class="hero-campus" :src="asset('campus-hero.jpg')" mode="aspectFill"/><view class="hero-copy"><image class="brand" :src="asset('qixu-brand.png')" mode="aspectFit"/><text class="hero-tagline">有所期，亦有序。</text><text class="hero-greeting">{{auth.session?.actor.displayName}}，找一处合适的空间。</text></view></view>
    <view class="home-batch panel"><view><text class="card-title">{{activeBatch?activeBatch.title:'从一处空间开始'}}</text><text class="muted">{{activeBatch?label(activeBatch.effectivePhase):'随用随约，长期席位按公开批次分配。'}}</text><text v-if="activeBatch" class="caption">申请截至 {{formatTime(activeBatch.closes_at)}}</text></view><button role="button" class="primary compact" @click="go(activeBatch?'batch':'map',activeBatch?.id)">{{activeBatch?'查看本轮':'找空间'}}<image :src="icon('arrow-right','red')"/></button></view>
    <view class="shortcuts"><button role="button" v-for="s in [{view:'map',icon:'map-trifold',name:'空间地图'},{view:'batches',icon:'book-open',name:'备考专区'},{view:'mine',icon:'clipboard-text',name:'我的申请'},{view:'feedback',icon:'chat-circle',name:'空间反馈'}]" :key="s.view" @click="go(s.view)"><view class="shortcut-icon"><image :src="icon(s.icon,s.view==='map'?'green':'red')"/></view><text>{{s.name}}</text></button></view>
    <view class="warm-note"><image :src="icon('sun','red')"/><text>先了解位置，再表达心愿。<text class="muted">分配不评价谁更努力。</text></text></view>
    <view class="section-heading"><text class="section-title">空间地图</text><button role="button" class="text-button" @click="go('map')">查看楼层<image :src="icon('arrow-right')"/></button></view>
    <text class="muted">{{currentFloor?.building}} · {{currentFloor?.name}}</text><SpaceMap :spaces="spaces" @select="s=>go('space',s.id)"/>
    <view class="section-heading"><text class="section-title">了解这些位置</text><button role="button" class="text-button" @click="go('favorites')">收藏与对比</button></view><view class="featured"><SpaceCard v-for="s in featured" :key="s.id" :space="s"/></view><text v-if="!loading&&!error&&!featured.length" class="empty">该楼层暂无座位档案，可以查看其他楼层与场地。</text>
    <view class="section-heading"><text class="section-title">近期活动</text><button role="button" class="text-button" @click="go('events')">查看全部</button></view><button role="button" v-for="e in events.slice(0,2)" :key="e.id" class="list-row" @click="go('event',e.id)"><image :src="icon('calendar-blank','red')"/><view><text class="card-title">{{e.title}}</text><text class="muted">{{label(e.phase||e.status)}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!events.length" class="empty">暂无已发布活动。开放后会在这里展示。</text>
  </template>
  <template v-else-if="view==='map'">
    <view class="filter-panel panel"><picker :value="Math.max(0,floors.findIndex(f=>Number(f.id)===floor))" :range="floors.map(f=>f.building+' · '+f.name)" @change="chooseFloor"><view class="picker-label">{{currentFloor?.building}} · {{currentFloor?.name}}<image :src="icon('map-trifold','green')"/></view></picker><view class="floor-actions"><button role="button" :disabled="floors.findIndex(f=>Number(f.id)===floor)<=0" @click="stepFloor(-1)">上一层</button><button role="button" :disabled="floors.findIndex(f=>Number(f.id)===floor)>=floors.length-1" @click="stepFloor(1)">下一层</button></view><view class="search-field"><image :src="icon('magnifying-glass')"/><input v-model="search" placeholder="搜索编号或空间名称" maxlength="80" confirm-type="search" @confirm="changeFilter"/><button role="button" class="text-button" @click="changeFilter">查找</button></view><view class="chips"><button role="button" v-for="f in [{value:'',name:'全部条件'},{value:'window',name:'靠窗'},{value:'outlet',name:'有插座'},{value:'quiet',name:'安静'},{value:'accessible',name:'无障碍'}]" :key="f.value" :class="{active:tag===f.value}" @click="tag=f.value;changeFilter()">{{f.name}}</button></view><view class="chips"><button role="button" v-for="k in [{value:'',name:'全部空间'},{value:'SEAT',name:'座位'},{value:'ROOM',name:'研讨室'},{value:'HALL',name:'报告厅'}]" :key="k.value" :class="{active:kind===k.value}" @click="kind=k.value;changeFilter()">{{k.name}}</button><button role="button" @click="mapMode=!mapMode;remember()">{{mapMode?'切换列表':'切换地图'}}</button></view></view>
    <SpaceMap v-if="mapMode" :spaces="spaces" @select="s=>go('space',s.id)"/><text v-if="!loading&&!error" class="caption">{{spaces.filter(s=>s.kind!=='AREA').length}}个可选择空间符合当前公开条件。可用时段需在详情查询。</text>
    <button role="button" v-for="s in spaces.filter(s=>s.kind!=='AREA')" :key="s.id" class="list-row" @click="go('space',s.id)"><image class="row-photo" :src="asset(imageKey(s.imageKey)+'.jpg')" mode="aspectFill"/><view><text class="card-title">{{s.code}} · {{s.name}}</text><text class="muted">{{kindLabel[s.kind]}} · {{modeLabel[s.useMode]}}</text><view class="tags"><text v-for="f in featureText(s).filter(f=>f.value==='有')" :key="f.key">{{f.label}}</text></view></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!spaces.some(s=>s.kind!=='AREA')" class="empty">没有符合条件的空间，试试其他楼层或取消筛选。</text>
  </template>
  <template v-else-if="view==='space'&&selected">
    <image class="detail-photo" :src="asset(imageKey(selected.imageKey)+'.jpg')" mode="aspectFill"/><text class="caption">演示示意图片 · 非真实馆内照片</text><view class="panel"><view class="section-heading"><text class="section-title">{{selected.code}} · {{selected.name}}</text><button role="button" class="icon-button" :aria-label="favorites.some(f=>f.id===id)?'取消收藏':'收藏空间'" @click="write('/favorites',{spaceId:id,selected:!favorites.some(f=>f.id===id)})"><image :src="icon('heart',favorites.some(f=>f.id===id)?'red':'ink')"/></button></view><text class="muted">{{kindLabel[selected.kind]}} · {{modeLabel[selected.useMode]}} · 容量{{selected.capacity}}人</text><text class="description">{{selected.profile.description||'公开简介尚未填写。'}}</text><view class="feature-grid"><view v-for="(f,i) in featureText(selected)" :key="f.key"><image :src="icon(['sun','plug','wind','wheelchair'][i],f.value==='有'?'green':'ink')"/><view><text class="card-title">{{f.label}}</text><text class="muted">{{f.value}}</text></view></view></view><text v-if="selected.profile.notice" class="info-note">{{selected.profile.notice}}</text><view v-for="(value,key) in selected.profile.conditions||{}" :key="key" class="fact-row"><text>{{factLabel[String(key)]||'其他已采集条件'}}</text><text>{{label(value)}}</text></view><text class="caption">设施未采集时显示未知。原始反馈核实后才进入公开事实。</text></view>
    <view class="panel"><text class="section-title">查看使用时段</text><text class="caption">服务器时间 {{formatTime(rules.serverNow)}}；开放08:00–22:00。短约限当天未来4小时。</text><view class="time-row" v-for="field in ['starts','ends']" :key="field"><text>{{field==='starts'?'开始':'结束'}}</text><picker mode="date" :value="datePart(field==='starts'?startsAt:endsAt)" @change="(e:Row)=>pickTime(field as 'starts'|'ends','date',e)"><view class="field-value">{{datePart(field==='starts'?startsAt:endsAt)||'选择日期'}}</view></picker><picker mode="time" :value="timePart(field==='starts'?startsAt:endsAt)" @change="(e:Row)=>pickTime(field as 'starts'|'ends','time',e)"><view class="field-value">{{timePart(field==='starts'?startsAt:endsAt)}}</view></picker></view><button role="button" @click="checkAvailability">查询时段可用性</button><view v-if="available" :class="available.available?'info-note':'error-note'">{{available.available?'当前查询可用，提交时仍须重新裁决。':'当前时段已有使用权或限制，请换时间/空间。'}}<text class="caption">查询时点 {{formatTime(available.asOf)}}；不代表现场是否有人。</text></view>
      <button role="button" v-if="selected.kind==='SEAT'&&selected.useMode==='BOOKABLE'" class="primary" :disabled="busy||!auth.session?.actor.studentVerified" @click="submitShort">申请这个时段</button>
      <view v-else-if="selected.useMode==='PREPARATION'" class="info-note">长期位通过统一批次分配，无需每日打卡保席。<button role="button" class="text-button" @click="go('batches')">查看可参加批次</button></view>
      <template v-else-if="selected.useMode==='VENUE'"><label class="field-label">预计人数<input v-model="people" type="number" placeholder="不超过场地容量"/></label><label class="field-label">用途<input v-model="purpose" maxlength="100" placeholder="如：读书交流"/></label><label class="field-label">申请说明<textarea v-model="description" maxlength="1000" placeholder="说明使用安排与设备需求" :adjust-position="true" :cursor-spacing="32"/></label><label class="field-label">联系方式<input v-model="contact" maxlength="100" placeholder="用于本次申请联系"/></label><button role="button" class="primary" :disabled="busy" @click="submitVenue">提交场地申请</button></template>
      <view v-else class="info-note">该区域为自由使用，未开放预约接口。</view>
    </view><button role="button" @click="go('feedback',id)">反馈这个空间的问题</button>
  </template>
  <template v-else-if="view==='favorites'"><view class="info-note">最多收藏6个空间。公开条件帮助选择，时段可用性仍需查询。</view><view v-for="s in favorites" :key="s.id" class="panel"><SpaceCard :space="s"/><view class="feature-grid"><view v-for="f in featureText(s)" :key="f.key"><text>{{f.label}}</text><text class="card-title">{{f.value}}</text></view></view><button role="button" class="text-button" @click="write('/favorites',{spaceId:s.id,selected:false})">移除收藏</button></view><text v-if="!loading&&!error&&!favorites.length" class="empty">还没有收藏，可以在空间详情点心形按钮。</text></template>
  <template v-else-if="view==='batches'"><view class="info-note">资格决定参与，公开抽签处理稀缺。首选未获分配也会有明确通知与下一步。</view><button role="button" v-for="b in batches" :key="b.id" class="list-row" @click="go('batch',b.id)"><image :src="icon('book-open','red')"/><view><text class="card-title">{{b.title}}</text><text class="muted">{{label(b.effectivePhase)}} · 申请截至{{formatTime(b.closes_at)}}</text><text class="caption">结果最迟{{formatTime(b.result_deadline)}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!batches.length" class="empty">目前没有长期批次。普通空间仍可按时段申请。</text></template>
  <template v-else-if="view==='events'"><button role="button" v-for="e in events" :key="e.id" class="list-row" @click="go('event',e.id)"><image :src="icon('calendar-blank','red')"/><view><text class="card-title">{{e.title}}</text><text class="muted">{{label(e.phase||e.status)}} · {{e.speaker||'主讲信息待补充'}}</text></view><image :src="icon('arrow-right')"/></button><text v-if="!loading&&!error&&!events.length" class="empty">目前没有公开活动。活动场地成立后才发布。</text></template>
  <PersonalFlows v-else ref="personal" :view="view" :resource-id="id"/>
  </template>
  <view class="bottom-nav"><button role="button" v-for="t in tabs" :key="t.view" :class="{active:view===t.view}" @click="go(t.view,undefined,true)"><image :src="icon(t.icon,view===t.view?'red':'ink')"/><text>{{t.name}}</text></button></view>
</view>
</template>
