package dev.noctilume.qixu;

import static org.junit.jupiter.api.Assertions.*;
import dev.noctilume.qixu.common.*;
import dev.noctilume.qixu.preparation.LongSeats;
import java.net.*;
import java.net.http.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.nio.file.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import org.springframework.transaction.support.TransactionTemplate;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("demo")
@Import(PreparationIT.FaultConfig.class)
class GovernanceCasesIT {
    @DynamicPropertySource static void db(DynamicPropertyRegistry r) {FoundationIT.database(r);}
    @LocalServerPort int port;
    @Autowired JdbcTemplate jdbc;@Autowired JsonMapper json;@Autowired PreparationIT.MutableClock clock;@Autowired LongSeats seats;
    @Autowired org.springframework.transaction.PlatformTransactionManager manager;
    @MockitoSpyBean Business business;
    private final HttpClient http=HttpClient.newHttpClient();private final List<Map<String,Object>> requests=new CopyOnWriteArrayList<>();private final Map<String,Object> facts=new LinkedHashMap<>();
    private static final Map<String,Object> RETAINED=new ConcurrentHashMap<>();private String name;
    record Reply(int status,JsonNode body) {JsonNode data() {return body.path("data");}long id() {return data().path("id").asLong();}}
    record Fixture(String admin,String owner,long batch,long offer,long right) {}
    @BeforeEach void reset(TestInfo info) {
        name=info.getTestMethod().orElseThrow().getName();clock.value=Instant.parse("2026-10-10T01:00:00Z");TestData.clearBusiness(jdbc);jdbc.update("DELETE FROM auth_session");jdbc.update("DELETE FROM login_attempt");jdbc.update("DELETE FROM audit_entry");jdbc.update("UPDATE identity_user SET active=TRUE,auth_version=1,student_verified=(role='STUDENT') WHERE id BETWEEN 1 AND 5");jdbc.update("INSERT IGNORE INTO admin_scope(user_id,floor_id) VALUES(4,100),(4,101),(5,100)");
    }
    @AfterEach void retain() {org.mockito.Mockito.reset(business);M4Measurements.collect(jdbc,facts);for(String table:List.of("governance_case","governance_history","long_application_penalty","seat_entitlement","long_offer","allocation_result"))facts.put(table,jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class));RETAINED.put(name,Map.of("requests",requests,"database",facts,"randomnessProvider","CONTROLLED_TEST_DOUBLE_NOT_PUBLIC_BLS"));}
    @AfterAll static void write() throws Exception {var p=Path.of("target/failsafe-reports/qixu-m4-governance-observation.json");Files.createDirectories(p.getParent());Files.writeString(p,JsonMapper.builder().build().writeValueAsString(RETAINED));}
    Reply api(String method,String path,Object body,String token,String key) throws Exception {
        var builder=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(25));if(token!=null)builder.header("Authorization","Bearer "+token);if(key!=null)builder.header("Idempotency-Key",key);if(body!=null)builder.header("Content-Type","application/json");builder.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));var response=http.send(builder.build(),HttpResponse.BodyHandlers.ofString());requests.add(Map.of("method",method,"path",path,"status",response.statusCode()));return new Reply(response.statusCode(),json.readTree(response.body()));
    }
    void ok(Reply r) {assertEquals(200,r.status(),r.body().toString());}void error(Reply r,int status,String code) {assertEquals(status,r.status(),r.body().toString());assertEquals(code,r.body().at("/error/code").asString());}
    String login(String user) throws Exception {var r=api("POST","/auth/login",Map.of("username",user,"password","qixu-demo","mode","BEARER"),null,null);ok(r);return r.data().path("token").asString();}
    String iso(Instant time) {return time.toString();}
    Map<String,Object> batchBody(List<Long> pool) {
        var now=clock.value;return new LinkedHashMap<>(Map.ofEntries(Map.entry("title","治理验收轮次"),Map.entry("purpose","POSTGRADUATE"),Map.entry("startsAt",iso(now.plusSeconds(4200))),Map.entry("endsAt",iso(now.plusSeconds(864000))),Map.entry("opensAt",iso(now.minusSeconds(1))),Map.entry("closesAt",iso(now.plusSeconds(300))),Map.entry("freezeDeadline",iso(now.plusSeconds(360))),Map.entry("randomAt",iso(now.plusSeconds(420))),Map.entry("resultDeadline",iso(now.plusSeconds(1200))),Map.entry("confirmationDeadline",iso(now.plusSeconds(3600))),Map.entry("promotionUntil",iso(now.plusSeconds(864000))),Map.entry("promotionSeconds",600),Map.entry("seatIds",pool)));
    }
    long open(String admin,List<Long> pool,String key) throws Exception {var r=api("POST","/preparation-batches",batchBody(pool),admin,key);ok(r);return r.id();}
    Map<String,Object> application(long seat) {return Map.of("version",0,"preferences",List.of(Map.of("seatId",seat,"rank",1)),"keepWaitlist",true);}
    void submit(String owner,long batch,long seat,String key) throws Exception {ok(api("POST","/preparation-batches/"+batch+"/application",application(seat),owner,key));}
    void draw(String admin,long batch) throws Exception {clock.value=Instant.parse("2026-10-10T01:05:00Z");ok(api("POST","/preparation-batches/"+batch+"/actions",Map.of("version",1,"action","FREEZE"),admin,"governance-freeze"));clock.value=Instant.parse("2026-10-10T01:07:03Z");ok(api("POST","/preparation-batches/"+batch+"/actions",Map.of("version",2,"action","ALLOCATE"),admin,"governance-allocate"));}
    Fixture fixture() throws Exception {
        var admin=login("admin1");var owner=login("student1");long batch=open(admin,List.of(2000L),"governance-batch");submit(owner,batch,2000,"governance-application");draw(admin,batch);long offer=jdbc.queryForObject("SELECT id FROM long_offer WHERE batch_id=? AND user_id=1",Long.class,batch);ok(api("POST","/long-offers/"+offer+"/actions",Map.of("version",1,"action","ACCEPT"),owner,"governance-accept"));return new Fixture(admin,owner,batch,offer,jdbc.queryForObject("SELECT id FROM seat_entitlement WHERE offer_id=?",Long.class,offer));
    }
    Map<String,Object> caseBody(Fixture f) {return new LinkedHashMap<>(Map.of("entitlementId",f.right(),"entitlementVersion",1,"reasonCode","EXPLICIT_RULE_VIOLATION","evidence","验收专用私有事实 PRIVATE_CASE_9922，不得公开","statementUntil",iso(clock.value.plusSeconds(86400))));}
    Reply create(Fixture f) throws Exception {var r=api("POST","/admin/governance-cases",caseBody(f),f.admin(),"governance-notice");ok(r);return r;}
    long version(long id) {return jdbc.queryForObject("SELECT version FROM governance_case WHERE id=?",Long.class,id);}
    void due(long id) {clock.value=Business.date(jdbc.queryForMap("SELECT statement_until FROM governance_case WHERE id=?",id),"statement_until").toInstant(ZoneOffset.UTC);}
    Reply decision(String admin,long id,String action,String penalty,String key) throws Exception {var body=new LinkedHashMap<String,Object>(Map.of("version",version(id),"action",action,"reason","有明确依据的裁决，非勤奋或签到指标"));if(penalty!=null)body.put("penaltyUntil",penalty);return api("POST","/admin/governance-cases/"+id+"/decisions",body,admin,key);}
    Reply appeal(String owner,long id) throws Exception {return api("POST","/governance-cases/"+id+"/appeals",Map.of("version",version(id),"message","请核实原记录，本案存在事实错误"),owner,"governance-appeal");}
    Reply review(String reviewer,long id,String key) throws Exception {return api("POST","/admin/governance-cases/"+id+"/reviews",Map.of("version",version(id),"action","OVERTURN","reason","独立复核确认原裁决错误"),reviewer,key);}
    long future(String admin,Instant close,String key) throws Exception {
        var body=batchBody(List.of(2003L));body.put("startsAt","2026-10-21T02:00:00Z");body.put("endsAt","2026-10-25T02:00:00Z");body.put("promotionUntil","2026-10-25T02:00:00Z");body.put("closesAt",iso(close));body.put("freezeDeadline",iso(close.plusSeconds(60)));body.put("randomAt",iso(close.plusSeconds(120)));body.put("resultDeadline",iso(close.plusSeconds(900)));body.put("confirmationDeadline",iso(close.plusSeconds(3600)));var r=api("POST","/preparation-batches",body,admin,key);ok(r);return r.id();
    }
    void freezeFuture(String admin,long batch) throws Exception {clock.value=Business.date(jdbc.queryForMap("SELECT closes_at FROM preparation_batch WHERE id=?",batch),"closes_at").toInstant(ZoneOffset.UTC);ok(api("POST","/preparation-batches/"+batch+"/actions",Map.of("version",1,"action","FREEZE"),admin,"freeze-future-round"));}
    Reply allocateFuture(String admin,long batch) throws Exception {clock.value=Business.date(jdbc.queryForMap("SELECT random_at FROM preparation_batch WHERE id=?",batch),"random_at").toInstant(ZoneOffset.UTC).plusSeconds(3);return api("POST","/preparation-batches/"+batch+"/actions",Map.of("version",2,"action","ALLOCATE"),admin,"allocate-future-round");}
    @Test void noticeIsPrivateAndCannotRevokeBeforeAtLeastTwentyFourHours() throws Exception {
        var f=fixture();var invalid=caseBody(f);invalid.put("statementUntil",iso(clock.value.plusSeconds(86399)));error(api("POST","/admin/governance-cases",invalid,f.admin(),"short-notice-period"),422,"INVALID_INPUT");invalid=caseBody(f);invalid.put("reasonCode","LOW_STUDY_HOURS");error(api("POST","/admin/governance-cases",invalid,f.admin(),"unfair-effort-reason"),422,"INVALID_INPUT");
        var record=create(f);error(api("GET","/governance-cases/"+record.id(),null,login("student2"),null),404,"RESOURCE_NOT_FOUND");error(api("POST","/admin/governance-cases",caseBody(f),f.owner(),"student-notice-control"),403,"SCOPE_FORBIDDEN");error(decision(f.admin(),record.id(),"REVOKE",null,"premature-revocation"),409,"STATEMENT_WINDOW_OPEN");
        assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM long_application_penalty",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM governance_case",Integer.class));assertFalse(api("GET","/spaces/2000",null,login("student2"),null).body().toString().contains("PRIVATE_CASE"));
    }
    @Test void statementVersionsAreRetainedAndExactDeadlineIsClosed() throws Exception {
        var f=fixture();var record=create(f);ok(api("POST","/governance-cases/"+record.id()+"/statements",Map.of("version",1,"message","本人第一份陈述"),f.owner(),"statement-first"));error(api("POST","/governance-cases/"+record.id()+"/statements",Map.of("version",1,"message","旧版本覆盖陈述"),f.owner(),"statement-stale"),409,"STALE_VERSION");
        due(record.id());var owner=login("student1");error(api("POST","/governance-cases/"+record.id()+"/statements",Map.of("version",2,"message","精确截止后的陈述"),owner,"statement-at-cutoff"),409,"STATEMENT_WINDOW_CLOSED");
        String output=jdbc.queryForObject("SELECT output_hash FROM allocation_result WHERE batch_id=?",String.class,f.batch());ok(decision(login("admin1"),record.id(),"REVOKE",null,"governance-revoke"));assertEquals(output,jdbc.queryForObject("SELECT output_hash FROM allocation_result WHERE batch_id=?",String.class,f.batch()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM governance_history WHERE action='STATEMENT'",Integer.class));assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));
    }
    @Test void aVoluntaryExitCannotBeMisrepresentedAsAnAdministrativeRevocation() throws Exception {
        var f=fixture();var record=create(f);ok(api("POST","/preparation-batches/"+f.batch()+"/exit",Map.of("version",1,"action","EXIT"),f.owner(),"exit-before-revocation"));due(record.id());var admin=login("admin1");error(decision(admin,record.id(),"REVOKE",null,"revoke-after-exit"),409,"STALE_VERSION");ok(decision(admin,record.id(),"DISMISS",null,"dismiss-after-exit"));assertEquals("RELINQUISHED",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));assertEquals("DISMISSED",jdbc.queryForObject("SELECT status FROM governance_case WHERE id=?",String.class,record.id()));
    }
    @Test void originalNoticeReceiptCanReplayAfterTheEntitlementVersionChanges() throws Exception {
        var f=fixture();var body=caseBody(f);var record=api("POST","/admin/governance-cases",body,f.admin(),"original-notice-key");ok(record);due(record.id());var admin=login("admin1");ok(decision(admin,record.id(),"REVOKE",null,"notice-then-revoke"));var replay=api("POST","/admin/governance-cases",body,admin,"original-notice-key");ok(replay);assertEquals(record.data(),replay.data());assertEquals("REVOKED",api("GET","/governance-cases/"+record.id(),null,admin,null).data().path("status").asString());
    }
    @Test void independentAppealCanRestoreAnActuallyFreeOriginalSeat() throws Exception {
        var f=fixture();var record=create(f);due(record.id());var admin=login("admin1");ok(decision(admin,record.id(),"REVOKE",iso(clock.value.plusSeconds(86400)),"penalized-revocation"));var owner=login("student1");ok(appeal(owner,record.id()));error(review(admin,record.id(),"self-review-denied"),409,"INDEPENDENT_REVIEW_REQUIRED");var restored=review(login("admin2"),record.id(),"independent-restoration");ok(restored);assertEquals("RESTORED",restored.data().path("status").asString());assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));assertEquals("OVERTURNED",jdbc.queryForObject("SELECT status FROM long_application_penalty WHERE case_id=?",String.class,record.id()));assertEquals("SUBMITTED",jdbc.queryForObject("SELECT status FROM preparation_application WHERE batch_id=? AND user_id=1",String.class,f.batch()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM seat_entitlement",Integer.class));
    }
    @Test void appealCannotStealASeatAlreadyAcceptedByTheStableWaitlist() throws Exception {
        var admin=login("admin1");var one=login("student1");var two=login("student2");long batch=open(admin,List.of(2000L),"two-person-batch");submit(one,batch,2000,"two-person-one");submit(two,batch,2000,"two-person-two");draw(admin,batch);
        var offered=jdbc.queryForMap("SELECT id,user_id FROM long_offer WHERE batch_id=?",batch);long user=Business.number(offered,"user_id"),offer=Business.number(offered,"id");var winner=user==1?one:two;ok(api("POST","/long-offers/"+offer+"/actions",Map.of("version",1,"action","ACCEPT"),winner,"first-winner-accept"));long right=jdbc.queryForObject("SELECT id FROM seat_entitlement WHERE offer_id=?",Long.class,offer);var record=create(new Fixture(admin,winner,batch,offer,right));String output=jdbc.queryForObject("SELECT output_hash FROM allocation_result WHERE batch_id=?",String.class,batch);
        due(record.id());admin=login("admin1");ok(decision(admin,record.id(),"REVOKE",null,"winner-revoked"));seats.maintain(batch);var promoted=jdbc.queryForMap("SELECT id,user_id FROM long_offer WHERE batch_id=? AND status='OPEN'",batch);assertNotEquals(user,Business.number(promoted,"user_id"));var next=login(user==1?"student2":"student1");ok(api("POST","/long-offers/"+promoted.get("id")+"/actions",Map.of("version",1,"action","ACCEPT"),next,"stable-waitlist-accept"));
        ok(appeal(login(user==1?"student1":"student2"),record.id()));var correction=review(login("admin2"),record.id(),"cannot-steal-restoration");ok(correction);assertEquals("CORRECTED_UNAVAILABLE",correction.data().path("status").asString());assertEquals("SPACE_CONFLICT",correction.data().path("restoration_reason").asString());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM seat_entitlement WHERE status='ACTIVE'",Integer.class));assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,right));assertEquals(output,jdbc.queryForObject("SELECT output_hash FROM allocation_result WHERE batch_id=?",String.class,batch));
    }
    @Test void activePenaltyRejectsNewApplicationButExpiresWithoutATaskAndKeepsOldReceipt() throws Exception {
        var f=fixture();var record=create(f);due(record.id());var admin=login("admin1");var end=clock.value.plusSeconds(3600);ok(decision(admin,record.id(),"REVOKE",iso(end),"one-hour-penalty"));var owner=login("student1");long next=open(admin,List.of(2001L),"penalty-next-batch");error(api("POST","/preparation-batches/"+next+"/application",application(2001),owner,"application-during-penalty"),409,"LONG_APPLICATION_PENALTY");ok(api("POST","/preparation-batches/"+f.batch()+"/application",application(2000),owner,"governance-application"));
        clock.value=end;long later=open(admin,List.of(2002L),"penalty-expired-batch");submit(owner,later,2002,"application-at-penalty-end");assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM long_application_penalty WHERE case_id=?",String.class,record.id()));assertFalse(api("GET","/governance-cases/"+record.id(),null,owner,null).data().path("penalty").get(0).path("effective").asBoolean());
    }
    @Test void decisionNotificationFaultRollsBackRevocationPenaltyAndReceipt() throws Exception {
        var f=fixture();var record=create(f);due(record.id());var admin=login("admin1");String until=iso(clock.value.plusSeconds(3600));
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).equals("governance:"+record.id()+":REVOKED"))throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_GOVERNANCE_NOTICE_FAILURE");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {error(decision(admin,record.id(),"REVOKE",until,"revoke-notice-fault"),503,"DATABASE_UNAVAILABLE");}finally {org.mockito.Mockito.reset(business);}
        assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));assertEquals("NOTICE",jdbc.queryForObject("SELECT status FROM governance_case WHERE id=?",String.class,record.id()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM long_application_penalty",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM idempotency_receipt WHERE request_key='revoke-notice-fault'",Integer.class));M4Measurements.governanceFault(jdbc,facts,record.id(),f.right(),"revoke-notice-fault");ok(decision(admin,record.id(),"REVOKE",until,"revoke-notice-fault"));
    }
    @Test void appealCorrectionNotificationFaultCannotPartiallyRestoreOrDropThePenalty() throws Exception {
        var f=fixture();var record=create(f);due(record.id());ok(decision(login("admin1"),record.id(),"REVOKE",iso(clock.value.plusSeconds(86400)),"review-fault-revoke"));ok(appeal(login("student1"),record.id()));var reviewer=login("admin2");
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).equals("governance:"+record.id()+":review"))throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_APPEAL_NOTICE_FAILURE");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {error(review(reviewer,record.id(),"review-notice-fault"),503,"DATABASE_UNAVAILABLE");}finally {org.mockito.Mockito.reset(business);}
        assertEquals("APPEALED",jdbc.queryForObject("SELECT status FROM governance_case WHERE id=?",String.class,record.id()));assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM long_application_penalty WHERE case_id=?",String.class,record.id()));M4Measurements.governanceFault(jdbc,facts,record.id(),f.right(),"review-notice-fault");ok(review(reviewer,record.id(),"review-notice-fault"));
    }
    @Test void appealAtTheExactSeventhDayCannotReopenTheOldDecision() throws Exception {
        var f=fixture();var record=create(f);due(record.id());ok(decision(login("admin1"),record.id(),"REVOKE",null,"appeal-expiry-revoke"));clock.value=Business.date(jdbc.queryForMap("SELECT appeal_until FROM governance_case WHERE id=?",record.id()),"appeal_until").toInstant(ZoneOffset.UTC);error(appeal(login("student1"),record.id()),409,"APPEAL_WINDOW_CLOSED");assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM governance_case WHERE id=?",String.class,record.id()));
    }
    @Test void administratorLosingScopeWhileWaitingCannotRevokeTheRight() throws Exception {
        var f=fixture();var record=create(f);due(record.id());var admin=login("admin1");var gate=new CountDownLatch(1);var executor=Executors.newSingleThreadExecutor();final Future<Reply>[] pending=new Future[1];
        org.mockito.Mockito.doAnswer(inv->{gate.countDown();return inv.callRealMethod();}).when(business).floors(org.mockito.ArgumentMatchers.anyCollection());
        try {new TransactionTemplate(manager).execute(status->{jdbc.queryForList("SELECT id FROM floor WHERE id=100 FOR UPDATE");pending[0]=executor.submit(()->decision(admin,record.id(),"REVOKE",null,"scope-revoked-during-wait"));try {assertTrue(gate.await(5,TimeUnit.SECONDS));}catch(InterruptedException e){throw new RuntimeException(e);}jdbc.update("DELETE FROM admin_scope WHERE user_id=4 AND floor_id=100");return null;});error(pending[0].get(20,TimeUnit.SECONDS),403,"SCOPE_FORBIDDEN");assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));}
        finally {executor.shutdownNow();jdbc.update("INSERT IGNORE INTO admin_scope(user_id,floor_id) VALUES(4,100)");org.mockito.Mockito.reset(business);}
    }
    @Test void concurrentDecisionsCannotOverwriteEachOtherWithTheSameVersion() throws Exception {
        var f=fixture();var record=create(f);due(record.id());var one=login("admin1");var two=login("admin2");var executor=Executors.newFixedThreadPool(2);var go=new CountDownLatch(1);var body1=Map.of("version",1,"action","REVOKE","reason","第一份合法裁决");var body2=Map.of("version",1,"action","DISMISS","reason","另一位管理员的不同判断");
        try {var a=executor.submit(()->{go.await();return api("POST","/admin/governance-cases/"+record.id()+"/decisions",body1,one,"decision-race-a");});var c=executor.submit(()->{go.await();return api("POST","/admin/governance-cases/"+record.id()+"/decisions",body2,two,"decision-race-b");});go.countDown();assertEquals(List.of(200,409),List.of(a.get(20,TimeUnit.SECONDS).status(),c.get(20,TimeUnit.SECONDS).status()).stream().sorted().toList());assertEquals(2,version(record.id()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM governance_history WHERE action IN ('REVOKED','DISMISSED')",Integer.class));}
        finally {executor.shutdownNow();}
    }
    @Test void aCurrentMaintenanceLimitMakesCorrectionExplicitlyUnavailable() throws Exception {
        var f=fixture();var record=create(f);due(record.id());var admin=login("admin1");ok(decision(admin,record.id(),"REVOKE",null,"maintained-right-revoke"));var start=clock.value.plusSeconds(600);var body=new LinkedHashMap<String,Object>(Map.of("spaceId",2000,"kind","MAINTENANCE","startsAt",iso(start),"endsAt",iso(start.plusSeconds(3600)),"reason","纠错期间实际维护","resolutions",List.of()));var preview=api("POST","/admin/space-blocks/preview",body,admin,null);ok(preview);body.put("impactHash",preview.data().path("impactHash").asString());ok(api("POST","/admin/space-blocks",body,admin,"maintenance-after-revoke"));ok(appeal(login("student1"),record.id()));var r=review(login("admin2"),record.id(),"maintenance-correction");ok(r);assertEquals("CORRECTED_UNAVAILABLE",r.data().path("status").asString());assertEquals("SPACE_CONFLICT",r.data().path("restoration_reason").asString());assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block",String.class));
    }
    @Test void unpublishedCancellationReleasesOnlyCurrentPoolProtectionAndKeepsApplicationHistory() throws Exception {
        var admin=login("admin1");var owner=login("student1");long batch=open(admin,List.of(2000L),"cancel-open-batch");submit(owner,batch,2000,"cancel-open-application");var body=Map.of("version",1,"action","CANCEL","reason","明确取消未发布轮次");var r=api("POST","/preparation-batches/"+batch+"/cancel",body,admin,"cancel-open-round");ok(r);assertEquals(r.data(),api("POST","/preparation-batches/"+batch+"/cancel",body,admin,"cancel-open-round").data());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM application_version WHERE application_id IN (SELECT id FROM preparation_application WHERE batch_id=?)",Integer.class,batch));long next=open(admin,List.of(2000L),"reuse-canceled-pool");assertNotEquals(batch,next);assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM notification_outbox WHERE event_key=?",Integer.class,"batch:"+batch+":canceled"));
    }
    @Test void unusedPublishedCancellationRejectsLiveOfferThenRetainsFormalResultWhenExpired() throws Exception {
        var admin=login("admin1");var owner=login("student1");long batch=open(admin,List.of(2000L),"cancel-unused-batch");submit(owner,batch,2000,"cancel-unused-application");draw(admin,batch);var body=Map.of("version",3,"action","CANCEL_UNUSED","reason","没有授予过使用权的废弃轮次");error(api("POST","/preparation-batches/"+batch+"/cancel",body,admin,"cancel-live-offer"),409,"BATCH_HAS_GRANTED_RIGHTS");String output=jdbc.queryForObject("SELECT output_hash FROM allocation_result WHERE batch_id=?",String.class,batch);clock.value=Instant.parse("2026-10-10T02:00:00Z");ok(api("POST","/preparation-batches/"+batch+"/cancel",body,admin,"cancel-expired-round"));assertEquals(output,jdbc.queryForObject("SELECT output_hash FROM allocation_result WHERE batch_id=?",String.class,batch));assertEquals("CANCELED",jdbc.queryForObject("SELECT status FROM long_offer WHERE batch_id=?",String.class,batch));
    }
    @Test void aRoundWithConfirmedHistoryCannotUseTheUnusedCancellationShortcut() throws Exception {
        var f=fixture();ok(api("POST","/preparation-batches/"+f.batch()+"/exit",Map.of("version",1,"action","EXIT"),f.owner(),"exit-before-unused-cancel"));error(api("POST","/preparation-batches/"+f.batch()+"/cancel",Map.of("version",3,"action","CANCEL_UNUSED","reason","不能借废弃入口洗掉确认历史"),f.admin(),"cancel-confirmed-history"),409,"BATCH_HAS_GRANTED_RIGHTS");assertEquals("RESULT_PUBLISHED",jdbc.queryForObject("SELECT status FROM preparation_batch WHERE id=?",String.class,f.batch()));assertEquals("RELINQUISHED",jdbc.queryForObject("SELECT status FROM seat_entitlement WHERE id=?",String.class,f.right()));
    }
    @Test void penaltyIntroducedAfterSubmissionExcludesTheCandidateAtFreezeWithoutChangingTheSubmittedVersion() throws Exception {
        var f=fixture();var record=create(f);var deadline=clock.value.plusSeconds(86400);long next=future(f.admin(),deadline.plusSeconds(3),"eligibility-freeze-batch");submit(f.owner(),next,2003,"eligibility-before-freeze");due(record.id());var admin=login("admin1");ok(decision(admin,record.id(),"REVOKE",iso(clock.value.plusSeconds(86400)),"eligibility-freeze-revoke"));freezeFuture(admin,next);
        assertEquals("EXCLUDED",jdbc.queryForObject("SELECT status FROM preparation_application WHERE batch_id=? AND user_id=1",String.class,next));assertEquals("ELIGIBILITY_INVALID_AT_FREEZE",jdbc.queryForObject("SELECT reason FROM preparation_application WHERE batch_id=? AND user_id=1",String.class,next));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM frozen_person WHERE batch_id=?",Integer.class,next));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM application_version v JOIN preparation_application a ON v.application_id=a.id WHERE a.batch_id=?",Integer.class,next));
        assertEquals("LONG_APPLICATION_PENALTY",api("GET","/preparation-batches/"+next+"/application",null,login("student1"),null).data().at("/currentEligibility/reason").asString());
    }
    @Test void penaltyAfterFreezeStopsWholePublicationInsteadOfSilentlyShrinkingFrozenPeople() throws Exception {
        var f=fixture();var record=create(f);var deadline=clock.value.plusSeconds(86400);long next=future(f.admin(),deadline.minusSeconds(120),"eligibility-publication-batch");submit(f.owner(),next,2003,"eligibility-before-publication");clock.value=deadline.minusSeconds(120);var admin=login("admin1");freezeFuture(admin,next);String hash=jdbc.queryForObject("SELECT input_hash FROM frozen_input WHERE batch_id=?",String.class,next);due(record.id());ok(decision(admin,record.id(),"REVOKE",iso(clock.value.plusSeconds(86400)),"eligibility-publication-revoke"));ok(allocateFuture(admin,next));
        assertEquals("FAILED_NO_RESULT",jdbc.queryForObject("SELECT status FROM preparation_batch WHERE id=?",String.class,next));assertEquals("INPUT_INVALIDATED_ELIGIBILITY",jdbc.queryForObject("SELECT failure_reason FROM preparation_batch WHERE id=?",String.class,next));assertEquals(hash,jdbc.queryForObject("SELECT input_hash FROM frozen_input WHERE batch_id=?",String.class,next));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM frozen_person WHERE batch_id=?",Integer.class,next));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM allocation_result WHERE batch_id=?",Integer.class,next));
    }
    @Test void anOpenOfferCannotBeConfirmedAfterCurrentQualificationIsRevoked() throws Exception {
        var f=fixture();var record=create(f);var deadline=clock.value.plusSeconds(86400);long next=future(f.admin(),deadline.minusSeconds(180),"eligibility-confirmation-batch");submit(f.owner(),next,2003,"eligibility-before-confirmation");clock.value=deadline.minusSeconds(180);var admin=login("admin1");freezeFuture(admin,next);ok(allocateFuture(admin,next));long offer=jdbc.queryForObject("SELECT id FROM long_offer WHERE batch_id=? AND user_id=1",Long.class,next);due(record.id());ok(decision(admin,record.id(),"REVOKE",iso(clock.value.plusSeconds(86400)),"eligibility-confirmation-revoke"));
        error(api("POST","/long-offers/"+offer+"/actions",Map.of("version",1,"action","ACCEPT"),login("student1"),"confirmation-after-penalty"),409,"LONG_APPLICATION_PENALTY");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM seat_entitlement WHERE batch_id=?",Integer.class,next));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM long_offer WHERE id=?",String.class,offer));seats.maintain(next);assertEquals("INVALID",jdbc.queryForObject("SELECT status FROM long_offer WHERE id=?",String.class,offer));
    }
    @Test void stableWaitlistCannotPromoteSomeoneUnderACurrentPenaltyFromAnotherCycle() throws Exception {
        var admin=login("admin1");var one=login("student1");var two=login("student2");long old=open(admin,List.of(2000L,2001L),"promotion-old-cycle");submit(one,old,2000,"promotion-old-one");submit(two,old,2001,"promotion-old-two");draw(admin,old);
        for(var offer:jdbc.queryForList("SELECT id,user_id FROM long_offer WHERE batch_id=?",old))ok(api("POST","/long-offers/"+offer.get("id")+"/actions",Map.of("version",1,"action","ACCEPT"),Business.number(offer,"user_id")==1?one:two,"promotion-old-accept-"+offer.get("id")));
        var close=clock.value.plusSeconds(86400);long next=future(admin,close,"promotion-new-cycle");submit(one,next,2003,"promotion-new-one");submit(two,next,2003,"promotion-new-two");clock.value=close;admin=login("admin1");freezeFuture(admin,next);ok(allocateFuture(admin,next));long user=jdbc.queryForObject("SELECT user_id FROM waitlist_entry WHERE batch_id=? AND status='ACTIVE'",Long.class,next);var right=jdbc.queryForMap("SELECT e.id,e.offer_id FROM seat_entitlement e WHERE e.batch_id=? AND e.user_id=?",old,user);var record=create(new Fixture(admin,login(user==1?"student1":"student2"),old,Business.number(right,"offer_id"),Business.number(right,"id")));
        due(record.id());ok(decision(login("admin1"),record.id(),"REVOKE",iso(clock.value.plusSeconds(86400)),"promotion-penalty-revoke"));seats.maintain(next);assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM long_offer WHERE batch_id=? AND status='OPEN'",Integer.class,next));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM long_offer WHERE batch_id=?",Integer.class,next));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM waitlist_entry WHERE batch_id=? AND user_id=?",String.class,next,user));assertEquals("LONG_APPLICATION_PENALTY",api("GET","/preparation-batches/"+next+"/application",null,login(user==1?"student1":"student2"),null).data().at("/currentEligibility/reason").asString());
    }
}
