package dev.noctilume.qixu;

import static org.junit.jupiter.api.Assertions.*;
import dev.noctilume.qixu.common.Business;
import dev.noctilume.qixu.spaces.SpaceRights;
import java.net.*;
import java.net.http.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.nio.file.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/** Real spatial transactions; controlled beacon is explicitly not future-source qualification. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("demo")
@Import(PreparationIT.FaultConfig.class)
class SpaceBlocksIT {
    @DynamicPropertySource static void db(DynamicPropertyRegistry r) {FoundationIT.database(r);}
    @LocalServerPort int port;
    @Autowired JdbcTemplate jdbc;@Autowired JsonMapper json;@Autowired PreparationIT.MutableClock clock;@Autowired SpaceRights rights;
    @Autowired org.springframework.transaction.PlatformTransactionManager manager;
    @MockitoSpyBean Business business;
    private final HttpClient http=HttpClient.newHttpClient();private final List<Map<String,Object>> requests=new CopyOnWriteArrayList<>();private final Map<String,Object> observations=new LinkedHashMap<>();
    private static final Map<String,Object> RETAINED=new ConcurrentHashMap<>();private String name;
    record Reply(int status,JsonNode body) {JsonNode data() {return body.path("data");}long id() {return data().path("id").asLong();}}
    @BeforeEach void reset(TestInfo info) {
        name=info.getTestMethod().orElseThrow().getName();clock.value=Instant.parse("2026-10-10T01:00:00Z");TestData.clearBusiness(jdbc);jdbc.update("DELETE FROM auth_session");jdbc.update("DELETE FROM login_attempt");jdbc.update("DELETE FROM audit_entry");jdbc.update("UPDATE identity_user SET active=TRUE,auth_version=1,student_verified=(role='STUDENT') WHERE id BETWEEN 1 AND 5");jdbc.update("INSERT IGNORE INTO admin_scope(user_id,floor_id) VALUES(4,100),(4,101),(5,100)");jdbc.update("UPDATE space SET active=TRUE,version=1 WHERE id BETWEEN 2000 AND 2220");
        for(long id:List.of(5801L,5802L,5803L)) {long floor=id==5801?100:101;jdbc.update("INSERT IGNORE INTO space(id,floor_id,code,name,kind,use_mode,capacity,map_x,map_y,map_w,map_h,profile_json) VALUES(?,?,?,?,'SEAT','BOOKABLE',1,10,750,30,30,JSON_OBJECT())",id,floor,"SPATIAL-"+id,"临时位置验收夹具");jdbc.update("UPDATE space SET active=TRUE,version=1,profile_json=JSON_OBJECT('source','TEST_FIXTURE','features',JSON_OBJECT('window',TRUE,'outlet',TRUE,'quiet',TRUE,'accessible',TRUE)) WHERE id=?",id);}
    }
    @AfterEach void retain() {for(String table:List.of("space_block","block_impact","long_temporary_arrangement","short_relocation","seat_entitlement","long_offer","notification_outbox"))observations.put(table,jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class));RETAINED.put(name,Map.of("requests",requests,"database",observations,"source","CONTROLLED_TEST_DOUBLE_NOT_PUBLIC_BLS"));}
    @AfterAll static void write() throws Exception {var p=Path.of("target/failsafe-reports/qixu-m4-spatial-observation.json");Files.createDirectories(p.getParent());Files.writeString(p,JsonMapper.builder().build().writeValueAsString(RETAINED));}
    Reply api(String method,String path,Object body,String token,String key) throws Exception {
        var builder=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(25));if(token!=null)builder.header("Authorization","Bearer "+token);if(key!=null)builder.header("Idempotency-Key",key);if(body!=null)builder.header("Content-Type","application/json");builder.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));var result=http.send(builder.build(),HttpResponse.BodyHandlers.ofString());requests.add(Map.of("method",method,"path",path,"status",result.statusCode()));return new Reply(result.statusCode(),json.readTree(result.body()));
    }
    void ok(Reply r) {assertEquals(200,r.status(),r.body().toString());}void error(Reply r,int status,String code) {assertEquals(status,r.status(),r.body().toString());assertEquals(code,r.body().at("/error/code").asString());}
    String login(String user) throws Exception {var r=api("POST","/auth/login",Map.of("username",user,"password","qixu-demo","mode","BEARER"),null,null);ok(r);return r.data().path("token").asString();}
    Map<String,Object> plan(long space,String start,String end) {return new LinkedHashMap<>(Map.of("spaceId",space,"kind","MAINTENANCE","startsAt",start,"endsAt",end,"reason","验收专用空间检修","resolutions",List.of()));}
    Reply preview(String admin,Map<String,Object> p) throws Exception {var r=api("POST","/admin/space-blocks/preview",p,admin,null);ok(r);return r;}
    Map<String,Object> seal(String admin,Map<String,Object> p,String action,Long target) throws Exception {
        var raw=preview(admin,p);var choices=new ArrayList<Map<String,Object>>();for(var i:raw.data().path("impacts"))if(i.path("needsResolution").asBoolean()) {var choice=new LinkedHashMap<String,Object>();choice.put("impactKey",i.path("impactKey").asString());choice.put("action",action);if(target!=null)choice.put("targetSpaceId",target);choices.add(choice);}p.put("resolutions",choices);p.put("impactHash",preview(admin,p).data().path("impactHash").asString());return p;
    }
    Reply create(String admin,Map<String,Object> p,String key) throws Exception {return api("POST","/admin/space-blocks",p,admin,key);}
    void revoke(String admin,long id,String key) throws Exception {ok(api("POST","/admin/space-blocks/"+id+"/revoke",Map.of("version",1,"reason","验收检修已结束"),admin,key));}
    Reply shortSeat(String student,long seat,String key) throws Exception {var r=api("POST","/reservations",Map.of("spaceId",seat,"startsAt","2026-10-10T02:30:00Z","endsAt","2026-10-10T03:30:00Z"),student,key);ok(r);return r;}
    long[] longOffer(String admin,String student,boolean accept) throws Exception {
        var body=Map.ofEntries(Map.entry("title","空间限制验收批次"),Map.entry("purpose","POSTGRADUATE"),Map.entry("startsAt","2026-10-10T02:10:00Z"),Map.entry("endsAt","2026-10-20T02:10:00Z"),Map.entry("opensAt","2026-10-10T00:59:00Z"),Map.entry("closesAt","2026-10-10T01:05:00Z"),Map.entry("freezeDeadline","2026-10-10T01:06:00Z"),Map.entry("randomAt","2026-10-10T01:07:00Z"),Map.entry("resultDeadline","2026-10-10T01:20:00Z"),Map.entry("confirmationDeadline","2026-10-10T02:00:00Z"),Map.entry("promotionUntil","2026-10-20T02:10:00Z"),Map.entry("promotionSeconds",600),Map.entry("seatIds",List.of(2100)));
        var batch=api("POST","/preparation-batches",body,admin,"spatial-batch");ok(batch);ok(api("POST","/preparation-batches/"+batch.id()+"/application",Map.of("version",0,"preferences",List.of(Map.of("seatId",2100,"rank",1)),"keepWaitlist",true),student,"spatial-apply"));clock.value=Instant.parse("2026-10-10T01:05:00Z");ok(api("POST","/preparation-batches/"+batch.id()+"/actions",Map.of("version",1,"action","FREEZE"),admin,"spatial-freeze"));clock.value=Instant.parse("2026-10-10T01:07:03Z");ok(api("POST","/preparation-batches/"+batch.id()+"/actions",Map.of("version",2,"action","ALLOCATE"),admin,"spatial-allocate"));long offer=jdbc.queryForObject("SELECT id FROM long_offer WHERE batch_id=?",Long.class,batch.id());if(accept)ok(api("POST","/long-offers/"+offer+"/actions",Map.of("version",1,"action","ACCEPT"),student,"spatial-accept"));return new long[]{batch.id(),offer};
    }
    boolean available(long space,String start,String end) {return Boolean.TRUE.equals(rights.availability(space,LocalDateTime.ofInstant(Instant.parse(start),ZoneOffset.UTC),LocalDateTime.ofInstant(Instant.parse(end),ZoneOffset.UTC)).get("available"));}
    String start="2026-10-10T02:30:00Z",end="2026-10-10T03:30:00Z";
    @Test void stalePreviewCannotSilentlyCoverNewShortReservation() throws Exception {
        var admin=login("admin1");var student=login("student1");var p=seal(admin,plan(2000,start,end),"CANCEL",null);shortSeat(student,2000,"new-after-preview");error(create(admin,p,"stale-block"),409,"STALE_IMPACT");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("PENDING",jdbc.queryForObject("SELECT status FROM short_reservation",String.class));
        var current=seal(admin,p,"CANCEL",null);var result=create(admin,current,"stale-block");ok(result);assertFalse(available(2000,start,end));assertEquals("CANCELED",jdbc.queryForObject("SELECT status FROM short_reservation",String.class));revoke(admin,result.id(),"revoke-short-block");assertTrue(available(2000,start,end));
    }
    @Test void duplicateCompletePlanReplaysOriginalReceiptAndMoveKeepsDeadline() throws Exception {
        var admin=login("admin1");var student=login("student1");var old=shortSeat(student,2000,"short-to-move");var p=seal(admin,plan(2000,start,end),"MOVE",5802L);var r=create(admin,p,"move-plan");ok(r);assertEquals(r.data(),create(admin,p,"move-plan").data());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM short_relocation",Integer.class));assertEquals("CANCELED",jdbc.queryForObject("SELECT status FROM short_reservation WHERE id=?",String.class,old.id()));assertEquals(5802,jdbc.queryForObject("SELECT space_id FROM short_reservation WHERE status='PENDING'",Long.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM short_relocation m JOIN short_reservation a ON m.original_id=a.id JOIN short_reservation z ON m.replacement_id=z.id WHERE a.check_in_deadline<>z.check_in_deadline",Integer.class));
    }
    @Test void overlappingLimitsKeepOriginalRightAndRevokeOnlyOneSource() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,true);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"overlap-first");ok(a);var z=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"overlap-second");ok(z);assertFalse(available(5802,start,end));revoke(admin,a.id(),"revoke-one-source");assertFalse(available(5802,start,end));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE offer_id=? AND status='ACTIVE'",Long.class,ids[1]));revoke(admin,z.id(),"revoke-other-source");assertTrue(available(5802,start,end));assertFalse(available(2100,start,end));
    }
    @Test void temporarySeatCanBeLimitedAgainAndUpstreamReleaseDoesNotLeakDownstreamClaim() throws Exception {
        var admin=login("admin1");var student=login("student1");longOffer(admin,student,true);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"first-chain");ok(a);var z=create(admin,seal(admin,plan(5802,start,end),"TEMPORARY",5803L),"second-chain");ok(z);assertFalse(available(5803,start,end));revoke(admin,a.id(),"chain-upstream-release");assertTrue(available(5803,start,end));assertFalse(available(5802,start,end));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE status='ACTIVE'",Long.class));
    }
    @Test void affectedOpenOfferNeedsCurrentImpactAndExpirationReleasesTemporaryHoldWithoutTask() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,false);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"open-offer-limit");ok(a);error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT"),student,"missing-impact"),409,"STALE_OFFER_IMPACT");var impact=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);ok(impact);error(api("GET","/long-offers/"+ids[1]+"/impact",null,login("student2"),null),404,"RESOURCE_NOT_FOUND");assertFalse(available(5802,start,end));clock.value=Instant.parse("2026-10-10T02:00:00Z");assertTrue(available(5802,start,end));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM long_offer WHERE id=?",String.class,ids[1]));
    }
    @Test void staleAcknowledgementDoesNotConfirmChangedOfferButCurrentAcknowledgementDoes() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,false);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"first-ack-limit");ok(a);var first=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);var z=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"second-ack-limit");ok(z);
        error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT","impactHash",first.data().path("impactHash").asString()),student,"old-ack-v1"),409,"STALE_OFFER_IMPACT");var current=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);var body=Map.of("version",1,"action","ACCEPT","impactHash",current.data().path("impactHash").asString());var accepted=api("POST","/long-offers/"+ids[1]+"/actions",body,student,"current-ack");ok(accepted);clock.value=Instant.parse("2026-10-10T02:30:00Z");assertEquals(accepted.data(),api("POST","/long-offers/"+ids[1]+"/actions",body,student,"current-ack").data());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM seat_entitlement WHERE status='ACTIVE'",Integer.class));
    }
    @Test void secondNotificationFaultRollsBackLimitArrangementsAndShortChanges() throws Exception {
        var admin=login("admin1");var one=login("student1");var two=login("student2");shortSeat(one,5802,"fault-short-one");shortSeat(two,5803,"fault-short-two");long parent=9990;jdbc.update("INSERT IGNORE INTO space(id,floor_id,code,name,kind,use_mode,capacity,map_x,map_y,map_w,map_h,profile_json) VALUES(9990,101,'TEST-PARENT','验收专用区域','AREA','VENUE',10,0,0,1000,1000,JSON_OBJECT())");jdbc.update("UPDATE space SET parent_id=9990 WHERE id IN (5802,5803)");var p=seal(admin,plan(parent,start,end),"CANCEL",null);var counter=new java.util.concurrent.atomic.AtomicInteger();
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).startsWith("block:")&&counter.incrementAndGet()==2)throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_SECOND_LIMIT_NOTIFICATION");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {assertEquals(503,create(admin,p,"fault-limit").status());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM short_reservation WHERE status='PENDING'",Integer.class));}
        finally {org.mockito.Mockito.doCallRealMethod().when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());jdbc.update("UPDATE space SET parent_id=NULL WHERE id IN (5802,5803)");}
    }
    @Test void scopeRevokedDuringFloorWaitCannotCreateLimit() throws Exception {
        var admin=login("admin1");var p=seal(admin,plan(5802,start,end),"CANCEL",null);var locked=new CountDownLatch(1);var release=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);
        try {var guard=pool.submit(()->new org.springframework.transaction.support.TransactionTemplate(manager).execute(status->{jdbc.queryForList("SELECT id FROM floor WHERE id=101 FOR UPDATE");locked.countDown();try {assertTrue(release.await(10,TimeUnit.SECONDS));}catch(InterruptedException e) {throw new RuntimeException(e);}return null;}));assertTrue(locked.await(5,TimeUnit.SECONDS));var request=pool.submit(()->create(admin,p,"revoked-wait-plan"));Thread.sleep(150);jdbc.update("DELETE FROM admin_scope WHERE user_id=4 AND floor_id=101");release.countDown();guard.get(10,TimeUnit.SECONDS);error(request.get(15,TimeUnit.SECONDS),403,"SCOPE_FORBIDDEN");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));}
        finally {release.countDown();pool.shutdownNow();jdbc.update("INSERT IGNORE INTO admin_scope(user_id,floor_id) VALUES(4,101)");}
    }
    @Test void concurrentPlansCannotMoveTwoPeopleToSameTemporarySeat() throws Exception {
        var admin=login("admin1");shortSeat(login("student1"),2000,"race-short-one");shortSeat(login("student2"),2001,"race-short-two");var a=seal(admin,plan(2000,start,end),"MOVE",5802L);var z=seal(admin,plan(2001,start,end),"MOVE",5802L);var pool=Executors.newFixedThreadPool(2);var ready=new CountDownLatch(2);var go=new CountDownLatch(1);
        try {var first=pool.submit(()->{ready.countDown();go.await();return create(admin,a,"race-plan-one");});var second=pool.submit(()->{ready.countDown();go.await();return create(admin,z,"race-plan-two");});assertTrue(ready.await(5,TimeUnit.SECONDS));go.countDown();var results=List.of(first.get(25,TimeUnit.SECONDS),second.get(25,TimeUnit.SECONDS));assertEquals(List.of(200,409),results.stream().map(Reply::status).sorted().toList());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM short_reservation WHERE space_id=5802 AND status='PENDING'",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));}
        finally {go.countDown();pool.shutdownNow();}
    }
    @Test void mismatchedOverlappingAlternativesRollBackWithoutEditingOriginalResult() throws Exception {
        var admin=login("admin1");longOffer(admin,login("student1"),true);var hash=jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class);var first=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"consistent-first");ok(first);error(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5803L),"inconsistent-second"),409,"TEMPORARY_DISAGREEMENT");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM long_temporary_arrangement",Integer.class));assertEquals(hash,jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class));assertTrue(available(5803,start,end));assertFalse(available(5802,start,end));
    }
    @Test void shrinkingImpactAfterExpiryStillInvalidatesOldPreview() throws Exception {
        var admin=login("admin1");var shortOne=api("POST","/reservations",Map.of("spaceId",2000,"startsAt","2026-10-10T01:02:00Z","endsAt","2026-10-10T01:04:00Z"),login("student1"),"short-expiring");ok(shortOne);var p=seal(admin,plan(2000,"2026-10-10T01:03:00Z","2026-10-10T01:30:00Z"),"CANCEL",null);clock.value=Instant.parse("2026-10-10T01:04:00Z");error(create(admin,p,"shrunk-impact"),409,"STALE_IMPACT");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("PENDING",jdbc.queryForObject("SELECT status FROM short_reservation WHERE id=?",String.class,shortOne.id()));
    }
    @Test void safetyCanExposeRealUnavailableWindowButPlannedCourseCannot() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,true);var course=plan(2100,start,end);course.put("kind","COURSE");error(create(admin,seal(admin,course,"UNAVAILABLE",null),"course-no-alternative"),422,"INVALID_INPUT");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));
        var safety=plan(2100,start,end);safety.put("kind","SAFETY");ok(create(admin,seal(admin,safety,"UNAVAILABLE",null),"safety-no-alternative"));var impact=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);ok(impact);assertEquals("TEMPORARILY_UNAVAILABLE",impact.data().at("/segments/0/state").asString());assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE status='ACTIVE'",Long.class));assertFalse(available(2100,start,end));
    }
    @Test void temporaryWindowHasHalfOpenEndWithoutLosingLongOwnership() throws Exception {
        var admin=login("admin1");longOffer(admin,login("student1"),true);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"temporal-boundary"));assertFalse(available(5802,start,end));assertTrue(available(5802,end,"2026-10-10T04:00:00Z"));clock.value=Instant.parse(end);assertTrue(available(5802,end,"2026-10-10T04:00:00Z"));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block",String.class));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement",String.class));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement",Long.class));
    }
    @Test void resolvedEventApprovalAndCancellationPreserveOtherLimitAndParticipationHistory() throws Exception {
        var admin=login("admin1");var teacher=login("teacher1");var student=login("student1");longOffer(admin,student,true);
        var venue=api("POST","/venue-requests",Map.of("spaceId",1001,"startsAt",start,"endsAt",end,"people",2,"purpose","阅读公开课","description","验收专用活动","contact","组织者"),teacher,"event-venue-request");ok(venue);error(api("POST","/venue-requests/"+venue.id()+"/actions",Map.of("version",1,"action","APPROVE","reason","普通审批不能覆盖既有权"),admin,"ordinary-approval-blocked"),409,"SPACE_CONFLICT");
        var p=plan(1001,start,end);p.put("kind","EVENT");p.put("venueRequestId",venue.id());p.put("venueVersion",1);var resolved=create(admin,seal(admin,p,"TEMPORARY",5802L),"resolved-event-venue");ok(resolved);error(api("POST","/admin/space-blocks/"+resolved.id()+"/revoke",Map.of("version",1,"reason","不能绕过活动"),admin,"revoke-linked-event"),409,"EVENT_BOUND");
        var event=api("POST","/organizer/events",Map.of("venueRequestId",venue.id(),"title","阅读公开课","eventType","CLASS","speaker","老师","description","活动说明","notice","准时参加","capacity",2,"opensAt","2026-10-10T00:00:00Z","closesAt","2026-10-10T02:15:00Z","promotionUntil","2026-10-10T02:25:00Z"),teacher,"resolved-create-event");ok(event);ok(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",1,"action","PUBLISH","reason","场地与处置已成立"),teacher,"resolved-publish-event"));ok(api("POST","/events/"+event.id()+"/participation",Map.of("action","JOIN"),student,"join-resolved-event"));
        var maintenance=create(admin,seal(admin,plan(5802,start,end),"TEMPORARY",5803L),"event-other-maintenance");ok(maintenance);assertFalse(available(5803,start,end));
        error(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",2,"action","CANCEL","reason","旧页面版本不能覆盖报名变化"),teacher,"stale-cancel-event"),409,"STALE_VERSION");var latest=api("GET","/events/"+event.id(),null,teacher,null);ok(latest);
        ok(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",latest.data().path("version").asLong(),"action","CANCEL","reason","活动取消，检修独立保留"),teacher,"cancel-resolved-event"));assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,resolved.id()));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,maintenance.id()));assertEquals("EVENT_CANCELED",jdbc.queryForObject("SELECT status FROM event_participation WHERE event_id=?",String.class,event.id()));assertFalse(available(5802,start,end));assertTrue(available(5803,start,end));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE status='ACTIVE'",Long.class));
    }
    @Test void relocatingPeopleDoesNotMakeMaintenanceAreaAvailableForEvent() throws Exception {
        var admin=login("admin1");longOffer(admin,login("student1"),true);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"maintenance-before-event"));var venue=api("POST","/venue-requests",Map.of("spaceId",1001,"startsAt",start,"endsAt",end,"people",2,"purpose","阅读公开课","description","验收专用活动","contact","组织者"),login("teacher1"),"maintenance-event-request");ok(venue);var p=plan(1001,start,end);p.put("kind","EVENT");p.put("venueRequestId",venue.id());p.put("venueVersion",1);error(create(admin,seal(admin,p,"TEMPORARY",5802L),"event-covering-maintenance"),409,"SPACE_CONFLICT");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("SUBMITTED",jdbc.queryForObject("SELECT status FROM venue_request WHERE id=?",String.class,venue.id()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM venue_entitlement",Integer.class));
    }
}
