package dev.noctilume.qixu;

import static org.junit.jupiter.api.Assertions.*;
import dev.noctilume.qixu.common.Business;
import dev.noctilume.qixu.spaces.SpaceRights;
import java.net.*;
import java.net.http.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.nio.file.*;
import org.junit.jupiter.api.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.*;
import org.springframework.boot.test.web.server.LocalServerPort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.*;
import org.springframework.test.context.bean.override.mockito.MockitoSpyBean;
import tools.jackson.databind.JsonNode;
import tools.jackson.databind.json.JsonMapper;

/** Real spatial transactions; controlled beacon is explicitly not future-source qualification. */
@SpringBootTest(webEnvironment=SpringBootTest.WebEnvironment.RANDOM_PORT)
@ActiveProfiles("demo")
@Import(PreparationIT.FaultConfig.class)
class SpaceBlocksIT {
    @DynamicPropertySource static void db(DynamicPropertyRegistry r) {FoundationIT.database(r);}
    @LocalServerPort int port;
    @Autowired JdbcTemplate jdbc;@Autowired JsonMapper json;@Autowired PreparationIT.MutableClock clock;@Autowired SpaceRights rights;
    @Autowired org.springframework.transaction.PlatformTransactionManager manager;
    @MockitoSpyBean Business business;
    private final HttpClient http=HttpClient.newHttpClient();private final List<Map<String,Object>> requests=new CopyOnWriteArrayList<>();private final Map<String,Object> observations=new LinkedHashMap<>();
    private static final Map<String,Object> RETAINED=new ConcurrentHashMap<>();private String name;
    record Reply(int status,JsonNode body) {JsonNode data() {return body.path("data");}long id() {return data().path("id").asLong();}}
    @BeforeEach void reset(TestInfo info) {
        name=info.getTestMethod().orElseThrow().getName();clock.value=Instant.parse("2026-10-10T01:00:00Z");TestData.clearBusiness(jdbc);jdbc.update("DELETE FROM auth_session");jdbc.update("DELETE FROM login_attempt");jdbc.update("DELETE FROM audit_entry");jdbc.update("UPDATE identity_user SET active=TRUE,auth_version=1,student_verified=(role='STUDENT') WHERE id BETWEEN 1 AND 5");jdbc.update("INSERT IGNORE INTO admin_scope(user_id,floor_id) VALUES(4,100),(4,101),(5,100)");jdbc.update("UPDATE space SET active=TRUE,version=1 WHERE id BETWEEN 2000 AND 2220");
        for(long id:List.of(5801L,5802L,5803L)) {long floor=id==5801?100:101;jdbc.update("INSERT IGNORE INTO space(id,floor_id,code,name,kind,use_mode,capacity,map_x,map_y,map_w,map_h,profile_json) VALUES(?,?,?,?,'SEAT','BOOKABLE',1,10,750,30,30,JSON_OBJECT())",id,floor,"SPATIAL-"+id,"临时位置验收夹具");jdbc.update("UPDATE space SET active=TRUE,version=1,profile_json=JSON_OBJECT('source','TEST_FIXTURE','features',JSON_OBJECT('window',TRUE,'outlet',TRUE,'quiet',TRUE,'accessible',TRUE)) WHERE id=?",id);}
    }
    @AfterEach void retain() {M4Measurements.collect(jdbc,observations);for(String table:List.of("space_block","block_impact","long_temporary_arrangement","short_relocation","seat_entitlement","long_offer","notification_outbox"))observations.put(table,jdbc.queryForObject("SELECT COUNT(*) FROM "+table,Integer.class));RETAINED.put(name,Map.of("requests",requests,"database",observations,"source","CONTROLLED_TEST_DOUBLE_NOT_PUBLIC_BLS"));}
    @AfterAll static void write() throws Exception {var p=Path.of("target/failsafe-reports/qixu-m4-spatial-observation.json");Files.createDirectories(p.getParent());Files.writeString(p,JsonMapper.builder().build().writeValueAsString(RETAINED));}
    Reply api(String method,String path,Object body,String token,String key) throws Exception {
        var builder=HttpRequest.newBuilder(URI.create("http://127.0.0.1:"+port+"/api/v1"+path)).timeout(Duration.ofSeconds(25));if(token!=null)builder.header("Authorization","Bearer "+token);if(key!=null)builder.header("Idempotency-Key",key);if(body!=null)builder.header("Content-Type","application/json");builder.method(method,body==null?HttpRequest.BodyPublishers.noBody():HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)));var result=http.send(builder.build(),HttpResponse.BodyHandlers.ofString());requests.add(Map.of("method",method,"path",path,"status",result.statusCode()));return new Reply(result.statusCode(),json.readTree(result.body()));
    }
    void ok(Reply r) {assertEquals(200,r.status(),r.body().toString());}void error(Reply r,int status,String code) {assertEquals(status,r.status(),r.body().toString());assertEquals(code,r.body().at("/error/code").asString());}
    String login(String user) throws Exception {var r=api("POST","/auth/login",Map.of("username",user,"password","qixu-demo","mode","BEARER"),null,null);ok(r);return r.data().path("token").asString();}
    Map<String,Object> plan(long space,String start,String end) {return new LinkedHashMap<>(Map.of("spaceId",space,"kind","MAINTENANCE","startsAt",start,"endsAt",end,"reason","验收专用空间检修","resolutions",List.of()));}
    Reply preview(String admin,Map<String,Object> p) throws Exception {var r=api("POST","/admin/space-blocks/preview",p,admin,null);ok(r);return r;}
    Map<String,Object> seal(String admin,Map<String,Object> p,String action,Long target) throws Exception {
        var raw=preview(admin,p);var choices=new ArrayList<Map<String,Object>>();for(var i:raw.data().path("impacts"))if(i.path("needsResolution").asBoolean()) {var choice=new LinkedHashMap<String,Object>();choice.put("impactKey",i.path("impactKey").asString());choice.put("action",action);if(target!=null)choice.put("targetSpaceId",target);choices.add(choice);}p.put("resolutions",choices);p.put("impactHash",preview(admin,p).data().path("impactHash").asString());return p;
    }
    Reply create(String admin,Map<String,Object> p,String key) throws Exception {return api("POST","/admin/space-blocks",p,admin,key);}
    void revoke(String admin,long id,String key) throws Exception {ok(api("POST","/admin/space-blocks/"+id+"/revoke",Map.of("version",1,"reason","验收检修已结束"),admin,key));}
    Reply shortSeat(String student,long seat,String key) throws Exception {var r=api("POST","/reservations",Map.of("spaceId",seat,"startsAt","2026-10-10T02:30:00Z","endsAt","2026-10-10T03:30:00Z"),student,key);ok(r);return r;}
    long openBatch(String admin) throws Exception {
        var body=Map.ofEntries(Map.entry("title","空间限制验收批次"),Map.entry("purpose","POSTGRADUATE"),Map.entry("startsAt","2026-10-10T02:10:00Z"),Map.entry("endsAt","2026-10-20T02:10:00Z"),Map.entry("opensAt","2026-10-10T00:59:00Z"),Map.entry("closesAt","2026-10-10T01:05:00Z"),Map.entry("freezeDeadline","2026-10-10T01:06:00Z"),Map.entry("randomAt","2026-10-10T01:07:00Z"),Map.entry("resultDeadline","2026-10-10T01:20:00Z"),Map.entry("confirmationDeadline","2026-10-10T02:00:00Z"),Map.entry("promotionUntil","2026-10-20T02:10:00Z"),Map.entry("promotionSeconds",600),Map.entry("seatIds",List.of(2100)));
        var batch=api("POST","/preparation-batches",body,admin,"spatial-batch");ok(batch);return batch.id();
    }
    void apply(long batch,String student,String key) throws Exception {ok(api("POST","/preparation-batches/"+batch+"/application",Map.of("version",0,"preferences",List.of(Map.of("seatId",2100,"rank",1)),"keepWaitlist",true),student,key));}
    long[] longOffer(String admin,String student,boolean accept) throws Exception {
        long batch=openBatch(admin);apply(batch,student,"spatial-apply");clock.value=Instant.parse("2026-10-10T01:05:00Z");ok(api("POST","/preparation-batches/"+batch+"/actions",Map.of("version",1,"action","FREEZE"),admin,"spatial-freeze"));clock.value=Instant.parse("2026-10-10T01:07:03Z");ok(api("POST","/preparation-batches/"+batch+"/actions",Map.of("version",2,"action","ALLOCATE"),admin,"spatial-allocate"));long offer=jdbc.queryForObject("SELECT id FROM long_offer WHERE batch_id=?",Long.class,batch);if(accept)ok(api("POST","/long-offers/"+offer+"/actions",Map.of("version",1,"action","ACCEPT"),student,"spatial-accept"));return new long[]{batch,offer};
    }
    boolean available(long space,String start,String end) {return Boolean.TRUE.equals(rights.availability(space,LocalDateTime.ofInstant(Instant.parse(start),ZoneOffset.UTC),LocalDateTime.ofInstant(Instant.parse(end),ZoneOffset.UTC)).get("available"));}
    String start="2026-10-10T02:30:00Z",end="2026-10-10T03:30:00Z";
    @Test void stalePreviewCannotSilentlyCoverNewShortReservation() throws Exception {
        var admin=login("admin1");var student=login("student1");var p=seal(admin,plan(2000,start,end),"CANCEL",null);shortSeat(student,2000,"new-after-preview");error(create(admin,p,"stale-block"),409,"STALE_IMPACT");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("PENDING",jdbc.queryForObject("SELECT status FROM short_reservation",String.class));
        var current=seal(admin,p,"CANCEL",null);var result=create(admin,current,"stale-block");ok(result);assertFalse(available(2000,start,end));assertEquals("CANCELED",jdbc.queryForObject("SELECT status FROM short_reservation",String.class));revoke(admin,result.id(),"revoke-short-block");assertTrue(available(2000,start,end));
    }
    @Test void duplicateCompletePlanReplaysOriginalReceiptAndMoveKeepsDeadline() throws Exception {
        var admin=login("admin1");var student=login("student1");var old=shortSeat(student,2000,"short-to-move");var p=seal(admin,plan(2000,start,end),"MOVE",5802L);var r=create(admin,p,"move-plan");ok(r);assertEquals(r.data(),create(admin,p,"move-plan").data());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM short_relocation",Integer.class));assertEquals("CANCELED",jdbc.queryForObject("SELECT status FROM short_reservation WHERE id=?",String.class,old.id()));assertEquals(5802,jdbc.queryForObject("SELECT space_id FROM short_reservation WHERE status='PENDING'",Long.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM short_relocation m JOIN short_reservation a ON m.original_id=a.id JOIN short_reservation z ON m.replacement_id=z.id WHERE a.check_in_deadline<>z.check_in_deadline",Integer.class));
    }
    @Test void overlappingLimitsKeepOriginalRightAndRevokeOnlyOneSource() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,true);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"overlap-first");ok(a);var z=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"overlap-second");ok(z);assertFalse(available(5802,start,end));revoke(admin,a.id(),"revoke-one-source");assertFalse(available(5802,start,end));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE offer_id=? AND status='ACTIVE'",Long.class,ids[1]));revoke(admin,z.id(),"revoke-other-source");assertTrue(available(5802,start,end));assertFalse(available(2100,start,end));
    }
    @Test void temporarySeatCanBeLimitedAgainAndUpstreamReleaseDoesNotLeakDownstreamClaim() throws Exception {
        var admin=login("admin1");var student=login("student1");longOffer(admin,student,true);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"first-chain");ok(a);var z=create(admin,seal(admin,plan(5802,start,end),"TEMPORARY",5803L),"second-chain");ok(z);assertFalse(available(5803,start,end));revoke(admin,a.id(),"chain-upstream-release");assertTrue(available(5803,start,end));assertFalse(available(5802,start,end));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE status='ACTIVE'",Long.class));
    }
    @Test void affectedOpenOfferNeedsCurrentImpactAndExpirationReleasesTemporaryHoldWithoutTask() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,false);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"open-offer-limit");ok(a);error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT"),student,"missing-impact"),409,"STALE_OFFER_IMPACT");var impact=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);ok(impact);error(api("GET","/long-offers/"+ids[1]+"/impact",null,login("student2"),null),404,"RESOURCE_NOT_FOUND");assertFalse(available(5802,start,end));clock.value=Instant.parse("2026-10-10T02:00:00Z");assertTrue(available(5802,start,end));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM long_offer WHERE id=?",String.class,ids[1]));
    }
    @Test void staleAcknowledgementDoesNotConfirmChangedOfferButCurrentAcknowledgementDoes() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,false);var a=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"first-ack-limit");ok(a);var first=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);var z=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"second-ack-limit");ok(z);
        error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT","impactHash",first.data().path("impactHash").asString()),student,"old-ack-v1"),409,"STALE_OFFER_IMPACT");var current=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);var body=Map.of("version",1,"action","ACCEPT","impactHash",current.data().path("impactHash").asString());var accepted=api("POST","/long-offers/"+ids[1]+"/actions",body,student,"current-ack");ok(accepted);clock.value=Instant.parse("2026-10-10T02:30:00Z");assertEquals(accepted.data(),api("POST","/long-offers/"+ids[1]+"/actions",body,student,"current-ack").data());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM seat_entitlement WHERE status='ACTIVE'",Integer.class));
    }
    @Test void secondNotificationFaultRollsBackLimitArrangementsAndShortChanges() throws Exception {
        var admin=login("admin1");var one=login("student1");var two=login("student2");shortSeat(one,5802,"fault-short-one");shortSeat(two,5803,"fault-short-two");long parent=9990;jdbc.update("INSERT IGNORE INTO space(id,floor_id,code,name,kind,use_mode,capacity,map_x,map_y,map_w,map_h,profile_json) VALUES(9990,101,'TEST-PARENT','验收专用区域','AREA','VENUE',10,0,0,1000,1000,JSON_OBJECT())");jdbc.update("UPDATE space SET parent_id=9990 WHERE id IN (5802,5803)");var p=seal(admin,plan(parent,start,end),"CANCEL",null);var counter=new java.util.concurrent.atomic.AtomicInteger();
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).startsWith("block:")&&counter.incrementAndGet()==2)throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_SECOND_LIMIT_NOTIFICATION");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {assertEquals(503,create(admin,p,"fault-limit").status());assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM short_reservation WHERE status='PENDING'",Integer.class));}
        finally {org.mockito.Mockito.doCallRealMethod().when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());jdbc.update("UPDATE space SET parent_id=NULL WHERE id IN (5802,5803)");}
    }
    @Test void scopeRevokedDuringFloorWaitCannotCreateLimit() throws Exception {
        var admin=login("admin1");var p=seal(admin,plan(5802,start,end),"CANCEL",null);var locked=new CountDownLatch(1);var release=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(2);
        try {var guard=pool.submit(()->new org.springframework.transaction.support.TransactionTemplate(manager).execute(status->{jdbc.queryForList("SELECT id FROM floor WHERE id=101 FOR UPDATE");locked.countDown();try {assertTrue(release.await(10,TimeUnit.SECONDS));}catch(InterruptedException e) {throw new RuntimeException(e);}return null;}));assertTrue(locked.await(5,TimeUnit.SECONDS));var request=pool.submit(()->create(admin,p,"revoked-wait-plan"));Thread.sleep(150);jdbc.update("DELETE FROM admin_scope WHERE user_id=4 AND floor_id=101");release.countDown();guard.get(10,TimeUnit.SECONDS);error(request.get(15,TimeUnit.SECONDS),403,"SCOPE_FORBIDDEN");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));}
        finally {release.countDown();pool.shutdownNow();jdbc.update("INSERT IGNORE INTO admin_scope(user_id,floor_id) VALUES(4,101)");}
    }
    @Test void concurrentPlansCannotMoveTwoPeopleToSameTemporarySeat() throws Exception {
        var admin=login("admin1");shortSeat(login("student1"),2000,"race-short-one");shortSeat(login("student2"),2001,"race-short-two");var a=seal(admin,plan(2000,start,end),"MOVE",5802L);var z=seal(admin,plan(2001,start,end),"MOVE",5802L);var pool=Executors.newFixedThreadPool(2);var ready=new CountDownLatch(2);var go=new CountDownLatch(1);
        try {var first=pool.submit(()->{ready.countDown();go.await();return create(admin,a,"race-plan-one");});var second=pool.submit(()->{ready.countDown();go.await();return create(admin,z,"race-plan-two");});assertTrue(ready.await(5,TimeUnit.SECONDS));go.countDown();var results=List.of(first.get(25,TimeUnit.SECONDS),second.get(25,TimeUnit.SECONDS));assertEquals(List.of(200,409),results.stream().map(Reply::status).sorted().toList());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM short_reservation WHERE space_id=5802 AND status='PENDING'",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));}
        finally {go.countDown();pool.shutdownNow();}
    }
    @Test void mismatchedOverlappingAlternativesRollBackWithoutEditingOriginalResult() throws Exception {
        var admin=login("admin1");longOffer(admin,login("student1"),true);var hash=jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class);var first=create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"consistent-first");ok(first);error(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5803L),"inconsistent-second"),409,"TEMPORARY_DISAGREEMENT");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM long_temporary_arrangement",Integer.class));assertEquals(hash,jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class));assertTrue(available(5803,start,end));assertFalse(available(5802,start,end));
    }
    @Test void shrinkingImpactAfterExpiryStillInvalidatesOldPreview() throws Exception {
        var admin=login("admin1");var shortOne=api("POST","/reservations",Map.of("spaceId",2000,"startsAt","2026-10-10T01:02:00Z","endsAt","2026-10-10T01:04:00Z"),login("student1"),"short-expiring");ok(shortOne);var p=seal(admin,plan(2000,"2026-10-10T01:03:00Z","2026-10-10T01:30:00Z"),"CANCEL",null);clock.value=Instant.parse("2026-10-10T01:04:00Z");error(create(admin,p,"shrunk-impact"),409,"STALE_IMPACT");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("PENDING",jdbc.queryForObject("SELECT status FROM short_reservation WHERE id=?",String.class,shortOne.id()));
    }
    @Test void safetyCanExposeRealUnavailableWindowButPlannedCourseCannot() throws Exception {
        var admin=login("admin1");var student=login("student1");var ids=longOffer(admin,student,true);var course=plan(2100,start,end);course.put("kind","COURSE");error(create(admin,seal(admin,course,"UNAVAILABLE",null),"course-no-alternative"),422,"INVALID_INPUT");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));
        var safety=plan(2100,start,end);safety.put("kind","SAFETY");ok(create(admin,seal(admin,safety,"UNAVAILABLE",null),"safety-no-alternative"));var impact=api("GET","/long-offers/"+ids[1]+"/impact",null,student,null);ok(impact);assertEquals("TEMPORARILY_UNAVAILABLE",impact.data().at("/segments/0/state").asString());assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE status='ACTIVE'",Long.class));assertFalse(available(2100,start,end));
    }
    @Test void temporaryWindowHasHalfOpenEndWithoutLosingLongOwnership() throws Exception {
        var admin=login("admin1");longOffer(admin,login("student1"),true);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"temporal-boundary"));assertFalse(available(5802,start,end));assertTrue(available(5802,end,"2026-10-10T04:00:00Z"));clock.value=Instant.parse(end);assertTrue(available(5802,end,"2026-10-10T04:00:00Z"));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block",String.class));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement",String.class));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement",Long.class));
    }
    @Test void resolvedEventApprovalAndCancellationPreserveOtherLimitAndParticipationHistory() throws Exception {
        var admin=login("admin1");var teacher=login("teacher1");var student=login("student1");longOffer(admin,student,true);
        var venue=api("POST","/venue-requests",Map.of("spaceId",1001,"startsAt",start,"endsAt",end,"people",2,"purpose","阅读公开课","description","验收专用活动","contact","组织者"),teacher,"event-venue-request");ok(venue);error(api("POST","/venue-requests/"+venue.id()+"/actions",Map.of("version",1,"action","APPROVE","reason","普通审批不能覆盖既有权"),admin,"ordinary-approval-blocked"),409,"SPACE_CONFLICT");
        var p=plan(1001,start,end);p.put("kind","EVENT");p.put("venueRequestId",venue.id());p.put("venueVersion",1);var resolved=create(admin,seal(admin,p,"TEMPORARY",5802L),"resolved-event-venue");ok(resolved);error(api("POST","/admin/space-blocks/"+resolved.id()+"/revoke",Map.of("version",1,"reason","不能绕过活动"),admin,"revoke-linked-event"),409,"EVENT_BOUND");
        var event=api("POST","/organizer/events",Map.of("venueRequestId",venue.id(),"title","阅读公开课","eventType","CLASS","speaker","老师","description","活动说明","notice","准时参加","capacity",2,"opensAt","2026-10-10T00:00:00Z","closesAt","2026-10-10T02:15:00Z","promotionUntil","2026-10-10T02:25:00Z"),teacher,"resolved-create-event");ok(event);ok(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",1,"action","PUBLISH","reason","场地与处置已成立"),teacher,"resolved-publish-event"));ok(api("POST","/events/"+event.id()+"/participation",Map.of("action","JOIN"),student,"join-resolved-event"));
        var maintenance=create(admin,seal(admin,plan(5802,start,end),"TEMPORARY",5803L),"event-other-maintenance");ok(maintenance);assertFalse(available(5803,start,end));
        error(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",2,"action","CANCEL","reason","旧页面版本不能覆盖报名变化"),teacher,"stale-cancel-event"),409,"STALE_VERSION");var latest=api("GET","/events/"+event.id(),null,teacher,null);ok(latest);
        ok(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",latest.data().path("version").asLong(),"action","CANCEL","reason","活动取消，检修独立保留"),teacher,"cancel-resolved-event"));assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,resolved.id()));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,maintenance.id()));assertEquals("EVENT_CANCELED",jdbc.queryForObject("SELECT status FROM event_participation WHERE event_id=?",String.class,event.id()));assertFalse(available(5802,start,end));assertTrue(available(5803,start,end));assertEquals(2100,jdbc.queryForObject("SELECT space_id FROM seat_entitlement WHERE status='ACTIVE'",Long.class));
    }
    @Test void relocatingPeopleDoesNotMakeMaintenanceAreaAvailableForEvent() throws Exception {
        var admin=login("admin1");longOffer(admin,login("student1"),true);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"maintenance-before-event"));var venue=api("POST","/venue-requests",Map.of("spaceId",1001,"startsAt",start,"endsAt",end,"people",2,"purpose","阅读公开课","description","验收专用活动","contact","组织者"),login("teacher1"),"maintenance-event-request");ok(venue);var p=plan(1001,start,end);p.put("kind","EVENT");p.put("venueRequestId",venue.id());p.put("venueVersion",1);error(create(admin,seal(admin,p,"TEMPORARY",5802L),"event-covering-maintenance"),409,"SPACE_CONFLICT");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("SUBMITTED",jdbc.queryForObject("SELECT status FROM venue_request WHERE id=?",String.class,venue.id()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM venue_entitlement",Integer.class));
    }
    @Test void restoringLimitNotifiesOriginalWithdrawnAndLaterApplicantWithoutInboxAuthority() throws Exception {
        var admin=login("admin1");var one=login("student1");var two=login("student2");long batch=openBatch(admin);apply(batch,one,"original-block-applicant");var block=create(admin,seal(admin,plan(2100,start,end),"CANCEL",null),"block-pool-notice");ok(block);
        assertEquals(List.of(1L),jdbc.queryForList("SELECT user_id FROM block_recipient WHERE block_id=? ORDER BY user_id",Long.class,block.id()));assertEquals(batch,jdbc.queryForObject("SELECT batch_id FROM block_batch WHERE block_id=?",Long.class,block.id()));
        ok(api("POST","/preparation-batches/"+batch+"/withdraw",Map.of("version",1,"action","WITHDRAW"),one,"withdraw-original-notice"));apply(batch,two,"later-block-applicant");jdbc.update("DELETE FROM inbox");jdbc.update("DELETE FROM notification_outbox");
        revoke(admin,block.id(),"restore-both-applicants");assertEquals(List.of(1L,2L),jdbc.queryForList("SELECT recipient_id FROM notification_outbox WHERE event_key=? ORDER BY recipient_id",Long.class,"block:"+block.id()+":revoked"));assertNotEquals("0".repeat(64),jdbc.queryForObject("SELECT impact_hash FROM block_history WHERE block_id=? AND action='REVOKED'",String.class,block.id()));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM preparation_batch WHERE id=?",String.class,batch));
    }
    @Test void secondRestoreNotificationFailureRollsBackSourceAndWholeRecipientSet() throws Exception {
        var admin=login("admin1");long batch=openBatch(admin);apply(batch,login("student1"),"first-restore-applicant");var block=create(admin,seal(admin,plan(2100,start,end),"CANCEL",null),"restore-fault-source");ok(block);apply(batch,login("student2"),"second-restore-applicant");var count=new java.util.concurrent.atomic.AtomicInteger();
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).endsWith(":revoked")&&count.incrementAndGet()==2)throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_SECOND_RESTORE_NOTICE");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {assertEquals(503,api("POST","/admin/space-blocks/"+block.id()+"/revoke",Map.of("version",1,"reason","完整恢复通知"),admin,"second-restore-fault").status());assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,block.id()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM block_history WHERE action='REVOKED'",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM notification_outbox WHERE event_key=?",Integer.class,"block:"+block.id()+":revoked"));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM idempotency_receipt WHERE request_key='second-restore-fault'",Integer.class));}
        finally {org.mockito.Mockito.doCallRealMethod().when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());}
        ok(api("POST","/admin/space-blocks/"+block.id()+"/revoke",Map.of("version",1,"reason","完整恢复通知"),admin,"second-restore-fault"));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM notification_outbox WHERE event_key=?",Integer.class,"block:"+block.id()+":revoked"));
    }
    @Test void movedTargetDeactivationCannotEraseOriginalReceipt() throws Exception {
        var admin=login("admin1");shortSeat(login("student1"),2000,"before-target-deactivation");var body=seal(admin,plan(2000,start,end),"MOVE",5802L);var created=create(admin,body,"receipt-inactive-target");ok(created);jdbc.update("UPDATE space SET active=FALSE,version=version+1 WHERE id=5802");var replay=create(admin,body,"receipt-inactive-target");ok(replay);assertEquals(created.data(),replay.data());assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM short_relocation",Integer.class));
    }
    @Test void plannedCourseCrossingStartDuringWritesCannotCommit() throws Exception {
        var admin=login("admin1");long batch=openBatch(admin);apply(batch,login("student1"),"course-deadline-applicant");var body=plan(2100,start,end);body.put("kind","COURSE");seal(admin,body,"CANCEL",null);
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).startsWith("block:"))clock.value=Instant.parse(start);return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {error(create(admin,body,"course-crossed-start"),409,"LIMIT_WINDOW_STARTED");assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM block_recipient",Integer.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM notification_outbox WHERE event_key LIKE 'block:%'",Integer.class));}
        finally {org.mockito.Mockito.doCallRealMethod().when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());}
    }
    long[] poolEvent(String admin,String teacher) throws Exception {
        var venue=api("POST","/venue-requests",Map.of("spaceId",1001,"startsAt",start,"endsAt",end,"people",2,"purpose","阅读公开课","description","验收活动","contact","组织者"),teacher,"pool-event-venue");ok(venue);var p=plan(1001,start,end);p.put("kind","EVENT");p.put("venueRequestId",venue.id());p.put("venueVersion",1);var block=create(admin,seal(admin,p,"CANCEL",null),"pool-event-limit");ok(block);
        var event=api("POST","/organizer/events",Map.of("venueRequestId",venue.id(),"title","阅读公开课","eventType","CLASS","speaker","老师","description","活动说明","notice","准时参加","capacity",2,"opensAt","2026-10-10T00:00:00Z","closesAt","2026-10-10T02:15:00Z","promotionUntil","2026-10-10T02:25:00Z"),teacher,"pool-event-draft");ok(event);ok(api("POST","/organizer/events/"+event.id()+"/actions",Map.of("version",1,"action","PUBLISH","reason","场地与处置已成立"),teacher,"pool-event-publish"));return new long[]{block.id(),event.id(),venue.id()};
    }
    @Test void canceledEventRetainsPoolRecipientsAndRollsBackSecondRestoreNotice() throws Exception {
        var admin=login("admin1");var teacher=login("teacher1");long batch=openBatch(admin);apply(batch,login("student1"),"before-pool-event");var ids=poolEvent(admin,teacher);apply(batch,login("student2"),"after-pool-event");var count=new java.util.concurrent.atomic.AtomicInteger();var body=Map.of("version",2,"action","CANCEL","reason","恢复使用安排");
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).endsWith(":venue-closed")&&count.incrementAndGet()==2)throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_SECOND_VENUE_CLOSE_NOTICE");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {assertEquals(503,api("POST","/organizer/events/"+ids[1]+"/actions",body,teacher,"pool-event-cancel").status());assertEquals("PUBLISHED",jdbc.queryForObject("SELECT status FROM campus_event WHERE id=?",String.class,ids[1]));assertEquals("APPROVED",jdbc.queryForObject("SELECT status FROM venue_request WHERE id=?",String.class,ids[2]));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,ids[0]));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM venue_entitlement WHERE request_id=?",String.class,ids[2]));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM notification_outbox WHERE event_key=?",Integer.class,"block:"+ids[0]+":venue-closed"));}
        finally {org.mockito.Mockito.doCallRealMethod().when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());}
        var canceled=api("POST","/organizer/events/"+ids[1]+"/actions",body,teacher,"pool-event-cancel");ok(canceled);var replay=api("POST","/organizer/events/"+ids[1]+"/actions",body,teacher,"pool-event-cancel");ok(replay);assertEquals(canceled.data(),replay.data());assertEquals(List.of(1L,2L,3L),jdbc.queryForList("SELECT recipient_id FROM notification_outbox WHERE event_key=? ORDER BY recipient_id",Long.class,"block:"+ids[0]+":venue-closed"));assertNotEquals("0".repeat(64),jdbc.queryForObject("SELECT impact_hash FROM block_history WHERE block_id=? AND action='VENUE_CLOSED'",String.class,ids[0]));
    }
    @Test void eventCancelHoldsBatchBeforeWaitingForFloorSoApplicantCannotSlipIntoRestoreSet() throws Exception {
        var admin=login("admin1");var teacher=login("teacher1");long batch=openBatch(admin);apply(batch,login("student1"),"before-event-cancel-wait");var ids=poolEvent(admin,teacher);var locked=new CountDownLatch(1);var release=new CountDownLatch(1);var reachedFloor=new CountDownLatch(1);var pool=Executors.newFixedThreadPool(3);
        org.mockito.Mockito.doAnswer(inv->{reachedFloor.countDown();return inv.callRealMethod();}).when(business).floors(org.mockito.ArgumentMatchers.anyCollection());
        try {
            var guard=pool.submit(()->new org.springframework.transaction.support.TransactionTemplate(manager).execute(status->{jdbc.queryForList("SELECT id FROM floor WHERE id=100 FOR UPDATE");locked.countDown();try {assertTrue(release.await(10,TimeUnit.SECONDS));}catch(InterruptedException e) {throw new RuntimeException(e);}return null;}));assertTrue(locked.await(5,TimeUnit.SECONDS));
            var cancel=pool.submit(()->api("POST","/organizer/events/"+ids[1]+"/actions",Map.of("version",2,"action","CANCEL","reason","锁后恢复"),teacher,"event-cancel-floor-wait"));assertTrue(reachedFloor.await(5,TimeUnit.SECONDS));
            assertThrows(org.springframework.dao.DataAccessException.class,()->new org.springframework.transaction.support.TransactionTemplate(manager).execute(status->jdbc.queryForList("SELECT id FROM preparation_batch WHERE id=? FOR UPDATE NOWAIT",batch)));
            String two=login("student2");var submit=pool.submit(()->api("POST","/preparation-batches/"+batch+"/application",Map.of("version",0,"preferences",List.of(Map.of("seatId",2100,"rank",1)),"keepWaitlist",true),two,"after-cancel-wait-apply"));release.countDown();guard.get(10,TimeUnit.SECONDS);ok(cancel.get(20,TimeUnit.SECONDS));ok(submit.get(20,TimeUnit.SECONDS));assertEquals(List.of(1L,3L),jdbc.queryForList("SELECT recipient_id FROM notification_outbox WHERE event_key=? ORDER BY recipient_id",Long.class,"block:"+ids[0]+":venue-closed"));assertEquals("SUBMITTED",jdbc.queryForObject("SELECT status FROM preparation_application WHERE batch_id=? AND user_id=2",String.class,batch));observations.put("batchLockObserved",true);
        } finally {release.countDown();pool.shutdownNow();org.mockito.Mockito.doCallRealMethod().when(business).floors(org.mockito.ArgumentMatchers.anyCollection());}
    }
    Reply report(String student,long space,String key) throws Exception {var r=api("POST","/feedback",Map.of("spaceId",space,"category","OUTLET","description","原始插座问题记录，须保留"),student,key);ok(r);return r;}
    Reply verify(String admin,Reply report,List<Map<String,Object>> facts,String key) throws Exception {var r=api("POST","/admin/feedback/"+report.id()+"/actions",Map.of("version",1,"action","VERIFY","reason","管理员现场核实","facts",facts),admin,key);ok(r);return r;}
    Reply repair(String admin,List<Reply> reports,String key) throws Exception {var r=api("POST","/admin/repairs",Map.of("reports",reports.stream().map(p->Map.of("id",p.id(),"version",p.data().path("version").asLong())).toList(),"description","核实问题的维修事项"),admin,key);ok(r);return r;}
    Reply repairAct(String admin,long id,long version,String action,Boolean verified,List<Map<String,Object>> facts,String key) throws Exception {var body=new LinkedHashMap<String,Object>(Map.of("version",version,"action",action,"reason","明确维修处理说明","assignee","维修人员"));if(verified!=null)body.put("verified",verified);if(facts!=null)body.put("facts",facts);return api("POST","/admin/repairs/"+id+"/actions",body,admin,key);}
    void work(String admin,long repair,long version,String prefix) throws Exception {ok(repairAct(admin,repair,version,"ASSIGN",null,null,prefix+"-assign"));ok(repairAct(admin,repair,version+1,"WORK_DONE",null,null,prefix+"-done"));}
    @Test void verifiedTemporaryFacilityInvalidatesOldAcknowledgementAndRejectsCurrentUnsafeTarget() throws Exception {
        var admin=login("admin1");var one=login("student1");var ids=longOffer(admin,one,false);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"facility-original-limit"));var old=api("GET","/long-offers/"+ids[1]+"/impact",null,one,null);ok(old);var output=jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class);verify(admin,report(login("student2"),5802,"report-temp-broken"),List.of(Map.of("key","outletCondition","value","BROKEN")),"verify-temp-broken");
        var current=api("GET","/long-offers/"+ids[1]+"/impact",null,one,null);ok(current);assertNotEquals(old.data().path("impactHash").asString(),current.data().path("impactHash").asString());error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT","impactHash",old.data().path("impactHash").asString()),one,"broken-old-ack"),409,"STALE_OFFER_IMPACT");error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT","impactHash",current.data().path("impactHash").asString()),one,"broken-current-ack"),409,"TEMPORARY_RESOURCE_CHANGED");assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM long_offer WHERE id=?",String.class,ids[1]));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM seat_entitlement",Integer.class));assertEquals(output,jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class));assertEquals(List.of(1L),jdbc.queryForList("SELECT recipient_id FROM notification_outbox WHERE event_key='space:5802:facts:2' ORDER BY recipient_id",Long.class));
    }
    @Test void originalFacilityUpdateNotifiesApplicantWithoutChangingFrozenResult() throws Exception {
        var admin=login("admin1");var one=login("student1");var ids=longOffer(admin,one,false);var input=jdbc.queryForObject("SELECT input_hash FROM frozen_input",String.class);var output=jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class);verify(admin,report(login("student2"),2100,"report-original-fact"),List.of(Map.of("key","quiet","value",false)),"verify-original-fact");error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT"),one,"changed-original-confirm"),409,"RESOURCE_CHANGED");assertEquals(input,jdbc.queryForObject("SELECT input_hash FROM frozen_input",String.class));assertEquals(output,jdbc.queryForObject("SELECT output_hash FROM allocation_result",String.class));assertEquals(List.of(1L),jdbc.queryForList("SELECT recipient_id FROM notification_outbox WHERE event_key='space:2100:facts:2' ORDER BY recipient_id",Long.class));
    }
    @Test void missingHistoricalFacilityRequirementsRemainUnknownInsteadOfInheritingNewProfile() throws Exception {
        var admin=login("admin1");var one=login("student1");var ids=longOffer(admin,one,false);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"legacy-controlled-limit"));jdbc.update("UPDATE long_temporary_arrangement SET required_features_json=NULL");var impact=api("GET","/long-offers/"+ids[1]+"/impact",null,one,null);ok(impact);error(api("POST","/long-offers/"+ids[1]+"/actions",Map.of("version",1,"action","ACCEPT","impactHash",impact.data().path("impactHash").asString()),one,"legacy-unknown-ack"),409,"TEMPORARY_FACTS_UNPROVEN");assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM long_offer WHERE id=?",String.class,ids[1]));observations.put("legacySetup","CONTROLLED_NULL_HISTORY_NOT_MIGRATION_QUALIFICATION");
    }
    @Test void reducingOriginalProfileCannotEraseExistingTemporaryRequirements() throws Exception {
        var admin=login("admin1");var one=login("student1");longOffer(admin,one,true);ok(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"fixed-facility-limit"));var two=login("student2");verify(admin,report(two,2100,"changed-origin-quiet"),List.of(Map.of("key","quiet","value",false)),"verified-origin-quiet");verify(admin,report(two,5802,"changed-target-quiet"),List.of(Map.of("key","quiet","value",false)),"verified-target-quiet");
        error(create(admin,seal(admin,plan(2100,start,end),"TEMPORARY",5802L),"cannot-relax-old-requirement"),409,"TEMPORARY_RESOURCE_CHANGED");assertEquals("true",jdbc.queryForObject("SELECT JSON_UNQUOTE(JSON_EXTRACT(required_features_json,'$.quiet')) FROM long_temporary_arrangement",String.class));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM space_block",Integer.class));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM seat_entitlement",String.class));
    }
    @Test void repairVerificationReleasesOnlyOwnSourceAfterFailedAttempt() throws Exception {
        var admin=login("admin1");var feedback=verify(admin,report(login("student1"),5802,"repair-source-report"),List.of(),"repair-source-verify");var ticket=repair(admin,List.of(feedback),"repair-source-ticket");var own=create(admin,seal(admin,plan(5802,start,end),"CANCEL",null),"repair-owned-source");ok(own);var other=create(admin,seal(admin,plan(5802,start,end),"CANCEL",null),"repair-other-source");ok(other);ok(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",own.id(),"blockVersion",1,"reason","仅负责此来源"),admin,"repair-source-link"));work(admin,ticket.id(),2,"repair-first-work");assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,own.id()));ok(repairAct(admin,ticket.id(),4,"VERIFY",false,null,"repair-failed-verify"));assertEquals("OPEN",jdbc.queryForObject("SELECT status FROM repair_ticket WHERE id=?",String.class,ticket.id()));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,own.id()));work(admin,ticket.id(),5,"repair-second-work");ok(repairAct(admin,ticket.id(),7,"VERIFY",true,List.of(Map.of("key","outletCondition","value","WORKING")),"repair-passed-verify"));assertEquals("REVOKED",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,own.id()));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,other.id()));assertFalse(available(5802,start,end));assertEquals("RESOLVED",jdbc.queryForObject("SELECT status FROM feedback_report WHERE id=?",String.class,feedback.id()));assertEquals("原始插座问题记录，须保留",jdbc.queryForObject("SELECT description FROM feedback_report WHERE id=?",String.class,feedback.id()));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM repair_history WHERE action='VERIFICATION_FAILED'",Integer.class));
    }
    @Test void secondRepairRestoreNoticeRollsBackFactsReportsSourceAndReceipt() throws Exception {
        var admin=login("admin1");var one=login("student1");var two=login("student2");long batch=openBatch(admin);apply(batch,one,"repair-fault-applicant1");apply(batch,two,"repair-fault-applicant2");var block=create(admin,seal(admin,plan(2100,start,end),"CANCEL",null),"repair-fault-limit");ok(block);var a=verify(admin,report(one,2100,"repair-fault-report1"),List.of(),"repair-fault-verify1");var z=verify(admin,report(two,2100,"repair-fault-report2"),List.of(),"repair-fault-verify2");var ticket=repair(admin,List.of(a,z),"repair-fault-ticket");ok(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",block.id(),"blockVersion",1,"reason","维修来源"),admin,"repair-fault-link"));work(admin,ticket.id(),2,"repair-fault-work");var count=new java.util.concurrent.atomic.AtomicInteger();
        org.mockito.Mockito.doAnswer(inv->{if(inv.<String>getArgument(1).endsWith(":revoked")&&count.incrementAndGet()==2)throw new org.springframework.dao.DataAccessResourceFailureException("CONTROLLED_SECOND_REPAIR_RESTORE");return inv.callRealMethod();}).when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());
        try {assertEquals(503,repairAct(admin,ticket.id(),4,"VERIFY",true,List.of(Map.of("key","outletCondition","value","WORKING")),"repair-fault-final").status());assertEquals("WORK_DONE",jdbc.queryForObject("SELECT status FROM repair_ticket WHERE id=?",String.class,ticket.id()));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM feedback_report WHERE status='IN_REPAIR'",Integer.class));assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,block.id()));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM space_fact",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT version FROM space WHERE id=2100",Long.class));assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM idempotency_receipt WHERE request_key='repair-fault-final'",Integer.class));var fault=new LinkedHashMap<String,Object>();M4Measurements.collect(jdbc,fault);fault.put("facts",jdbc.queryForObject("SELECT COUNT(*) FROM space_fact",Long.class));fault.put("receipts",jdbc.queryForObject("SELECT COUNT(*) FROM idempotency_receipt WHERE request_key='repair-fault-final'",Long.class));observations.put("fault",fault);}
        finally {org.mockito.Mockito.doCallRealMethod().when(business).notify(org.mockito.ArgumentMatchers.anyLong(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyString(),org.mockito.ArgumentMatchers.anyLong());}
        ok(repairAct(admin,ticket.id(),4,"VERIFY",true,List.of(Map.of("key","outletCondition","value","WORKING")),"repair-fault-final"));assertEquals("VERIFIED_CLOSED",jdbc.queryForObject("SELECT status FROM repair_ticket WHERE id=?",String.class,ticket.id()));assertEquals(2,jdbc.queryForObject("SELECT COUNT(*) FROM feedback_report WHERE status='RESOLVED'",Integer.class));
    }
    @Test void endedRawActiveLimitCannotBecomeANewRepairSource() throws Exception {
        var admin=login("admin1");var feedback=verify(admin,report(login("student1"),5802,"ended-source-report"),List.of(),"ended-source-verify");var ticket=repair(admin,List.of(feedback),"ended-source-ticket");
        var block=create(admin,seal(admin,plan(5802,start,end),"CANCEL",null),"ended-repair-block");ok(block);clock.value=Instant.parse(end);
        assertEquals("ACTIVE",jdbc.queryForObject("SELECT status FROM space_block WHERE id=?",String.class,block.id()));
        error(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",block.id(),"blockVersion",1,"reason","不能复活已结束限制"),admin,"ended-repair-link"),409,"REPAIR_LIMIT_INVALID");
        assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM repair_limit",Integer.class));assertEquals(1,jdbc.queryForObject("SELECT version FROM repair_ticket WHERE id=?",Long.class,ticket.id()));assertTrue(available(5802,end,"2026-10-10T04:00:00Z"));
    }
    @Test void repairCannotLinkWrongSpaceOrCourseOrReplaceItsSource() throws Exception {
        var admin=login("admin1");var feedback=verify(admin,report(login("student1"),5802,"wrong-source-report"),List.of(),"wrong-source-verify");var ticket=repair(admin,List.of(feedback),"wrong-source-ticket");var other=create(admin,seal(admin,plan(5803,start,end),"CANCEL",null),"wrong-space-limit");ok(other);error(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",other.id(),"blockVersion",1,"reason","不能错关联"),admin,"wrong-source-link"),409,"REPAIR_LIMIT_INVALID");var p=plan(5802,start,end);p.put("kind","COURSE");var course=create(admin,seal(admin,p,"CANCEL",null),"course-not-repair");ok(course);error(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",course.id(),"blockVersion",1,"reason","课程不是维修来源"),admin,"course-source-link"),409,"REPAIR_LIMIT_INVALID");revoke(admin,course.id(),"course-ended-before-repair");var own=create(admin,seal(admin,plan(5802,start,end),"CANCEL",null),"valid-repair-source");ok(own);error(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",own.id(),"blockVersion",1,"reason","越界不可关联"),login("admin2"),"out-of-scope-source"),403,"SCOPE_FORBIDDEN");var link=api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",1,"blockId",own.id(),"blockVersion",1,"reason","维修关联"),admin,"right-source-link");ok(link);error(api("POST","/admin/repairs/"+ticket.id()+"/limits",Map.of("version",2,"blockId",own.id(),"blockVersion",1,"reason","不能重新关联"),admin,"duplicate-source-link"),409,"REPAIR_LIMIT_ALREADY_LINKED");assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM repair_limit",Integer.class));
    }
}
