-- A batch, an immutable calculation and a person's entitlement are different facts.
CREATE TABLE preparation_batch (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 public_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL UNIQUE,
 owner_id BIGINT NOT NULL,
 title VARCHAR(100) NOT NULL,
 purpose VARCHAR(16) NOT NULL,
 status VARCHAR(24) NOT NULL DEFAULT 'OPEN',
 cycle_starts_at DATETIME(6) NOT NULL,
 cycle_ends_at DATETIME(6) NOT NULL,
 opens_at DATETIME(6) NOT NULL,
 closes_at DATETIME(6) NOT NULL,
 freeze_deadline DATETIME(6) NOT NULL,
 random_at DATETIME(6) NOT NULL,
 result_deadline DATETIME(6) NOT NULL,
 confirmation_deadline DATETIME(6) NOT NULL,
 promotion_until DATETIME(6) NOT NULL,
 promotion_seconds INT NOT NULL,
 algorithm VARCHAR(64) NOT NULL,
 source_chain CHAR(64) CHARACTER SET ascii NOT NULL,
 source_round BIGINT NOT NULL,
 failure_reason VARCHAR(80) NULL,
 published_at DATETIME(6) NULL,
 created_at DATETIME(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 1,
 FOREIGN KEY(owner_id) REFERENCES identity_user(id),
 INDEX ix_batch_tasks(status,closes_at,result_deadline),
 CHECK (purpose IN ('POSTGRADUATE','CIVIL_SERVICE','OTHER')),
 CHECK (status IN ('OPEN','FROZEN','RESULT_PUBLISHED','FAILED_NO_RESULT','CANCELED','CLOSED')),
 CHECK (opens_at < closes_at AND closes_at < freeze_deadline AND freeze_deadline < random_at AND random_at < result_deadline),
 CHECK (result_deadline < confirmation_deadline AND confirmation_deadline <= cycle_starts_at AND cycle_starts_at < cycle_ends_at),
 CHECK (confirmation_deadline < promotion_until AND promotion_until <= cycle_ends_at),
 CHECK (promotion_seconds BETWEEN 60 AND 86400 AND source_round > 0)
) ENGINE=InnoDB;
CREATE TABLE preparation_pool (
 batch_id BIGINT NOT NULL,
 space_id BIGINT NOT NULL,
 floor_id BIGINT NOT NULL,
 space_version BIGINT NOT NULL,
 PRIMARY KEY(batch_id,space_id),
 FOREIGN KEY(batch_id) REFERENCES preparation_batch(id),
 FOREIGN KEY(space_id,floor_id) REFERENCES space(id,floor_id),
 INDEX ix_pool_space(space_id,batch_id)
) ENGINE=InnoDB;
CREATE TABLE preparation_application (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 batch_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 anonymous_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 current_version INT NOT NULL,
 frozen_version INT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'SUBMITTED',
 reason VARCHAR(80) NULL,
 created_at DATETIME(6) NOT NULL,
 UNIQUE KEY uq_application_actor(batch_id,user_id),
 UNIQUE KEY uq_application_anon(batch_id,anonymous_id),
 UNIQUE KEY uq_application_batch(id,batch_id),
 FOREIGN KEY(batch_id) REFERENCES preparation_batch(id),
 FOREIGN KEY(user_id) REFERENCES identity_user(id),
 INDEX ix_application_person(user_id,status,batch_id),
 CHECK (current_version > 0 AND (frozen_version IS NULL OR frozen_version > 0)),
 CHECK (status IN ('SUBMITTED','WITHDRAWN','EXCLUDED'))
) ENGINE=InnoDB;
CREATE TABLE application_version (
 application_id BIGINT NOT NULL,
 revision INT NOT NULL,
 accepted_at DATETIME(6) NOT NULL,
 preferences_json JSON NOT NULL,
 keep_waitlist BOOLEAN NOT NULL,
 PRIMARY KEY(application_id,revision),
 FOREIGN KEY(application_id) REFERENCES preparation_application(id),
 CHECK (revision > 0)
) ENGINE=InnoDB;
CREATE TABLE frozen_input (
 batch_id BIGINT PRIMARY KEY,
 input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 input_bytes MEDIUMTEXT NOT NULL,
 frozen_at DATETIME(6) NOT NULL,
 UNIQUE KEY uq_frozen_hash(batch_id,input_hash),
 FOREIGN KEY(batch_id) REFERENCES preparation_batch(id)
) ENGINE=InnoDB;
CREATE TABLE frozen_person (
 batch_id BIGINT NOT NULL,
 anonymous_id CHAR(36) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 application_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 revision INT NOT NULL,
 PRIMARY KEY(batch_id,anonymous_id),
 UNIQUE KEY uq_frozen_application(batch_id,application_id),
 UNIQUE KEY uq_frozen_user(batch_id,user_id),
 FOREIGN KEY(batch_id) REFERENCES frozen_input(batch_id),
 FOREIGN KEY(application_id,batch_id) REFERENCES preparation_application(id,batch_id),
 FOREIGN KEY(application_id,revision) REFERENCES application_version(application_id,revision),
 FOREIGN KEY(user_id) REFERENCES identity_user(id)
) ENGINE=InnoDB;
CREATE TABLE allocation_run (
 batch_id BIGINT PRIMARY KEY,
 input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 output_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 proof_json JSON NOT NULL,
 output_json JSON NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'CANDIDATE',
 created_at DATETIME(6) NOT NULL,
 UNIQUE KEY uq_run_output(batch_id,output_hash),
 FOREIGN KEY(batch_id,input_hash) REFERENCES frozen_input(batch_id,input_hash),
 CHECK (status IN ('CANDIDATE','PUBLISHED'))
) ENGINE=InnoDB;
CREATE TABLE allocation_result (
 batch_id BIGINT PRIMARY KEY,
 input_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 output_hash CHAR(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
 maximum_count INT NOT NULL,
 candidate_count INT NOT NULL,
 published_at DATETIME(6) NOT NULL,
 FOREIGN KEY(batch_id,input_hash) REFERENCES frozen_input(batch_id,input_hash),
 FOREIGN KEY(batch_id,output_hash) REFERENCES allocation_run(batch_id,output_hash),
 CHECK (maximum_count >= 0 AND maximum_count <= candidate_count)
) ENGINE=InnoDB;
CREATE TABLE allocation_outcome (
 batch_id BIGINT NOT NULL,
 application_id BIGINT NOT NULL,
 lottery_position INT NOT NULL,
 space_id BIGINT NULL,
 floor_id BIGINT NULL,
 preference_rank INT NULL,
 reason VARCHAR(40) NOT NULL,
 PRIMARY KEY(batch_id,application_id),
 UNIQUE KEY uq_outcome_position(batch_id,lottery_position),
 FOREIGN KEY(batch_id) REFERENCES allocation_result(batch_id),
 FOREIGN KEY(application_id,batch_id) REFERENCES preparation_application(id,batch_id),
 FOREIGN KEY(space_id,floor_id) REFERENCES space(id,floor_id),
 CHECK (lottery_position > 0),
 CHECK ((space_id IS NULL AND floor_id IS NULL AND preference_rank IS NULL) OR (space_id IS NOT NULL AND floor_id IS NOT NULL AND preference_rank BETWEEN 1 AND 3))
) ENGINE=InnoDB;
CREATE TABLE long_offer (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 batch_id BIGINT NOT NULL,
 application_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 space_id BIGINT NOT NULL,
 floor_id BIGINT NOT NULL,
 preference_rank INT NOT NULL,
 deadline DATETIME(6) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'OPEN',
 upgrade_from_id BIGINT NULL,
 created_at DATETIME(6) NOT NULL,
 version BIGINT NOT NULL DEFAULT 1,
 open_space_id BIGINT GENERATED ALWAYS AS (CASE WHEN status='OPEN' THEN space_id ELSE NULL END) STORED,
 open_user_id BIGINT GENERATED ALWAYS AS (CASE WHEN status='OPEN' THEN user_id ELSE NULL END) STORED,
 UNIQUE KEY uq_open_offer_space(batch_id,open_space_id),
 UNIQUE KEY uq_open_offer_user(batch_id,open_user_id),
 UNIQUE KEY uq_offer_coordinates(id,batch_id,user_id,space_id,floor_id),
 FOREIGN KEY(batch_id) REFERENCES allocation_result(batch_id),
 FOREIGN KEY(application_id,batch_id) REFERENCES preparation_application(id,batch_id),
 FOREIGN KEY(user_id) REFERENCES identity_user(id),
 FOREIGN KEY(space_id,floor_id) REFERENCES space(id,floor_id),
 INDEX ix_offer_deadline(batch_id,status,deadline),
 CHECK (preference_rank BETWEEN 1 AND 3),
 CHECK (status IN ('OPEN','ACCEPTED','DECLINED','EXPIRED','CANCELED','INVALID'))
) ENGINE=InnoDB;
CREATE TABLE seat_entitlement (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 offer_id BIGINT NOT NULL UNIQUE,
 batch_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 space_id BIGINT NOT NULL,
 floor_id BIGINT NOT NULL,
 starts_at DATETIME(6) NOT NULL,
 ends_at DATETIME(6) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
 closed_at DATETIME(6) NULL,
 version BIGINT NOT NULL DEFAULT 1,
 active_space_id BIGINT GENERATED ALWAYS AS (CASE WHEN status='ACTIVE' THEN space_id ELSE NULL END) STORED,
 active_user_id BIGINT GENERATED ALWAYS AS (CASE WHEN status='ACTIVE' THEN user_id ELSE NULL END) STORED,
 UNIQUE KEY uq_active_long_space(batch_id,active_space_id),
 UNIQUE KEY uq_active_long_user(batch_id,active_user_id),
 FOREIGN KEY(offer_id,batch_id,user_id,space_id,floor_id) REFERENCES long_offer(id,batch_id,user_id,space_id,floor_id),
 FOREIGN KEY(batch_id) REFERENCES allocation_result(batch_id),
 FOREIGN KEY(user_id) REFERENCES identity_user(id),
 FOREIGN KEY(space_id,floor_id) REFERENCES space(id,floor_id),
 INDEX ix_long_person(user_id,status,starts_at,ends_at),
 INDEX ix_long_space(floor_id,space_id,status,starts_at,ends_at),
 CHECK (starts_at < ends_at),
 CHECK (status IN ('ACTIVE','RELINQUISHED','REPLACED','EXPIRED','REVOKED'))
) ENGINE=InnoDB;
ALTER TABLE long_offer ADD CONSTRAINT fk_offer_upgrade FOREIGN KEY(upgrade_from_id) REFERENCES seat_entitlement(id);
CREATE TABLE waitlist_entry (
 batch_id BIGINT NOT NULL,
 application_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 lottery_position INT NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
 version BIGINT NOT NULL DEFAULT 1,
 PRIMARY KEY(batch_id,user_id),
 UNIQUE KEY uq_waitlist_application(batch_id,application_id),
 UNIQUE KEY uq_waitlist_position(batch_id,lottery_position),
 FOREIGN KEY(batch_id) REFERENCES allocation_result(batch_id),
 FOREIGN KEY(application_id,batch_id) REFERENCES preparation_application(id,batch_id),
 FOREIGN KEY(user_id) REFERENCES identity_user(id),
 CHECK (lottery_position > 0 AND status IN ('ACTIVE','EXITED','FINISHED'))
) ENGINE=InnoDB;
CREATE TABLE allocation_event (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 batch_id BIGINT NOT NULL,
 user_id BIGINT NULL,
 actor_id BIGINT NULL,
 action VARCHAR(40) NOT NULL,
 detail_json JSON NOT NULL,
 created_at DATETIME(6) NOT NULL,
 FOREIGN KEY(batch_id) REFERENCES preparation_batch(id),
 FOREIGN KEY(user_id) REFERENCES identity_user(id),
 FOREIGN KEY(actor_id) REFERENCES identity_user(id),
 INDEX ix_allocation_history(batch_id,user_id,created_at)
) ENGINE=InnoDB;
