ALTER TABLE seat_entitlement ADD UNIQUE KEY uq_entitlement_coordinates(id,batch_id,user_id,space_id,floor_id);
CREATE TABLE governance_case (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 entitlement_id BIGINT NOT NULL,
 batch_id BIGINT NOT NULL,
 user_id BIGINT NOT NULL,
 space_id BIGINT NOT NULL,
 floor_id BIGINT NOT NULL,
 entitlement_version BIGINT NOT NULL,
 reason_code VARCHAR(40) NOT NULL,
 evidence TEXT NOT NULL,
 opened_by BIGINT NOT NULL,
 opened_at DATETIME(6) NOT NULL,
 statement_until DATETIME(6) NOT NULL,
 status VARCHAR(32) NOT NULL DEFAULT 'NOTICE',
 decided_by BIGINT NULL,
 decided_at DATETIME(6) NULL,
 decision_reason VARCHAR(1500) NULL,
 revoked_version BIGINT NULL,
 appeal_until DATETIME(6) NULL,
 appealed_at DATETIME(6) NULL,
 appeal_reason VARCHAR(3000) NULL,
 reviewed_by BIGINT NULL,
 reviewed_at DATETIME(6) NULL,
 review_reason VARCHAR(1500) NULL,
 restoration_reason VARCHAR(100) NULL,
 version BIGINT NOT NULL DEFAULT 1,
 open_entitlement_id BIGINT GENERATED ALWAYS AS (CASE WHEN status IN ('NOTICE','APPEALED') THEN entitlement_id ELSE NULL END) STORED,
 UNIQUE KEY uq_open_governance_case(open_entitlement_id),
 FOREIGN KEY(entitlement_id,batch_id,user_id,space_id,floor_id) REFERENCES seat_entitlement(id,batch_id,user_id,space_id,floor_id),
 FOREIGN KEY(opened_by) REFERENCES identity_user(id),
 FOREIGN KEY(decided_by) REFERENCES identity_user(id),
 FOREIGN KEY(reviewed_by) REFERENCES identity_user(id),
 INDEX ix_governance_owner(user_id,id),
 INDEX ix_governance_scope(floor_id,status,id),
 CHECK (statement_until > opened_at),
 CHECK (reason_code IN ('FALSE_DECLARATION','UNAUTHORIZED_TRANSFER','PERSISTENT_OBSTRUCTION','EXPLICIT_RULE_VIOLATION')),
 CHECK (status IN ('NOTICE','DISMISSED','REVOKED','APPEALED','UPHELD','RESTORED','CORRECTED_UNAVAILABLE'))
) ENGINE=InnoDB;
CREATE TABLE governance_history (
 id BIGINT PRIMARY KEY AUTO_INCREMENT,
 case_id BIGINT NOT NULL,
 actor_id BIGINT NOT NULL,
 action VARCHAR(40) NOT NULL,
 message TEXT NOT NULL,
 created_at DATETIME(6) NOT NULL,
 FOREIGN KEY(case_id) REFERENCES governance_case(id),
 FOREIGN KEY(actor_id) REFERENCES identity_user(id),
 INDEX ix_governance_history(case_id,id)
) ENGINE=InnoDB;
CREATE TABLE long_application_penalty (
 case_id BIGINT PRIMARY KEY,
 user_id BIGINT NOT NULL,
 starts_at DATETIME(6) NOT NULL,
 ends_at DATETIME(6) NOT NULL,
 status VARCHAR(16) NOT NULL DEFAULT 'ACTIVE',
 revoked_at DATETIME(6) NULL,
 FOREIGN KEY(case_id) REFERENCES governance_case(id),
 FOREIGN KEY(user_id) REFERENCES identity_user(id),
 INDEX ix_current_long_penalty(user_id,status,starts_at,ends_at),
 CHECK (starts_at < ends_at),
 CHECK (status IN ('ACTIVE','OVERTURNED'))
) ENGINE=InnoDB;
