<script setup lang="ts">
import {computed,reactive,ref,watch,nextTick,onBeforeUnmount} from 'vue';
import {RouterLink,useRoute,useRouter} from 'vue-router';
import {PhArrowLeft,PhArrowClockwise} from '@phosphor-icons/vue';
import {ApiError,StaleResponse,factLabel,factValueLabel,label,formatTime,businessTime,localDateTime,type Row,type Page,type Space,type Floor} from '@qixu/client';
import {api,auth,client,errorMessage} from '../runtime';
const props=defineProps<{section:string;id:number}>();const route=useRoute(),router=useRouter();
const items=ref<Row[]>([]),data=ref<Row>({}),aux=ref<Row[]>([]),spaces=ref<Space[]>([]),rights=ref<Row[]>([]),page=ref(Number(route.query.page)||1),total=ref(0),error=ref(''),message=ref(''),loading=ref(false),busy=ref(false),preview=ref<Row|null>(null),choices=reactive<Record<string,Row>>({});let revision=0;let operation=0;const images=ref<{id:number;url:string}[]>([]),photoError=ref('');
const form=reactive<Row>({reportRefs:[],spaceId:Number(route.query.space)||0,startsAt:'',endsAt:'',people:1,purpose:'',description:'',contact:'',reason:'',title:'',speaker:'',notice:'',capacity:1,venueRequestId:0,eventType:'READING',opensAt:'',closesAt:'',promotionUntil:'',freezeDeadline:'',randomAt:'',resultDeadline:'',confirmationDeadline:'',promotionSeconds:3600,batchPurpose:'POSTGRADUATE',kind:'MAINTENANCE',venueVersion:1,seatIds:[],facts:[],factKey:'outletCondition',factValue:'BROKEN',assignee:'',verified:false,blockId:0,blockVersion:1,entitlementId:0,entitlementVersion:1,reasonCode:'EXPLICIT_RULE_VIOLATION',statementUntil:'',penaltyUntil:''});
const isAdmin=computed(()=>auth.session?.actor.role==='ADMIN');
const errorAlert=ref<HTMLElement|null>(null);
watch(error,async value=>{if(!value)return;await nextTick();if(error.value!==value)return;errorAlert.value?.focus({preventScroll:true});errorAlert.value?.scrollIntoView({block:'center',behavior:'auto'});});
const administrative=computed(()=>['batches','blocks','feedback','repairs','governance','operations','audit'].includes(props.section));
const fieldNames:Record<string,string>={startsAt:'使用开始',endsAt:'使用结束',opensAt:'申请/预约开放',closesAt:'申请/预约截止',promotionUntil:'递补停止',freezeDeadline:'冻结最迟时间',randomAt:'未来随机源时刻',resultDeadline:'结果最迟公布',confirmationDeadline:'首次确认截止',statementUntil:'陈述截止（至少24小时）'};
const batchTimes=['opensAt','closesAt','freezeDeadline','randomAt','resultDeadline','confirmationDeadline','startsAt','endsAt','promotionUntil'];
function date(field:string){return businessTime(String(form[field]));}
function clearImages(){for(const image of images.value)URL.revokeObjectURL(image.url);images.value=[];photoError.value='';}
function normalized(row:Row,venues:Row[]=[]):Row{const venue=venues.find(v=>v.id===row.venue_request_id);return {...row,space_id:row.space_id??row.spaceId,code:row.code??venue?.code,name:row.name??venue?.name,starts_at:row.starts_at??row.startsAt,ends_at:row.ends_at??row.endsAt,closes_at:row.closes_at??row.registration_closes_at,effectivePhase:row.effectivePhase??row.phase};}
function related(row:Row){return row.code||row.space_id||row.entity_type||(props.section==='batches'?'批次资源池':'未关联');}
async function loadImages(run:number){for(const a of (data.value.attachments||[]).slice(0,6)){try{const r=await client.get<{tempFilePath:string}>('/api/v1/feedback/'+props.id+'/attachments/'+a.id,'admin-photo-'+a.id,'FILE');if(run!==revision){URL.revokeObjectURL(r.tempFilePath);return;}images.value.push({id:a.id,url:r.tempFilePath});}catch(e){if(run===revision&&!(e instanceof StaleResponse))photoError.value=errorMessage(e);}}}
async function loadSpaceChoices(run:number){const fs=await api<Floor[]>('/floors');const allowed=isAdmin.value?fs.filter(f=>(auth.session?.adminFloors||[]).includes(Number(f.id))):fs;const result:Space[]=[];for(const f of allowed)for(let p=1;p<=40;p++){if(run!==revision)return;const r=await api<Page<Space>>('/spaces?floor='+f.id+'&page='+p,'chooser-'+f.id);result.push(...r.items);if(result.length>2000)throw new ApiError(503,'CHOOSER_TOO_LARGE','空间较多，请从地图选择具体楼层和空间。');if(p*50>=r.total)break;}if(run===revision)spaces.value=result;}
async function load(){const run=++revision;clearImages();loading.value=true;error.value='';try{
 if(administrative.value&&!isAdmin.value)throw new ApiError(403,'ADMIN_REQUIRED','此入口只向有范围的空间管理员开放。');
 let r:Row|Row[]={},extra:Row[]=[];
 if(props.section==='venues')r=await api(props.id?'/venue-requests/'+props.id:isAdmin.value?'/admin/venue-requests':'/venue-requests');
 else if(props.section==='events'){r=await api(props.id?'/events/'+props.id:'/organizer/events');extra=await api<Row[]>('/venue-requests');}
 else if(props.section==='batches'){r=await api(props.id?'/preparation-batches/'+props.id:'/preparation-batches');if(!props.id){const all:Space[]=[];for(const floor of auth.session?.adminFloors||[]){for(let p=1;p<=40;p++){if(run!==revision)return;const result=await api<Page<Space>>('/spaces?kind=SEAT&floor='+floor+'&page='+p,'pool-'+floor);all.push(...result.items.filter(s=>s.useMode==='PREPARATION'));if(p*50>=result.total)break;}}if(run===revision)spaces.value=all;}}
 else if(props.section==='blocks')r=await api(props.id?'/admin/space-blocks/'+props.id:'/admin/space-blocks?page='+page.value);
 else if(props.section==='feedback')r=await api(props.id?'/feedback/'+props.id:'/admin/feedback?page='+page.value);
 else if(props.section==='repairs')r=await api(props.id?'/admin/repairs/'+props.id:'/admin/repairs?page='+page.value);
 else if(props.section==='governance'){r=await api(props.id?'/governance-cases/'+props.id:'/admin/governance-cases?page='+page.value);if(!props.id){const rs=await api<Page<Row>>('/admin/long-entitlements?page='+page.value);if(run===revision)rights.value=rs.items;}}
 else if(props.section==='operations')r=await api('/admin/operations');
 else if(props.section==='audit')r=await api('/admin/audit?page='+page.value);
 else if(props.section==='inbox')r=await api('/inbox?page='+page.value+'&size=20');else throw new ApiError(404,'PAGE_NOT_FOUND','没有这个工作入口。');
 if(['venues','blocks'].includes(props.section)&&!props.id)await loadSpaceChoices(run);
 if(props.section==='repairs'&&props.id&&'space_id' in r){const feedback=await api<Page<Row>>('/admin/feedback');extra=feedback.items.filter(f=>f.space_id===(r as Row).space_id&&f.status==='VERIFIED');}
 if(run!==revision)return;aux.value=extra;if(Array.isArray(r)){items.value=r.map(row=>normalized(row,extra));total.value=r.length;}else if(Array.isArray(r.items)){items.value=r.items.map((row:Row)=>normalized(row,extra));total.value=r.total||r.items.length;data.value=r;}else data.value=normalized(r,extra);if(props.section==='feedback'&&props.id)await loadImages(run);
 }catch(e){if(run===revision&&!(e instanceof StaleResponse))error.value=errorMessage(e);}finally{if(run===revision)loading.value=false;}}
async function write(path:string,body:unknown,sensitive=false){if(busy.value)return;const run=revision,op=++operation;busy.value=true;error.value='';message.value='';try{const r=await client.mutate<Row>('/api/v1'+path,body,{sensitive});if(run!==revision)return r;message.value='已确认回执 '+r.receipt.key.slice(-8)+'。';await load();return r;}catch(e){if(run===revision&&op===operation&&!(e instanceof StaleResponse))error.value=errorMessage(e);}finally{if(op===operation)busy.value=false;}}
async function submit(kind:string){try{
 if(kind==='venue')await write('/venue-requests',{spaceId:Number(form.spaceId),startsAt:date('startsAt'),endsAt:date('endsAt'),people:Number(form.people),purpose:form.purpose,description:form.description,contact:form.contact},true);
 if(kind==='event')await write('/organizer/events',{venueRequestId:Number(form.venueRequestId),title:form.title,eventType:form.eventType,speaker:form.speaker,description:form.description,notice:form.notice,capacity:Number(form.capacity),opensAt:date('opensAt'),closesAt:date('closesAt'),promotionUntil:date('promotionUntil')});
 if(kind==='batch')await write('/preparation-batches',{title:form.title,purpose:form.batchPurpose,startsAt:date('startsAt'),endsAt:date('endsAt'),opensAt:date('opensAt'),closesAt:date('closesAt'),freezeDeadline:date('freezeDeadline'),randomAt:date('randomAt'),resultDeadline:date('resultDeadline'),confirmationDeadline:date('confirmationDeadline'),promotionUntil:date('promotionUntil'),promotionSeconds:Number(form.promotionSeconds),seatIds:form.seatIds});
 if(kind==='governance')await write('/admin/governance-cases',{entitlementId:Number(form.entitlementId),entitlementVersion:Number(form.entitlementVersion),reasonCode:form.reasonCode,evidence:form.description,statementUntil:date('statementUntil')},true);
 }catch(e){error.value=errorMessage(e);}}
async function action(name:string){const v=data.value.version;try{
 if(props.section==='venues')await write('/venue-requests/'+props.id+'/actions',{version:v,action:name,reason:form.reason});
 if(props.section==='events')await write('/organizer/events/'+props.id+'/actions',{version:v,action:name,reason:form.reason,...(name==='REBIND'?{venueRequestId:Number(form.venueRequestId)}:{})});
 if(props.section==='batches')await write('/preparation-batches/'+props.id+(['CANCEL','CANCEL_UNUSED'].includes(name)?'/cancel':'/actions'),{version:v,action:name,reason:form.reason});
 if(props.section==='blocks')await write('/admin/space-blocks/'+props.id+'/revoke',{version:v,reason:form.reason});
 if(props.section==='feedback'){if(name==='REPAIR')await write('/admin/repairs',{reports:[{id:props.id,version:v}],description:form.reason},true);else await write('/admin/feedback/'+props.id+'/actions',{version:v,action:name,reason:form.reason,facts:form.facts},true);}
 if(props.section==='repairs'){if(name==='LINK_LIMIT')await write('/admin/repairs/'+props.id+'/limits',{version:v,blockId:Number(form.blockId),blockVersion:Number(form.blockVersion),reason:form.reason},true);else await write('/admin/repairs/'+props.id+'/actions',{version:v,action:name,reason:form.reason,assignee:form.assignee,verified:form.verified,facts:form.facts,...(name==='LINK_REPORTS'?{reports:form.reportRefs}:{})},true);}
 if(props.section==='governance')await write('/admin/governance-cases/'+props.id+(name==='UPHOLD'||name==='OVERTURN'?'/reviews':'/decisions'),{version:v,action:name,reason:form.reason,...(form.penaltyUntil?{penaltyUntil:date('penaltyUntil')}:{})},true);
 }catch(e){error.value=errorMessage(e);}}
function plan(){const p:Row={spaceId:Number(form.spaceId),kind:form.kind,startsAt:date('startsAt'),endsAt:date('endsAt'),reason:form.reason,resolutions:Object.entries(choices).filter(([,c])=>c.action).map(([impactKey,c])=>({impactKey,action:c.action,...(c.target?{targetSpaceId:Number(c.target)}:{}),...(c.venue?{replacementVenueId:Number(c.venue)}:{})}))};if(form.kind==='EVENT'){p.venueRequestId=Number(form.venueRequestId);p.venueVersion=Number(form.venueVersion);}return p;}
async function previewBlock(){const run=revision;error.value='';try{const result=await client.observe<Row>('POST','/api/v1/admin/space-blocks/preview',plan(),'block-preview');if(run!==revision)return;preview.value=result;for(const i of result.impacts)if(i.needsResolution&&!choices[i.impactKey])choices[i.impactKey]={action:'',target:'',venue:''};}catch(e){if(run===revision&&!(e instanceof StaleResponse))error.value=errorMessage(e);}}
async function commitBlock(){const run=revision;try{if(!preview.value){error.value='须先预览完整影响。';return;}const p=plan();const fresh=await client.observe<Row>('POST','/api/v1/admin/space-blocks/preview',p,'block-preview');if(run!==revision)return;const expected=fresh.impacts.filter((i:Row)=>i.needsResolution).map((i:Row)=>i.impactKey).sort();const actual=p.resolutions.map((r:Row)=>r.impactKey).sort();preview.value=fresh;if(JSON.stringify(expected)!==JSON.stringify(actual)){error.value='影响已变化或处置未填写完整，请重新核对，不会提交。';return;}await write('/admin/space-blocks',{...p,impactHash:fresh.impactHash});}catch(e){if(run===revision&&!(e instanceof StaleResponse))error.value=errorMessage(e);}}
function choicesFor(kind:string){return kind==='SHORT'?['MOVE','CANCEL']:kind==='LONG'?['TEMPORARY','UNAVAILABLE']:kind==='VENUE'?['RELOCATE','CANCEL']:[];}
const booleanFact=computed(()=>['window','outlet','quiet','accessible'].includes(form.factKey));
const factValues=computed(()=>booleanFact.value?['true','false']:['UNKNOWN','WORKING','BROKEN','REPAIRING']);
watch(()=>form.factKey,()=>{form.factValue=booleanFact.value?'':'UNKNOWN';},{flush:'sync'});
function addFact(){if(!factValues.value.includes(form.factValue)){error.value=booleanFact.value?'请明确选择有或无；未知不能作为缺失事实提交。':'请选择有效设施状况。';return;}error.value='';form.facts=[...form.facts.filter((f:Row)=>f.key!==form.factKey),{key:form.factKey,value:booleanFact.value?form.factValue==='true':form.factValue}];}
function chooseRight(r:Row){form.entitlementId=r.id;form.entitlementVersion=r.version;}
function pageTo(next:number){router.replace({path:'/'+props.section,query:{...route.query,page:next}});}
function clearPrivate(){form.description='';form.contact='';form.reason='';form.facts=[];client.clearSensitive();}
onBeforeUnmount(()=>{revision++;operation++;clearImages();clearPrivate();});
watch(()=>[props.section,props.id,route.query.page,auth.generation],()=>{revision++;operation++;message.value='';error.value='';busy.value=false;clearImages();clearPrivate();page.value=Number(route.query.page)||1;data.value={};items.value=[];aux.value=[];rights.value=[];preview.value=null;form.reason='';form.description='';form.contact='';form.facts=[];for(const key of Object.keys(choices))delete choices[key];load();},{immediate:true,flush:'sync'});
watch(()=>[form.spaceId,form.startsAt,form.endsAt,form.kind,form.reason,form.venueRequestId,form.venueVersion],()=>{preview.value=null;});
</script>
<template>
<div v-if="error" ref="errorAlert" class="alert danger" role="alert" tabindex="-1">{{error}}<button @click="load">刷新事实（保留输入）</button></div><div v-if="message" class="alert">{{message}}</div><p v-if="loading" class="muted">正在读取…</p>
<template v-if="!administrative||isAdmin">
<div class="section-header"><RouterLink v-if="id" :to="{path:'/'+section,query:{...route.query,page}}" class="back-link"><PhArrowLeft :size="16"/>返回原列表</RouterLink><span v-else class="muted">{{section==='inbox'?'当前身份 ':total+'项 · 当前身份 '}}{{auth.session?.actor.displayName}}</span><button class="icon-button" aria-label="刷新当前事实" @click="load"><PhArrowClockwise :size="20"/></button></div>
<section v-if="section==='operations'" class="panel"><h2>授权事件投递概况</h2><div class="metric-grid"><div><strong>{{data.notifications?.total??'未知'}}</strong><span>持久事件</span></div><div><strong>{{data.notifications?.pending??'未知'}}</strong><span>等待站内投递</span></div><div><strong>{{data.notifications?.delivered??'未知'}}</strong><span>已持久到站内</span></div></div><p>最早等待 {{data.notifications?.oldest_pending_at?formatTime(data.notifications.oldest_pending_at):'无等待事件'}}</p><p class="muted">只统计当前范围能归属的已知业务实体。已投递不代表已读或外部微信送达；没有把未采集的重试次数当0。</p></section>
<section v-else-if="section==='inbox'" class="panel"><h2>我的站内通知</h2><p v-if="!loading&&!error&&typeof data.unread==='number'" class="muted">{{data.unread}}条未读 · 共{{total}}条</p><p v-else class="muted">未读数量尚未确认</p><p class="muted">站内通知是持久结果入口；投递不代表已读。</p><article v-for="n in items" :key="n.id" class="inbox-item"><h3>{{n.title}}<span class="badge">{{n.read_at?'已读':'未读'}}</span></h3><p>{{n.message}}</p><small>{{formatTime(n.created_at)}}</small><button v-if="!n.read_at" :disabled="busy||loading" @click="write('/inbox/'+n.id+'/read',{})">标为已读</button></article><p v-if="!items.length&&!loading&&!error" class="empty">没有站内消息。</p><div v-if="total>20&&!error&&typeof data.unread==='number'" class="pagination"><button :disabled="page<=1||loading||busy" @click="pageTo(page-1)">上一页</button><span>{{page}} / {{Math.ceil(total/20)}}</span><button :disabled="page*20>=total||loading||busy" @click="pageTo(page+1)">下一页</button></div></section>
<section v-else-if="!id" class="panel"><div class="section-header"><h2>{{{venues:'场地申请',events:'我组织的活动',batches:'公开长期批次',blocks:'空间限制',feedback:'待核实反馈',repairs:'维修事项',governance:'使用权处置',audit:'授权审计'}[section]}}</h2><div v-if="section==='feedback'" class="actions"><RouterLink to="/repairs">维修事项</RouterLink></div></div><div class="table-wrap"><table><thead><tr><th>编号/名称</th><th>状态/动作</th><th>关联空间/实体</th><th>时间/期限</th><th>操作</th></tr></thead><tbody><tr v-for="r in items" :key="r.id"><td>{{r.title||r.purpose||r.id}}</td><td><span class="badge">{{label(r.effectivePhase||r.status||r.action,section==='repairs'?'REPAIR':undefined)}}</span></td><td>{{related(r)}}</td><td>{{formatTime(r.statement_until||r.closes_at||r.starts_at||r.created_at)}}</td><td><RouterLink v-if="section!=='audit'" :to="{path:'/'+section+'/'+r.id,query:{...route.query,page}}">查看详情</RouterLink><small v-else>{{r.request_id}}</small></td></tr></tbody></table></div><p v-if="!items.length&&!loading&&!error" class="empty">当前授权范围没有记录。</p><div v-if="total>50" class="pagination"><button :disabled="page<=1" @click="pageTo(page-1)">上一页</button><span>{{page}} / {{Math.ceil(total/50)}}</span><button :disabled="page*50>=total" @click="pageTo(page+1)">下一页</button></div></section>
<section v-else-if="data.id" class="panel workflow-detail"><h2>{{data.title||data.purpose||'记录 '+data.id}} <span class="badge">{{label(data.effectivePhase||data.status,section==='repairs'?'REPAIR':undefined)}}</span></h2><dl><div v-if="data.space_id"><dt>空间</dt><dd>{{data.code||data.space_id}}</dd></div><div v-if="data.user_id"><dt>申请主体</dt><dd>{{data.user_id}}</dd></div><div v-if="data.version"><dt>当前版本</dt><dd>{{data.version}}</dd></div><div v-for="key in ['starts_at','ends_at','closes_at','result_deadline','confirmation_deadline','statement_until','appeal_until']" :key="key"><template v-if="data[key]"><dt>{{{starts_at:'开始',ends_at:'结束',closes_at:'申请截止',result_deadline:'结果最迟',confirmation_deadline:'确认截止',statement_until:'陈述截止',appeal_until:'申诉截止'}[key]}}</dt><dd>{{formatTime(data[key])}}</dd></template></div></dl><p v-if="data.description" class="preserve-text">{{data.description}}</p><p v-if="data.evidence" class="preserve-text">处理依据：{{data.evidence}}</p><p v-if="data.decision_note||data.decision_reason" class="alert">{{data.decision_note||data.decision_reason}}</p><p v-if="photoError" class="alert danger">照片未读取：{{photoError}}</p><div v-if="images.length" class="evidence-images"><img v-for="a in images" :key="a.id" :src="a.url" alt="受权限保护的反馈原图"/></div><div v-if="data.history?.length" class="history"><article v-for="(h,i) in data.history" :key="i"><strong>{{label(h.action)}} · {{formatTime(h.created_at)}}</strong><p>{{h.message||h.reason}}</p></article></div><section v-if="section==='feedback'&&data.repairs?.length" class="related-records"><h3>关联维修事项</h3><RouterLink v-for="repair in data.repairs" :key="repair.id" :to="'/repairs/'+repair.id">维修事项 {{repair.id}} · {{label(repair.status,'REPAIR')}}</RouterLink></section><label>处理说明<textarea v-model="form.reason" maxlength="1500" placeholder="明确事实、理由和影响；输入不会因409被清空"/></label>
 <div v-if="section==='venues'" class="actions"><button v-if="isAdmin&&data.status==='SUBMITTED'" class="primary" :disabled="busy" @click="action('APPROVE')">批准并建立空间权</button><button v-if="isAdmin&&data.status==='SUBMITTED'" :disabled="busy" @click="action('REJECT')">拒绝申请</button><button v-if="['SUBMITTED','APPROVED'].includes(data.status)" :disabled="busy" @click="action('CANCEL')">明确取消</button></div>
 <template v-if="section==='events'"><p>主讲人：{{data.speaker}} · 预约截止 {{formatTime(data.registration_closes_at)}} · 递补停止 {{formatTime(data.promotion_until)}}</p><p class="muted">剩余{{data.remaining}}/{{data.capacity}}；预约关系随合法换地保持。</p><label>换用本人已批准场地<select v-model="form.venueRequestId"><option :value="0">请选择</option><option v-for="v in aux.filter(v=>v.status==='APPROVED')" :key="v.id" :value="v.id">{{v.code||'空间 '+v.space_id}} · {{v.purpose}} · {{formatTime(v.starts_at)}}</option></select></label><div class="actions"><button v-if="data.status==='DRAFT'" class="primary" :disabled="busy" @click="action('PUBLISH')">场地核验后发布</button><button v-if="data.status!=='CANCELED'" :disabled="busy" @click="action('REBIND')">提交合法换地</button><button v-if="data.status!=='CANCELED'" :disabled="busy" @click="action('CANCEL')">取消活动并通知</button></div></template>
 <template v-if="section==='batches'"><p class="muted">算法{{data.algorithm}}；固定来源round{{data.source_round}}，时刻{{formatTime(data.random_at)}}。没有指定种子或中签者入口。</p><p v-if="data.failure_reason" class="alert danger">{{data.failure_reason}}</p><div v-if="data.result?.input_hash" class="proof-digests"><p>输入摘要 {{data.result.input_hash}}</p><p>输出摘要 {{data.result.output_hash}}</p><a :href="'/api/public/batches/'+data.public_id+'/verification'" target="_blank" rel="noopener">公开匿名复算材料</a></div><div class="actions"><button v-if="data.status==='OPEN'" :disabled="busy" @click="action('FREEZE')">到期冻结</button><button v-if="data.status==='FROZEN'" class="primary" :disabled="busy" @click="action('ALLOCATE')">取得固定来源并计算</button><button v-if="['OPEN','FROZEN','FAILED_NO_RESULT'].includes(data.status)" :disabled="busy" @click="action('CANCEL')">按合同取消轮次</button><button v-if="data.status==='RESULT_PUBLISHED'" :disabled="busy" @click="action('CANCEL_UNUSED')">核验无任何权历史后取消</button></div></template>
 <div v-if="section==='blocks'&&data.status==='ACTIVE'" class="actions"><button v-if="data.kind!=='EVENT'" :disabled="busy" @click="action('REVOKE')">只撤销本来源</button><p v-else class="muted">活动绑定限制通过活动/场地动作解除，不能绕过原业务。</p></div>
 <template v-if="['feedback','repairs'].includes(section)"><fieldset><legend>经核实的空间事实</legend><div class="inline-form"><select v-model="form.factKey"><option v-for="key in ['outletCondition','lightCondition','deskCondition','environmentCondition','outlet','window','quiet','accessible']" :key="key" :value="key">{{factLabel[key]}}</option></select><select v-model="form.factValue"><option v-if="booleanFact" value="" disabled>请选择有或无</option><option v-for="value in factValues" :key="value" :value="value">{{factValueLabel(value)}}</option></select><button @click="addFact">加入事实项</button></div><div v-for="f in form.facts" :key="f.key" class="fact-chip">{{factLabel[f.key]||f.key}} = {{factValueLabel(f.value)}}<button @click="form.facts=form.facts.filter((x:Row)=>x.key!==f.key)">移除</button></div><p class="muted">只提交亲自核实的事实；工作完成仍须复验，已知损坏的设施必须明确恢复正常。</p></fieldset><div v-if="section==='feedback'" class="actions"><button v-if="data.status==='REPORTED'" :disabled="busy" @click="action('ACKNOWLEDGE')">受理</button><button v-if="['REPORTED','ACKNOWLEDGED'].includes(data.status)" class="primary" :disabled="busy" @click="action('VERIFY')">核实事实</button><button v-if="['REPORTED','ACKNOWLEDGED'].includes(data.status)" :disabled="busy" @click="action('NOT_REPRODUCED')">未复现</button><button v-if="['REPORTED','ACKNOWLEDGED'].includes(data.status)" :disabled="busy" @click="action('REJECT')">驳回并说明</button><button v-if="data.status==='VERIFIED'" :disabled="busy" @click="action('REPAIR')">创建维修事项</button></div><template v-else><label>维修执行人<input v-model="form.assignee" maxlength="100"/></label><label class="check-label"><input v-model="form.verified" type="checkbox"/>明确复验通过（仍须填实际设施事实）</label><div class="actions"><button v-if="['OPEN','ASSIGNED'].includes(data.status)" :disabled="busy" @click="action('ASSIGN')">安排执行人</button><button v-if="data.status==='ASSIGNED'" :disabled="busy" @click="action('WORK_DONE')">记录工作完成</button><button v-if="data.status==='WORK_DONE'" class="primary" :disabled="busy" @click="action('VERIFY')">按事实复验</button></div><fieldset v-if="aux.length"><legend>关联最近50条反馈中的同空间已核实报告</legend><label v-for="r in aux" :key="r.id" class="check-label"><input v-model="form.reportRefs" type="checkbox" :value="{id:r.id,version:r.version}"/>反馈{{r.id}} · {{formatTime(r.updated_at)}}</label><button :disabled="busy||!form.reportRefs.length" @click="action('LINK_REPORTS')">关联所选报告</button></fieldset><div class="form-grid"><label>同空间安全/维护来源ID<input v-model="form.blockId" type="number" min="1"/></label><label>来源当前版本<input v-model="form.blockVersion" type="number" min="1"/></label></div><button v-if="data.status!=='VERIFIED_CLOSED'" :disabled="busy" @click="action('LINK_LIMIT')">关联本维修限制</button></template></template>
 <template v-if="section==='governance'"><label>可选申请处罚截止（最多30天）<input v-model="form.penaltyUntil" type="datetime-local"/></label><div class="actions"><button v-if="data.status==='NOTICE'" :disabled="busy" @click="action('DISMISS')">撤销通知，原权保持</button><button v-if="data.status==='NOTICE'" class="danger-button" :disabled="busy" @click="action('REVOKE')">陈述期结束后明确收回</button><button v-if="data.status==='APPEALED'" :disabled="busy" @click="action('UPHOLD')">独立复核维持</button><button v-if="data.status==='APPEALED'" class="primary" :disabled="busy" @click="action('OVERTURN')">独立复核纠正</button></div><p class="muted">原裁决人不得复核自己的申诉；纠正不覆盖后来合法取得位置的人。</p></template>
</section>
<section v-if="!id&&['venues','events','batches','blocks','governance'].includes(section)" class="panel"><h2>{{{venues:'申请使用场地',events:'创建图书馆活动',batches:'配置长期批次',blocks:'建立有来源的空间限制',governance:'有依据地发起处置'}[section]}}</h2>
<form @submit.prevent="submit(section==='venues'?'venue':section==='events'?'event':section==='batches'?'batch':section==='governance'?'governance':'none')">
 <template v-if="['venues','blocks'].includes(section)"><div class="form-grid"><label>选择空间<select v-model="form.spaceId" required><option :value="0" disabled>请选择实际空间</option><option v-for="sp in spaces.filter(s=>section==='blocks'||s.useMode==='VENUE')" :key="sp.id" :value="sp.id">{{sp.code}} · {{sp.name}} · 容量{{sp.capacity}}人</option></select></label><label v-if="section==='venues'">预计人数<input v-model="form.people" type="number" min="1" required/></label><label v-if="section==='blocks'">来源类型<select v-model="form.kind"><option v-for="k in ['MAINTENANCE','SAFETY','COURSE','EVENT']" :key="k" :value="k">{{{MAINTENANCE:'维护',SAFETY:'安全',COURSE:'课程',EVENT:'活动审批'}[k]}}</option></select></label><label v-for="key in ['startsAt','endsAt']" :key="key">{{fieldNames[key]}}<input v-model="form[key]" type="datetime-local" required/></label></div></template>
 <template v-if="section==='venues'"><label>用途<input v-model="form.purpose" maxlength="100" required/></label><label>申请说明<textarea v-model="form.description" maxlength="1000" required/></label><label>联系方式<input v-model="form.contact" maxlength="100" required/></label><button class="primary" :disabled="busy">保存场地申请</button></template>
 <template v-if="section==='events'"><label>本人场地申请<select v-model="form.venueRequestId" required><option :value="0">请选择申请</option><option v-for="v in aux.filter(v=>v.status==='APPROVED')" :key="v.id" :value="v.id">{{v.code||'空间 '+v.space_id}} · {{v.purpose}} · {{formatTime(v.starts_at)}}</option></select></label><div class="form-grid"><label>活动名称<input v-model="form.title" maxlength="100" required/></label><label>类型<select v-model="form.eventType"><option value="READING">读书会</option><option value="CLASS">公开课</option><option value="LECTURE">讲座</option><option value="OTHER">其他</option></select></label><label>主讲人<input v-model="form.speaker" maxlength="100"/></label><label>参与容量<input v-model="form.capacity" type="number" min="1" required/></label><label v-for="key in ['opensAt','closesAt','promotionUntil']" :key="key">{{fieldNames[key]}}<input v-model="form[key]" type="datetime-local" required/></label></div><label>活动介绍<textarea v-model="form.description" maxlength="2000" required/></label><label>注意事项<textarea v-model="form.notice" maxlength="500"/></label><button class="primary" :disabled="busy">先保存活动草稿</button></template>
 <template v-if="section==='batches'"><p class="alert warning">大规模配置建议在桌面完成。全部时间提前公布；随机来源不可事后选择，失败也必须明确通知。</p><div class="form-grid"><label>批次名称<input v-model="form.title" maxlength="100" required/></label><label>声明用途<select v-model="form.batchPurpose"><option value="POSTGRADUATE">考研</option><option value="CIVIL_SERVICE">考公</option><option value="OTHER">其他长期备考</option></select></label><label v-for="key in batchTimes" :key="key">{{fieldNames[key]}}<input v-model="form[key]" type="datetime-local" required/></label><label>递补响应时间（60–86400秒）<input v-model="form.promotionSeconds" type="number" min="60" max="86400"/></label></div><fieldset><legend>可分配长期座位（最多400个）</legend><label v-for="s in spaces" :key="s.id" class="seat-choice"><input v-model="form.seatIds" type="checkbox" :value="s.id"/>{{s.code}} · {{s.name}}</label></fieldset><p class="muted">已选{{form.seatIds.length}}位；窗口顺序与场地冲突仍由服务端裁决。</p><button class="primary" :disabled="busy||!form.seatIds.length">保存批次规则</button></template>
 <template v-if="section==='blocks'"><template v-if="form.kind==='EVENT'"><div class="form-grid"><label>活动场地申请编号<input v-model="form.venueRequestId" type="number" min="1"/></label><label>申请当前版本<input v-model="form.venueVersion" type="number" min="1"/></label></div></template><label>来源与理由<textarea v-model="form.reason" maxlength="500" required/></label><button type="button" @click="previewBlock">预览完整影响</button><div v-if="preview" class="impact-preview"><h3>影响{{preview.impacts.length}}项 · 需通知{{preview.notifyCount}}人</h3><p class="muted">观察时点{{formatTime(preview.asOf)}}；预览不是批准权。</p><article v-for="i in preview.impacts" :key="i.impactKey"><strong>{{i.kind}} #{{i.originId}} · 空间{{i.fromSpaceId}}</strong><p>{{formatTime(i.startsAt)}} — {{formatTime(i.endsAt)}}</p><template v-if="i.needsResolution"><label>明确处置<select v-model="choices[i.impactKey].action"><option value="">必须选择</option><option v-for="a in choicesFor(i.kind)" :key="a" :value="a">{{{MOVE:'移动到等效座位',CANCEL:'明确取消并通知',TEMPORARY:'保留原权并安排临时位',UNAVAILABLE:'明确暂不可用',RELOCATE:'换用原组织者的新申请'}[a]}}</option></select></label><label v-if="['MOVE','TEMPORARY'].includes(choices[i.impactKey].action)">真实替代座位<select v-model="choices[i.impactKey].target"><option value="">请选择</option><option v-for="sp in spaces.filter(s=>s.kind==='SEAT'&&s.id!==i.fromSpaceId)" :key="sp.id" :value="sp.id">{{sp.code}} · {{sp.name}}</option></select></label><label v-if="choices[i.impactKey].action==='RELOCATE'">替代场地申请ID<input v-model="choices[i.impactKey].venue" type="number" min="1"/></label></template><p v-else class="muted">批次资源保护项，不虚构当前持权人；通知受影响申请人。</p></article><button type="button" class="primary" :disabled="busy" @click="commitBlock">重新核对完整方案后提交</button></div></template>
 <template v-if="section==='governance'"><p class="muted">从授权使用权选择编号与当前版本；不能从无人使用推导重新分配权。</p><div class="right-choices"><button v-for="r in rights.filter(r=>r.status==='ACTIVE')" :key="r.id" type="button" :class="{selected:Number(form.entitlementId)===r.id}" @click="chooseRight(r)">{{r.code}} · 主体{{r.user_id}} · 权利{{r.id}} / v{{r.version}}</button></div><div class="form-grid"><label>使用权编号<input v-model="form.entitlementId" type="number" min="1" required/></label><label>已核实当前版本<input v-model="form.entitlementVersion" type="number" min="1" required/></label><label>明确原因<select v-model="form.reasonCode"><option value="FALSE_DECLARATION">资格声明无效</option><option value="UNAUTHORIZED_TRANSFER">未经授权转让</option><option value="PERSISTENT_OBSTRUCTION">经通知仍持续妨碍空间使用</option><option value="EXPLICIT_RULE_VIOLATION">明确违反空间规则</option></select></label><label>陈述截止（24小时–7天）<input v-model="form.statementUntil" type="datetime-local" required/></label></div><label>核实依据<textarea v-model="form.description" maxlength="3000" required/></label><button class="primary" :disabled="busy">保存通知，原权保持</button></template>
</form></section>
</template>
</template>
