"""Fixed M4 witnesses and SQL assertions; not discovered from green reports."""

M4_CASES = {
    "FeedbackIT": [
        "reportsArePrivateAndNeverBecomeFactsWithoutScopedVerification",
        "duplicateRepairCreationReturnsOriginalReceiptAfterReportVersionsAdvance",
        "workDoneIsNotResolvedAndFailedVerificationCanContinue",
        "secondReporterNotificationFaultRollsBackFactsAndAllResolutions",
        "verificationCannotCloseTheSameFacilityWhileItsKnownBrokenFactRemains",
        "attachmentsAreBoundedPrivateAndContentVerifiedWithIdempotentReplay",
        "competingReportDecisionsRejectStaleVersionAndKeepOriginal",
        "queuedVerificationLosesAuthorityWhenScopeIsRevokedBeforeFloorRelease",
        "malformedSecondFactCannotPartiallyPublishTheFirstFactOrDecision",
    ],
    "SpaceBlocksIT": [
        "stalePreviewCannotSilentlyCoverNewShortReservation",
        "duplicateCompletePlanReplaysOriginalReceiptAndMoveKeepsDeadline",
        "overlappingLimitsKeepOriginalRightAndRevokeOnlyOneSource",
        "temporarySeatCanBeLimitedAgainAndUpstreamReleaseDoesNotLeakDownstreamClaim",
        "affectedOpenOfferNeedsCurrentImpactAndExpirationReleasesTemporaryHoldWithoutTask",
        "staleAcknowledgementDoesNotConfirmChangedOfferButCurrentAcknowledgementDoes",
        "secondNotificationFaultRollsBackLimitArrangementsAndShortChanges",
        "scopeRevokedDuringFloorWaitCannotCreateLimit",
        "concurrentPlansCannotMoveTwoPeopleToSameTemporarySeat",
        "mismatchedOverlappingAlternativesRollBackWithoutEditingOriginalResult",
        "shrinkingImpactAfterExpiryStillInvalidatesOldPreview",
        "safetyCanExposeRealUnavailableWindowButPlannedCourseCannot",
        "temporaryWindowHasHalfOpenEndWithoutLosingLongOwnership",
        "resolvedEventApprovalAndCancellationPreserveOtherLimitAndParticipationHistory",
        "relocatingPeopleDoesNotMakeMaintenanceAreaAvailableForEvent",
        "restoringLimitNotifiesOriginalWithdrawnAndLaterApplicantWithoutInboxAuthority",
        "secondRestoreNotificationFailureRollsBackSourceAndWholeRecipientSet",
        "movedTargetDeactivationCannotEraseOriginalReceipt",
        "plannedCourseCrossingStartDuringWritesCannotCommit",
        "canceledEventRetainsPoolRecipientsAndRollsBackSecondRestoreNotice",
        "eventCancelHoldsBatchBeforeWaitingForFloorSoApplicantCannotSlipIntoRestoreSet",
        "verifiedTemporaryFacilityInvalidatesOldAcknowledgementAndRejectsCurrentUnsafeTarget",
        "originalFacilityUpdateNotifiesApplicantWithoutChangingFrozenResult",
        "missingHistoricalFacilityRequirementsRemainUnknownInsteadOfInheritingNewProfile",
        "reducingOriginalProfileCannotEraseExistingTemporaryRequirements",
        "repairVerificationReleasesOnlyOwnSourceAfterFailedAttempt",
        "secondRepairRestoreNoticeRollsBackFactsReportsSourceAndReceipt",
        "endedRawActiveLimitCannotBecomeANewRepairSource",
        "repairCannotLinkWrongSpaceOrCourseOrReplaceItsSource",
    ],
    "GovernanceCasesIT": [
        "noticeIsPrivateAndCannotRevokeBeforeAtLeastTwentyFourHours",
        "statementVersionsAreRetainedAndExactDeadlineIsClosed",
        "aVoluntaryExitCannotBeMisrepresentedAsAnAdministrativeRevocation",
        "originalNoticeReceiptCanReplayAfterTheEntitlementVersionChanges",
        "independentAppealCanRestoreAnActuallyFreeOriginalSeat",
        "appealCannotStealASeatAlreadyAcceptedByTheStableWaitlist",
        "activePenaltyRejectsNewApplicationButExpiresWithoutATaskAndKeepsOldReceipt",
        "decisionNotificationFaultRollsBackRevocationPenaltyAndReceipt",
        "appealCorrectionNotificationFaultCannotPartiallyRestoreOrDropThePenalty",
        "appealAtTheExactSeventhDayCannotReopenTheOldDecision",
        "administratorLosingScopeWhileWaitingCannotRevokeTheRight",
        "concurrentDecisionsCannotOverwriteEachOtherWithTheSameVersion",
        "aCurrentMaintenanceLimitMakesCorrectionExplicitlyUnavailable",
        "unpublishedCancellationReleasesOnlyCurrentPoolProtectionAndKeepsApplicationHistory",
        "unusedPublishedCancellationRejectsLiveOfferThenRetainsFormalResultWhenExpired",
        "aRoundWithConfirmedHistoryCannotUseTheUnusedCancellationShortcut",
        "penaltyIntroducedAfterSubmissionExcludesTheCandidateAtFreezeWithoutChangingTheSubmittedVersion",
        "penaltyAfterFreezeStopsWholePublicationInsteadOfSilentlyShrinkingFrozenPeople",
        "anOpenOfferCannotBeConfirmedAfterCurrentQualificationIsRevoked",
        "stableWaitlistCannotPromoteSomeoneUnderACurrentPenaltyFromAnotherCycle",
    ],
}
INVARIANTS = ["earlyRevocationCases", "selfReviewedCases", "overlappingLongUserPairs", "canceledBatchWithRightsHistory", "originalEntitlementCoordinateDrift"]
M4_MEASURES = {case: {"invariants/"+key: 0 for key in INVARIANTS} for cases in M4_CASES.values() for case in cases}
SPECIFIC = {
    "reportsArePrivateAndNeverBecomeFactsWithoutScopedVerification": {"verifiedFacts": 2, "reports": 1},
    "duplicateRepairCreationReturnsOriginalReceiptAfterReportVersionsAdvance": {"repairs": 1},
    "workDoneIsNotResolvedAndFailedVerificationCanContinue": {"failedVerificationHistory": 1, "closedRepairs": 1},
    "secondReporterNotificationFaultRollsBackFactsAndAllResolutions": {"resolutionsAfterRecovery": 2, "formalRepairClosures": 1},
    "verificationCannotCloseTheSameFacilityWhileItsKnownBrokenFactRemains": {"verificationStatus": 409, "publicCondition": "BROKEN", "reportStatus": "IN_REPAIR"},
    "attachmentsAreBoundedPrivateAndContentVerifiedWithIdempotentReplay": {"attachments": 3, "privatePeerStatus": 404},
    "competingReportDecisionsRejectStaleVersionAndKeepOriginal": {"history": 2},
    "queuedVerificationLosesAuthorityWhenScopeIsRevokedBeforeFloorRelease": {"factsAfterRevoke": 0},
    "malformedSecondFactCannotPartiallyPublishTheFirstFactOrDecision": {"partialFacts": 0},
    "scopeRevokedDuringFloorWaitCannotCreateLimit": {"space_block": 0},
    "plannedCourseCrossingStartDuringWritesCannotCommit": {"space_block": 0},
    "secondNotificationFaultRollsBackLimitArrangementsAndShortChanges": {"space_block": 0, "short_relocation": 0},
    "overlappingLimitsKeepOriginalRightAndRevokeOnlyOneSource": {"space_blockStates": ["ACTIVE", "REVOKED"], "seat_entitlementStates": ["ACTIVE"]},
    "repairVerificationReleasesOnlyOwnSourceAfterFailedAttempt": {"space_blockStates": ["ACTIVE", "REVOKED"], "repair_ticketStates": ["VERIFIED_CLOSED"], "feedback_reportStates": ["RESOLVED"]},
    "secondRepairRestoreNoticeRollsBackFactsReportsSourceAndReceipt": {"fault/space_blockStates": ["ACTIVE"], "fault/repair_ticketStates": ["WORK_DONE"], "fault/feedback_reportStates": ["IN_REPAIR", "IN_REPAIR"], "fault/facts": 0, "fault/receipts": 0, "space_blockStates": ["REVOKED"], "repair_ticketStates": ["VERIFIED_CLOSED"]},
    "noticeIsPrivateAndCannotRevokeBeforeAtLeastTwentyFourHours": {"governance_caseStates": ["NOTICE"], "seat_entitlementStates": ["ACTIVE"], "long_application_penaltyStates": []},
    "statementVersionsAreRetainedAndExactDeadlineIsClosed": {"governance_caseStates": ["REVOKED"], "seat_entitlementStates": ["REVOKED"]},
    "aVoluntaryExitCannotBeMisrepresentedAsAnAdministrativeRevocation": {"governance_caseStates": ["DISMISSED"], "seat_entitlementStates": ["RELINQUISHED"]},
    "independentAppealCanRestoreAnActuallyFreeOriginalSeat": {"governance_caseStates": ["RESTORED"], "seat_entitlementStates": ["ACTIVE"], "long_application_penaltyStates": ["OVERTURNED"]},
    "appealCannotStealASeatAlreadyAcceptedByTheStableWaitlist": {"governance_caseStates": ["CORRECTED_UNAVAILABLE"], "seat_entitlementStates": ["ACTIVE", "REVOKED"]},
    "decisionNotificationFaultRollsBackRevocationPenaltyAndReceipt": {"faultCaseStatus": "NOTICE", "faultEntitlementStatus": "ACTIVE", "faultPenaltyStates": [], "faultReceipts": 0, "governance_caseStates": ["REVOKED"], "seat_entitlementStates": ["REVOKED"], "long_application_penaltyStates": ["ACTIVE"]},
    "appealCorrectionNotificationFaultCannotPartiallyRestoreOrDropThePenalty": {"faultCaseStatus": "APPEALED", "faultEntitlementStatus": "REVOKED", "faultPenaltyStates": ["ACTIVE"], "faultReceipts": 0, "governance_caseStates": ["RESTORED"], "seat_entitlementStates": ["ACTIVE"], "long_application_penaltyStates": ["OVERTURNED"]},
    "appealAtTheExactSeventhDayCannotReopenTheOldDecision": {"governance_caseStates": ["REVOKED"]},
    "administratorLosingScopeWhileWaitingCannotRevokeTheRight": {"governance_caseStates": ["NOTICE"], "seat_entitlementStates": ["ACTIVE"]},
    "concurrentDecisionsCannotOverwriteEachOtherWithTheSameVersion": {"governance_history": 2},
    "aCurrentMaintenanceLimitMakesCorrectionExplicitlyUnavailable": {"governance_caseStates": ["CORRECTED_UNAVAILABLE"], "seat_entitlementStates": ["REVOKED"], "space_blockStates": ["ACTIVE"]},
    "unusedPublishedCancellationRejectsLiveOfferThenRetainsFormalResultWhenExpired": {"preparation_batchStates": ["CANCELED"], "seat_entitlementStates": [], "long_offerStates": ["CANCELED"], "allocation_result": 1},
    "aRoundWithConfirmedHistoryCannotUseTheUnusedCancellationShortcut": {"preparation_batchStates": ["RESULT_PUBLISHED"], "seat_entitlementStates": ["RELINQUISHED"]},
    "penaltyIntroducedAfterSubmissionExcludesTheCandidateAtFreezeWithoutChangingTheSubmittedVersion": {"preparation_batchStates": ["FROZEN", "RESULT_PUBLISHED"]},
    "penaltyAfterFreezeStopsWholePublicationInsteadOfSilentlyShrinkingFrozenPeople": {"preparation_batchStates": ["FAILED_NO_RESULT", "RESULT_PUBLISHED"]},
    "anOpenOfferCannotBeConfirmedAfterCurrentQualificationIsRevoked": {"long_offerStates": ["ACCEPTED", "INVALID"], "seat_entitlementStates": ["REVOKED"]},
}
for name, measures in SPECIFIC.items():
    M4_MEASURES[name].update(measures)
